.changeset/sour-weeks-live.md, package-lock.json, packages/cli/package.json, packages/cli/src/command_failure_handler.test.ts, packages/cli/src/command_failure_handler.ts, packages/cli/src/command_middleware.test.ts, packages/cli/src/command_middleware.ts, packages/cli/src/commands/generate/generate_command.ts, packages/cli/src/commands/sandbox/sandbox-delete/sandbox_delete_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.ts, packages/cli/src/error/credential_error.ts, packages/cli/src/error/profile_error.ts
https://app.asana.com/0/1205484060153101/1205891697777566/f
1. Add region validation for AWS profile.
2. Customize error message (and suppress help output) for validation failure.
```
% amplify sandbox   
Region is missing. Please refer to this page for region setting options:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html
To configure a new Amplify profile, use "amplify configure profile".
To update an existing profile, use "aws configure"
% amplify sandbox --profile invalid
Failed to load aws credentials for profile 'invalid'.
To configure a new Amplify profile, use "amplify configure profile".
To update an existing profile, use "aws configure"
```
By submitting this pull request, I confirm that …
=> Region validation

.changeset/clever-snails-guess.md, .changeset/shaggy-bears-smile.md, package-lock.json, packages/auth-construct/API.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/types.ts
Converts to string union, so that it does not require importing Cognito.OAuthScopes:
Also, improve documentation for verificationMessage:
=> fix: Auth types and documentation

.changeset/curvy-hotels-begin.md, packages/auth-construct/src/construct.ts, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
The default authenticated roles that were being created were overly permissive and was not tied to the specific identity pool. This will leave the created app to be vulnerable as it can be exploited.
This change will apply condition to these roles so its tied down to specific identity pools created when auth construct is deployed.
=> fix: add conditions to auth & unauth roles

.changeset/giant-meals-itch.md, package-lock.json, packages/cli/src/command_middleware.test.ts
The unit test on loading credential from environment variables fail if the running env has AWS_PROFILE set. Why?  `fromNodeProviderChain` will ignore credential envVars (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY...) if `AWS_PROFILE` is set.
=> Fix profile validation unit test

.changeset/flat-lies-hope.md, package-lock.json, packages/create-amplify/src/gitignore_initializer.test.ts, packages/create-amplify/src/gitignore_initializer.ts, packages/integration-tests/src/test-e2e/create_amplify.test.ts
- Add `# amplify` to separate amplify content in `.gitignore`
- Ensure amplify content is separated with a newline from other content
=> Add amplify comment when writing to .gitignore

.changeset/small-readers-check.md, .github/workflows/poc-e2e-flow-test.yml, packages/create-amplify/src/npm_package_manager_controller.ts, packages/create-amplify/src/tsconfig_initializer.ts, packages/integration-tests/src/test-e2e/create_amplify.test.ts
This is a followup PR of https://github.com/aws-amplify/amplify-backend/pull/533
- Use GH Workflow Matrix to run test-e2e/create_amplify.test.ts with different Package Managers
- Temporarily use Env Var as an indicator of Package Managers
*Note*:
- Modern Yarn x Node 18/20 fails for https://github.com/yarnpkg/berry/issues/4694 and  https://github.com/yarnpkg/berry/issues/5951 , so we use Node 19 in this PR. However, Node 19 is already deprecated. I wonder if we should test Node 20 (exclude Modern Yarn) and Node 19 only for Modern Yarn?
*Test*: https://github.com/aws-amplify/amplify-backend/actions/runs/6856166344
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> test: use GH workflow for e2e test of create amplify

.changeset/wet-emus-smile.md, package-lock.json, packages/cli/src/commands/generate/config/generate_config_command.test.ts, packages/client-config/API.md, packages/client-config/src/client-config-types/client_config.ts, packages/client-config/src/client-config-types/mobile/client_config_mobile_types.ts, packages/client-config/src/client-config-writer/client_config_converter.test.ts, packages/client-config/src/client-config-writer/client_config_converter.ts, packages/client-config/src/client-config-writer/client_config_formatter.test.ts, packages/client-config/src/client-config-writer/client_config_formatter.ts, packages/client-config/src/client-config-writer/client_config_writer.test.ts, packages/client-config/src/client-config-writer/client_config_writer.ts, packages/client-config/src/generate_client_config_to_file.ts, packages/client-config/src/paths/get_client_config_path.test.ts, packages/client-config/src/paths/get_client_config_path.ts
**Issue #, if available:**
https://app.asana.com/0/1205484060153101/1205931466811581/f
**Description of changes:**
This PR 
1. adds initial version of iOS/Android config by transforming JS config into desired schema
2. adds `json-mobile` format
3. fixes dart format to conform to the same format as other mobile platform
**Assumptions**
1. This is a solution until frontend format is unified in https://app.asana.com/0/1205484060153101/1205931466811588/f 
2. Data parity between JS and mobile format can be achieved by adding necessary fields to JS config and transforming them into mobile.
**Out of scope**
This PR does not attempt to unify format across JS and mobile libraries. Neither it tries to change "config contributors" to use "generalized format" and keeps using JS as externally facing …
=> feat: generate mobile friendly config

.changeset/loud-boats-yell.md, packages/backend/API.md, packages/backend/src/backend.ts, packages/backend/src/backend_factory.test.ts, packages/backend/src/backend_factory.ts, packages/backend/src/engine/nested_stack_resolver.test.ts, packages/backend/src/engine/nested_stack_resolver.ts
Previously `backend.getStack(name)` would create a new stack if "name" did not already exist and return the existing stack if it did exist. This changes the method to `backend.createStack(name)` and will create a new stack if "name" does not already exist and throw if name does exist.
=> change backend.getStack to backend.createStack

.changeset/nine-brooms-sneeze.md, packages/cli/src/command_middleware.test.ts, packages/cli/src/command_middleware.ts, packages/cli/src/commands/configure/configure_profile_command.test.ts, packages/cli/src/commands/configure/configure_profile_command.ts
1. Simplify error messages from profile validation. If a customer already has a profile, they probably know how to fix if seeing credentials or region error. They either use `aws configure` or manual init file editing. Adding all details here is not necessary so simplifying it per PM suggested.
2. Update the URL for `amplify configure profile`- Note that the new URL http://docs.amplify.aws/gen2/start/configure-account is not live yet.
```
% amplify sandbox
Failed to load default aws region: Region is missing.
To configure a new Amplify profile, use "amplify configure profile".
% amplify sandbox      
Failed to load default aws credentials: Could not load credentials from any providers.
To configure a new Amplify profile, use "amplify …
```
=> Update profile error messages

.changeset/fair-jars-switch.md, package-lock.json, packages/backend-data/src/convert_authorization_modes.test.ts, packages/backend-data/src/convert_authorization_modes.ts, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataamplifyDataTodo80505FFF.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataamplifyDataTodo80505FFF.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataamplifyDataTodo80505FFF.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataamplifyDataTodo80505FFF.nested.template.json, packages/integration-tests/test-projects/minimalist-project-with-typescript-idioms/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
N/A
Use `ref` instead of `logicalId` on L1 CfnIdentityPool to grab the correct value.
Confirmed in test app that value in template goes from `$util.qr($ctx.stash.put("identityPoolId", "amplifyAuthIdentityPool3FDE84CC"))` to `$util.qr($ctx.stash.put("identityPoolId", "us-west-2:f7e8f1cb-49e8-4347-ae71-0cbe7ec9874e"))`.
=> fix: use correct logical id for identity pool

.changeset/spicy-carrots-shave.md, packages/client-config/src/client-config-types/mobile/client_config_mobile_types.ts, packages/client-config/src/client-config-writer/client_config_converter.test.ts, packages/client-config/src/client-config-writer/client_config_converter.ts
This PR adds necessary fields for mobile authenticator to work.
Tested with the following app.
```
package dev.salih.myamplifyapp
import android.app.Application
import android.util.Log
import com.amplifyframework.AmplifyException
import com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin
import com.amplifyframework.core.Amplify
class MyAmplifyApp: Application() {
override fun onCreate() {
super.onCreate()
try {
Log.i("MyAmplifyApp", "Before initializing Amplify")
Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.configure(applicationContext)
Log.i("MyAmplifyApp", "Initialized Amplify")
} catch (error: AmplifyException) {
Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
}
}
}
```
```
package dev.salih.myamplifyapp
import …
```
=> fix: add required fields to mobile config

.changeset/pretty-mice-camp.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts
A `!` pattern have different meanings for .gitignore and glob pattern (used in sandbox excludes). 
The `!` pattern in gitignore means explicitly to add back (i.e. include) the file/folder immediately followed by `!` if other more generic patterns are excluding it.
However in glob patterns, `!` pattern means include everything **but** the file/folder immediately followed by `!`
As an example for a .gitignore file
```ignore
...
output
!output/file-i-want-to-check-in.ts
...
```
If this file is fed to the [sandbox's watcher](https://github.com/parcel-bundler/watcher) exclude, it will essentially means exclude everything but `file-i-want-to-check-in.ts` overriding the `src`, `amplify` directories and everything else.
[sandbox's …
=> fix: handling !pattern in gitignore to avoid excluding everything from watching in sandbox

.changeset/ninety-days-kick.md, packages/backend-deployer/src/cdk_deployer.ts
*Description of changes:* Piping the child process output by default strips off the color for consuming streams. This is a workaround to preserve the color being piped to parent process. See https://github.com/Marak/colors.js/issues/127#issuecomment-392249836
=> fix: Force colors to not be stripped off when piping child process stdout

.changeset/sour-bananas-enjoy.md, package-lock.json, packages/backend-data/package.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
N/A
Bump data dep to include change that will set the correct attribution stackType (e.g. AmplifySandbox, AmplifyPipelineDeploy, AmplifyCDk, etc.)
=> chore: bump data construct to support sandbox/pipeline/cdk attribution tags

.changeset/khaki-pumas-cover.md, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.test.ts, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.test.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.ts
1. Avoid crashing sandbox on failure to generate client config but print that we couldn't
2. If the metadata cannot be retrieved because stack is in progress, let the customers know
3. Backfill tests
=> chore: avoid crashing sandbox on failing to retrieve metadata

.changeset/green-keys-cough.md, packages/cli/src/commands/generate/config/generate_config_command.test.ts, packages/cli/src/commands/generate/config/generate_config_command.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.test.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts
Removes requirement to pass in stack or app-id to Config and Model generation commands. The CLI will fall back to using the stack identifier when no identifier is explicitly provided.
=> fix: remove id input validations in order to fall back to stack id

.changeset/rich-carrots-rule.md, package-lock.json, packages/form-generator/package.json, packages/form-generator/src/local_codegen_graphql_form_generator.ts
update form renderer to render amplify js v6 code.
upgrades `@aws-amplify/codegen-ui` and `@aws-amplify/codegen-ui-react` to get the latest code generation version.
=> fix(form-generator): update form renderer to render amplify js v6 code

.changeset/mighty-bottles-deliver.md, packages/client-config/src/client-config-types/mobile/client_config_mobile_types.ts, packages/client-config/src/client-config-writer/client_config_converter.test.ts, packages/client-config/src/client-config-writer/client_config_converter.ts
**Description of changes:**
This adds fields that are required by `dart` libs. (These fields are also present in other mobile configs but were ignored by respective platforms).
**Before**
**After**
=> feat: add missing fields for mobile config

.changeset/strange-pandas-know.md, packages/cli/src/commands/configure/configure_profile_command.test.ts, packages/cli/src/commands/configure/configure_profile_command.ts
The account setup URL has changed to `https://docs.amplify.aws/gen2/start/account-setup/`
Confirmed with @josefaidt  `https://next-docs.amplify.aws/gen2/start/account-setup/`
=> Change account setup URL

.github/workflows/health_checks.yml
This change flips from 8 core to 4 core ubuntu worker.
It has been confirmed in https://github.com/aws-amplify/amplify-backend/pull/694 and https://github.com/aws-amplify/amplify-backend/pull/695 . That our e2e test workload is mostly memory and i/o bound, so downgrading to 4 cores that has enough memory to run multiple deployments in parallel. I.e. runtime is ~same on 4,8 and 16 core.
=> build: use ubuntu 4 core for e2e tests

.changeset/dull-keys-punch.md, packages/backend-data/API.md, packages/backend-data/src/convert_authorization_modes.test.ts, packages/backend-data/src/convert_authorization_modes.ts, packages/backend-data/src/index.ts, packages/backend-data/src/types.ts, packages/create-amplify/templates/basic-auth-data/amplify/data/resource.ts, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/amplify/data/resource.ts, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json, packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
> Align the terminology used in defineData and mark UPPER_CASE_FORMAT as deprecated
> In the client it's `authMode: 'userPool', 'apiKey'`
>
> Acceptance criteria:
> Support both camel case and UPPER_SNAKE_CASE format but mark all UPPER_CASE_FORMAT as deprecated
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
In this review, with product input, we have decided not to support the UPPER_SNAKE_CASE on the schema definition surface, keeping only the camel case values consistent with the `aws-amplify` client library.
This change does the following:
- Introduces `'iam' | 'userPool' | 'oidc' | 'apiKey' | 'lambda'` as DefualtAuthorizationMode options
- Translates these to the …
=> fix(@aws-amplify/backend-data) - Align authorization modes with client

.changeset/cool-mirrors-protect.md, packages/create-amplify/src/amplify_project_creator.test.ts, packages/create-amplify/src/amplify_project_creator.ts
- adds `npx` to `amplify` commands that print at the end of create-amplify
In its current state it can be confused for gen1 CLI that is installed globally.
=> add npx to "get started" command in create-amplify

.changeset/moody-pugs-drive.md, packages/backend-deployer/src/cdk_deployer.ts
*Description of changes:* fix: hide tsc --showConfig output since its used for validation only
=> fix: hide tsc --showConfig output since its used for validation only

.changeset/friendly-icons-decide.md, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts
Change secret name argument to kebab-case
```
% amplify sandbox secret --help
amplify sandbox secret <command>
Manage sandbox secret
Commands:
amplify sandbox secret set <secret-name>  Set a sandbox secret
amplify sandbox secret remove <secret-na  Remove a sandbox secret
me>
amplify sandbox secret get <secret-name>  Get a sandbox secret
amplify sandbox secret list               List all sandbox secrets
Options:
--profile  An AWS profile name.                                       [string]
--help     Show help                                                 [boolean]
% amplify sandbox secret set --help
amplify sandbox secret set <secret-name>
Set a sandbox secret
Positionals:
secret-name  Name of the secret to set …
```
=> Change secret name argument to kebab-case

package-lock.json, package.json
Canary [build586](https://github.com/aws-amplify/amplify-backend/actions/runs/6934039976/job/18861438228) faiiled for error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: amplify-vnext@0.0.1
npm ERR! Found: typescript@5.3.2
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^5.0.4" from the root project
npm ERR!   peer typescript@">=4.4" from eslint-config-xo-typescript@0.5[7](https://github.com/aws-amplify/amplify-backend/actions/runs/6934039976/job/18861438228#step:4:8).0
npm ERR!   node_modules/eslint-config-xo-typescript
npm ERR!     dev eslint-config-xo-typescript@"^0.57.0" from the root project
npm ERR!   1 more (@aws-amplify/backend-deployer)
npm ERR! 
npm ERR! Could not …
```
=> fix: typedoc version for conflict

.changeset/plenty-maps-doubt.md, packages/backend-data/src/convert_schema.test.ts, packages/backend-data/src/convert_schema.ts
N/A
Adding comments and friction around the criticality of not changing db provisioning strategy for data.
Plan to add an integration test verifying data continuity across update https://github.com/aws-amplify/amplify-backend/issues/691
=> chore: add friction and comment/test about not changing critical config values for AmplifyTable

.changeset/rotten-swans-study.md, packages/deployed-backend-client/src/deployed_backend_client.test.ts, packages/deployed-backend-client/src/deployed_backend_client.ts, packages/deployed-backend-client/src/deployed_backend_client_list_sandboxes.test.ts
N/A
There is currently an issue in deployed-backend-client where calling `getOutput` for every stack to determine `deploymentType: 'sandbox'` is causing high latency and throttling exceptions from `listSandboxes`.
This PR adds a heuristic to filter stacks that are not named using the sandbox naming convention in order to prevent excessive `getOutput` calls.
I've also refactored the test suite a bit since it was getting unruly.
=> fix: filter non-sandbox stacks

.eslintrc.cjs
This fixes IDE issues where it's not able to correctly resolve the tsconfig that corresponds to a particular file if there was a nested eslint config in the directory hierarchy of that file.
AFAICT, this config was not affecting eslint when running as a script; it was only affecting IDE lint error highlighting.
=> fix tsconfig resolution

.changeset/cuddly-ears-move.md, package-lock.json, packages/integration-tests/package.json, templates/construct/package.json
Fresh npm install without package-lock.json should succeed. 
Match aws-cdk-lib versions in sub-packages
=> match aws-cdk-lib versions

packages/integration-tests/package.json, packages/integration-tests/src/test-project-setup/passwordless_auth.ts, packages/integration-tests/src/test-project-setup/test_project_creator.ts, packages/integration-tests/src/test-projects/passwordless-auth/amplify/auth/resource.ts, packages/integration-tests/src/test-projects/passwordless-auth/amplify/backend.ts
add initial integ test setup for `passwordless-auth`
=> feat: add initial e2e integ test setup for passwordless auth

.github/workflows/canary_checks.yml, .github/workflows/health_checks.yml
Follow up to https://github.com/aws-amplify/amplify-backend/pull/768 to switch the e2e runner role arn name back to the original
=> switch role name

.changeset/nice-socks-complain.md, package-lock.json, packages/auth-construct/package.json, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts
*Issue 796*
https://github.com/aws-amplify/amplify-backend/issues/796
Replaces manual creation of ARN strings with official builder from AWS SDK
=> bug(796): Replaces arn construction logic with SDK parser

packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.test.ts, packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.ts, packages/passwordless-auth-construct/src/factories/challenge_service_factory.test.ts, packages/passwordless-auth-construct/src/magic-link/magic_link_challenge_service.ts, packages/passwordless-auth-construct/src/otp/otp_challenge_service.test.ts, packages/passwordless-auth-construct/src/otp/otp_challenge_service.ts, packages/passwordless-auth-construct/src/types.ts
Allow users to make up to 3 attempts when trying to confirm their OTP code before the auth session fails. This is accomplished by: 
1. Saving the OTP and delivery method under the `challengeMetadata` key in the response.
2. On failed attempts, restart the flow and reuse the saved OTP code and delivery method.
3. Fail auth session after 3 attempts 
=> feat(passwordless): Allow OTP Retry

packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.test.ts, packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.ts, packages/passwordless-auth-construct/src/magic-link/magic_link_challenge_service.test.ts, packages/passwordless-auth-construct/src/magic-link/magic_link_challenge_service.ts, packages/passwordless-auth-construct/src/types.ts
- validate the event including required metadata before checking for the existence of a user.
Prior to this change, an attacker could discover the existence of a user by making certain bad requests. For certain bad requests an error would be thrown only when the user existed. With the update the request validation happens first which ensures the same response is returned when the user does not exist.
=> chore: validate create event before validating user existence

.github/workflows/health_checks.yml, scripts/check_api_changes.ts, scripts/publish_local.ts
Fixes https://github.com/aws-amplify/amplify-backend/actions/runs/7177124185/job/19543184647?pr=810 .
Add option to retain git diff after local publish. I.e. retain information about versions that got published to verdaccio.
Test projects in api check use pinned versions to resolve package under test to make sure they don't accidentally pull wrong version.
I was debating if we should use `latest` in test project's package json but I figured using precise version is going to remove some doubts about what exactly is resolved.
=> test: fix api check - retain version information after local publish

.changeset/friendly-jokes-roll.md, packages/backend/src/engine/branch-linker/lambda/branch_linker.ts
This PR removes excessive logging from branch linker. Logging dumps of rest requests and responses poses a risk of logging of sensitive data.
This removes request and response dumps from logging messages.
I keep sanitized log messages instead of just removing them so that there's a trace of how logic flow executed.
PR checks. The log messages are not used in any logic.
=> fix: sanitize branch linker logs

.changeset/moody-grapes-move.md, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
`amplify pipeline-deploy` deploys cdk resources in CI/CD environments and runs `amplify generate config` automatically. However, `pipeline-deploy` does not currently allow an `--out-dir` to be specified, so the config is always written to the root of the project which is not always desired.
N/A
This pr adds the `--out-dir` argument to the `pipeline-deploy` command.
* unit tests
* performed deployment with `--out-dir` set
* performed deployment without `--out-dir` set
=> add --config-out-dir arg to pipeline-deploy

.changeset/calm-books-refuse.md, packages/backend-function/src/factory.test.ts
Currently for `defineFunction` we default to the oldest maintained Node LTS for runtime. We would need to know when the oldest maintained Node LTS changes in order to update the default as well.
Resolves #813
Add unit test that will start to fail once the current day's date reaches a specified date. This unit test includes comments to describe what it is there for and first steps to fix the unit test.
Manually ran the unit test with different `endDate` values:
- `endDate` is today = FAIL
- `endDate` is in the past = FAIL
- `endDate` is in the future = PASS
=> Add unit test to know when oldest node lts changes

.changeset/brown-taxis-allow.md, packages/cli/src/backend-identifier/local_namespace_resolver.ts, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.ts, packages/platform-core/src/package_json_reader.test.ts, packages/platform-core/src/package_json_reader.ts
Errors thrown due to invalid package json file are thrown as faults.
Throw user errors instead with remedy steps.
Unit tests amended.
=> classify package.json errors as user errors

.changeset/angry-avocados-teach.md, packages/cli/src/commands/configure/profile_controller.test.ts, packages/cli/src/commands/configure/profile_controller.ts
Fixes https://github.com/aws-amplify/amplify-backend/issues/881 .
Add logic to create directory if it doesn't exist yet when creating profile.
Added unit test.
=> fix: create dir if not exists when configuring profile

.changeset/angry-guests-notice.md, package-lock.json, packages/cli/src/commands/configure/configure_profile_command.test.ts, packages/cli/src/commands/configure/configure_profile_command.ts, packages/cli/src/commands/configure/profile_controller.test.ts, packages/cli/src/commands/configure/profile_controller.ts
When `npx amplify configure profile` creates `~/.aws/config` and `~/.aws/credentials` files, they were created with the default mode of "666" (read/write for owner/group/other). This is different than the permissions created when configuring these files using the AWS CLI which is "600" (read/write for owner only).
Fixes https://github.com/aws-amplify/amplify-backend/issues/884 although that is just a naming concern that is colocated with this change.
Sets the file mode to 600 when creating new config and credential files
Tested locally and added coverage to existing unit test
=> set user read/write only permissions when creating aws cred files

scripts/check_package_versions.ts, scripts/components/api-changes-validator/api_changes_validator.ts, scripts/components/dependencies_validator.ts, scripts/components/package-json/package_json.ts, scripts/setup_test_project.ts, scripts/update_tsconfig_refs.ts
We have couple of places in `scripts` that read and write package json and we keep re-defining types for it.
This PR removes that redundancy by introducing a component to define, read and write package json.
I was looking into packages like https://www.npmjs.com/package/type-fest that could provide typings, but I found that their typings lead to increased need for non-null assertions, so I chose to just centralize existing solution given it's simplicity.
Using 3rd party types later is still an option and should be easier to implement if this change goes in.
This PR checks.
=> build: refactor package json access

.github/workflows/health_checks.yml
Sometimes API check hangs on publish local packages step (which usually happens around release if branch is not synchronized with main).
While this doesn't solve the root cause, it makes these jobs fail faster. Otherwise they'd hang until default limit (60 min?) is hit.
This PR checks.
=> build: add timeouts in api check

.changeset/three-shrimps-shave.md, package-lock.json, packages/auth-construct/API.md, packages/auth-construct/README.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/types.ts
Previously, users would need to import types to specify the saml MetadataType, like this:
> `import { UserPoolIdentityProviderSamlMetadataType } from 'aws-cdk-lib/aws-cognito';`
> metadata: {
metadataContent: samlMetadataContent,
metadataType: UserPoolIdentityProviderSamlMetadataType.FILE,
},
Now, customers can simply specify "FILE" or "URL" without importing any types.
> metadata: {
metadataContent: samlMetadataContent,
metadataType: 'FILE',
},
DX:
=> fix: eliminate SAML type import by flattening MetadataType to string union

.changeset/weak-geese-allow.md, package-lock.json, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts
Users currently need to map the email attributes manually when using social providers.
For example: https://github.com/josefaidt/amplify-gen2-workaround-cognito-domain/blob/main/amplify/auth/resource.ts#L21-L25
The email attribute will be automatically mapped for social providers and for OIDC.
SAML is not automatically mapped.
=> fix: automatically map email attributes for social providers and OIDC

scripts/components/api-changes-validator/api_changes_validator.test.ts, scripts/components/api-changes-validator/api_usage_generator.test.ts, scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/src/index.ts
Fixes https://github.com/aws-amplify/amplify-backend/actions/runs/7628068742/job/20778342823?pr=942 .
```
Validation of model-generator completed successfully
Validation of client-config completed successfully
Validation of sandbox completed successfully
/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:87
throw new AggregateError(errors, 'There are validation failures');
^
AggregateError: There are validation failures
at <anonymous> (/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:87:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[errors]: [
Error: Validation of @aws-amplify/cli-core failed, compiler output:
index.ts(59,65): error TS2345: Argument of type 'T[]' is not assignable to parameter …
```
=> test: handle var args in api check

.changeset/lucky-lizards-tan.md, packages/backend-function/src/cjs_shim.ts, packages/backend-function/src/factory.ts
Error when executing functions with a 3p import:
```
Error: "Dynamic require of ___ is not supported"
```
This happens when the 3p import statement ends up with `require` syntax instead of `import` syntax while the function is formatted as ESM for top level await support for resolving secrets.
Add shim for cjs require that is injected into the function. Shim replaces `require`, `__filename`, and `__dirname`.
With a local project where the handler has `const { Buffer } = require('node:buffer');`:
Before change:
When executing function got the `Dynamic require` error mentioned above
After change:
Function execution is successful and secrets are resolved.
_By submitting this pull request, I confirm that my contribution …
=> inject shim for cjs dependencies

.changeset/metal-radios-pay.md, package-lock.json, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/client-config/src/client-config-contributor/auth_client_config_contributor.ts
OAuth settings were not being output to the frontend config if domainPrefix was missing.
OAuth settings will now be output to the frontend config even if domainPrefix is missing.
domainPrefix (as oauthDomain) will only be output if it is set.
Tests updated
=> fix: Output OAuth settings to config without requiring domain prefix

.changeset/many-lobsters-move.md, packages/auth-construct/API.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/types.ts
Resource names were not configurable. This is not aligned with the way things are handled in the Data construct.
This adds a 'name' property that is optional. If specified, the name prop is used to prefix resource names.
Users can customize name based on things like process.env.AWS_BRANCH as well.
Unit test added.
=> fix: Expose name prop to allow controlling resource naming

.changeset/perfect-crabs-grab.md, package-lock.json, packages/model-generator/package.json
Bumped `@aws-amplify/graphql-generator` package from `0.1` to `0.2`. 
The model introspection schema generated by `npx amplify generate config` now includes meta data for custom queries, mutations and subscriptions.
The feature PR from codegen: https://github.com/aws-amplify/amplify-codegen/pull/771
=> chore: bump graphql-generator version for custom GQL operations

.changeset/selfish-eels-jam.md, packages/backend-storage/API.md, packages/backend-storage/src/construct.test.ts, packages/backend-storage/src/construct.ts, packages/backend-storage/src/factory.test.ts, packages/backend-storage/src/factory.ts, packages/integration-tests/src/test-in-memory/integration_tests.test.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/storage/resource.ts, packages/integration-tests/src/test-projects/minimalist-project-with-typescript-idioms/amplify/storage/resource.ts, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.ts
We want to support multiple buckets at some point in the future which will require unique names for each `defineStorage` call.
Requires a name prop in `defineStorage`
Manually tested, added unit test coverage and updated existing tests.
=> Require name in defineStorage props

.changeset/tricky-socks-wash.md, packages/backend/src/default_stack_factory.test.ts, packages/backend/src/project_environment_main_stack_creator.ts
Currently we don't have tags added to any of the Gen2 stacks
Added below mentioned tags:
**For branch deployments:**
created-by = "amplify"
app-id = <backend namespace>
branch-name = <backend name>
deployment-type = "branch"
**For sandbox deployments:**
created-by = "amplify"
deployment-type = "sandbox"
- Added unit tests
- Tested on my local setup 
=> feat: added tags to the stack resources

.changeset/angry-zebras-tease.md, .eslint_dictionary.json, packages/client-config/API.md, packages/client-config/src/client-config-types/client_config.ts, packages/client-config/src/client-config-types/geo_client_config.ts, packages/client-config/src/client-config-types/mobile/client_config_mobile_types.ts, packages/client-config/src/client-config-writer/client_config_converter.test.ts, packages/client-config/src/client-config-writer/client_config_converter.ts, packages/client-config/src/index.ts
This PR adds typings for geo category in client config.
Added:
- typings in ClientConfig for geo
- added mapping to mobile format
- added unit test
Unit test
=> cover geo in client config

.changeset/proud-brooms-live.md, .eslint_dictionary.json, packages/auth-construct/API.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/types.ts
Users would need to import OidcAttributeRequestMethod to specify values for attributeRequestMethod.
The attributeRequestMethod type has been converted to a string union in order to eliminate the need to import OidcAttributeRequestMethod.
Tests updated to ensure that mapping accounts for all properties and translates string union back to OidcAttributeRequestMethod under the hood.
=> fix: Flatten OIDC props to eliminate importing OidcAttributeRequestMethod

.changeset/five-fireants-shout.md, .changeset/khaki-panthers-grin.md, package-lock.json, packages/auth-construct/package.json, packages/backend-auth/package.json, packages/backend-data/package.json, packages/backend-deployer/package.json, packages/backend-function/package.json, packages/backend-output-storage/package.json, packages/backend-platform-test-stubs/package.json, packages/backend-storage/API.md, packages/backend-storage/package.json, packages/backend-storage/src/construct.ts, packages/backend-storage/src/factory.ts, packages/backend-storage/src/function_instance_provider.ts, packages/backend/package.json, packages/backend/src/index.ts, packages/integration-tests/package.json, packages/integration-tests/src/test-in-memory/integration_tests.test.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/function.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/storage/resource.ts, packages/plugin-types/package.json, packages/sandbox/package.json, scripts/components/test-resources/dependency-linked-version-consistency-test-packages/package2/package.json, templates/construct/package.json
add ability to add trigger for storage events
=> Add trigger handler for storage events

.changeset/loud-sheep-occur.md, .eslint_dictionary.json, packages/backend-storage/src/construct.test.ts, packages/backend-storage/src/construct.ts
Accessing files in S3 from the browser requires CORS rules on the bucket
fixes https://github.com/aws-amplify/amplify-backend/issues/992
Add CORS rules to the S3 Bucket configuration in defineStorage. These rules are copied from the Gen1 CORS rules.
Manually tested and added a unit test
=> Enable CORS on S3 Bucket

.changeset/cyan-steaks-repeat.md, packages/backend-data/src/factory.test.ts, packages/backend-data/src/factory.ts, packages/backend-data/src/index.ts, packages/backend-data/src/types.ts, packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts, packages/integration-tests/src/test-in-memory/data_without_auth.test.ts, packages/integration-tests/src/test-in-memory/data_without_auth_no_auth_mode.test.ts
Enforce call count limit on defineData to prevent customer from accidentally creating multiple DataFactory. When we detect customer calling defineData multiple times, we should throw descriptive error with resolution steps.
Split up memory-in-test integration tests into separate files. The test suite was bootstrapping multiple projects with specific configurations. This was throwing because all projects had some data resource defined. With this change that limits defineData call, the the test suite had to be split up.
=> feat: limit calling defineData multiple times

.changeset/khaki-pants-sniff.md, package-lock.json, packages/backend-storage/API.md, packages/backend-storage/src/access_builder.test.ts, packages/backend-storage/src/access_builder.ts, packages/backend-storage/src/storage_container_entry_generator.test.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/storage/resource.ts
Per product team recommendation, using var args for the actions doesn't make it obvious that multiple actions can be specified. Using an array explicitly makes this behavior obvious
Update the method signature of the `allow.<user>.to('action')` helper to `allow.<user>.to(['action'])` to make it clear that multiple actions can be specified
Existing tests updated to match new shape.
=> Use array instead of var args for defining resource access actions

.changeset/little-books-press.md, packages/cli-core/src/package-manager-controller/npm_package_manager_controller.test.ts, packages/cli-core/src/package-manager-controller/package_manager_controller_base.ts, packages/cli-core/src/package-manager-controller/pnpm_package_manager_controller.test.ts, packages/cli-core/src/package-manager-controller/yarn_classic_package_manager_controller.test.ts, packages/cli-core/src/package-manager-controller/yarn_modern_package_manager_controller.test.ts, packages/integration-tests/src/test-e2e/create_amplify.test.ts
E2E tests are failing when adding `--paths` option to `tsc` with error:
```
error TS6064: Option 'paths' can only be specified in 'tsconfig.json' file or set to 'null' on command line.npm ERR! code 1
```
Update to add `paths` by reading tsconfig file after `tsc` and overriding file with `paths` added.
=> fix how paths is added to tsconfig

.changeset/modern-files-arrive.md, packages/client-config/API.md, packages/client-config/src/client-config-types/analytics_client_config.ts, packages/client-config/src/client-config-writer/client_config_converter.test.ts, packages/client-config/src/client-config-writer/client_config_converter.ts
JS V6 config expects the analytics configuration to be passed differently. See J[S Parsing](https://github.com/aws-amplify/amplify-js/blob/9c916d1337b99751d9c286bace5873ae62936828/packages/core/src/parseAWSExports.ts#L61-L62) and [a test ](https://github.com/aws-amplify/amplify-js/blob/468f979ad07f66816fa44cd0f8e86cf27f5ffd60/packages/core/__tests__/parseAWSExports.test.ts#L173-L174)
Moreover, the [converted config](https://github.com/aws-amplify/amplify-js/blob/9c916d1337b99751d9c286bace5873ae62936828/packages/core/src/parseAWSExports.ts#L80) in JS has the key name as `Pinpoint` instead of `AWSPinpoint`for manually configuring it. 
**Issue number, if available:** fixes #1061
Changing the name of the keys
_By submitting this pull request, I confirm that my contribution is made under the …
=> fix(client-config): add legacy analytics configuration keys

.github/workflows/health_checks.yml
Currently we have to manually verify that e2e tests on main are passing before merging version bump PRs
Move the release step in the merge workflow to the end so that the release only happen once all tests are passing on the version commit. New workflow looks like
=> update publish job to depend on e2e and unit test jobs

.changeset/modern-terms-stare.md, packages/backend-function/src/function_env_type_generator.test.ts, packages/backend-function/src/function_env_type_generator.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/.amplify/function-env/defaultNodeFunction.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/func-src/response_generator.ts
E2E tests are not using the typed shim for resource env vars.
Majority of the work was already done as part of #1076.
- Update E2E tests to use typed `process.env` shim for resource access env vars
- Update typed shim file
- Move comment about Lambda runtime env vars to where it should be
- Add comment to explain what the `AmplifyBackendEnvVars` type is
E2E test checks
=> ensure resource access env vars are added to typed shim files

.changeset/short-olives-bow.md, packages/backend-storage/API.md, packages/backend-storage/src/private_types.ts, packages/backend-storage/src/storage_access_orchestrator.test.ts, packages/backend-storage/src/storage_access_orchestrator.ts, packages/backend-storage/src/storage_access_policy_factory.test.ts, packages/backend-storage/src/storage_access_policy_factory.ts, packages/backend-storage/src/types.ts
The "read" action currently only grants "GetObject" access. Read should also include the ability to list objects (within the specific prefix).
Add the ListBucket action to the behavior of the "read" action. Additionally, two new actions, "get" and "list" are added so that behavior can be scoped to only get or list if desired. "read" is a convenience action that includes both "get" and "list".
Updated unit tests and manually validated the generated policies
=> Add "list" action to storage resource access

.github/actions/restore_build_cache/action.yml, .github/workflows/health_checks.yml
Earlier when the github actions for this repository were implemented, the standard github runners were using 2 core CPUs. Now that github has upgraded those servers to 4, see if we can achieve similar performance with them.
Change amplify specific action runners to github hosted ones.
e2e
=> chore: Try moving to 4 core CPUs for github workflows

.changeset/brave-shirts-push.md, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts
It is very easy to hit memory limits and have a heavy performance hit as memory is swapped in and out of the disk.
For example, a lambda in my test project with the following handler code uses around 89MB:
```ts
export const handler = async () => {
return 'it works!'
}
```
Function log:
```
START RequestId: 6045161b-ea8f-43d1-947b-e3d9afd962f9 Version: $LATEST
END RequestId: 6045161b-ea8f-43d1-947b-e3d9afd962f9
REPORT RequestId: 6045161b-ea8f-43d1-947b-e3d9afd962f9	Duration: 24.52 ms	Billed Duration: 25 ms	Memory Size: 128 MB	Max Memory Used: 89 MB
```
Set default function memory to 512MB from 128MB. Function memory can still be set between 128MB - 10240MB, no change there. …
=> set default function memory to 512

.changeset/spicy-bulldogs-itch.md, package-lock.json, packages/backend-auth/API.md, packages/backend-auth/src/factory.ts, packages/backend-storage/API.md, packages/backend-storage/src/access_builder.test.ts, packages/backend-storage/src/access_builder.ts, packages/backend-storage/src/constants.ts, packages/backend-storage/src/storage_access_orchestrator.test.ts, packages/backend-storage/src/storage_access_orchestrator.ts, packages/backend-storage/src/types.ts, packages/backend-storage/src/validate_storage_access_paths.test.ts, packages/backend-storage/src/validate_storage_access_paths.ts, packages/plugin-types/API.md, packages/plugin-types/src/resource_access_acceptor.ts
1. Currently there is no way to define user pool group access to storage (without using overrides).
2. Also, the current syntax for specifying owner-based auth rules is not extensible to additional identification mechanisms we want to support in the future.
1. Add a new `allow.group('groupName')` syntax to the existing storage access builder for specifying group access
2. Change `allow.owner.to(['action'])` to `allow.id('identity').to(['action'])`. This allows us to support different "id types" in the future. Currently "identity" is the only option which maps to the Cognito IdP IdentityId. This name was chosen instead of "owner" because it is not actually the user sub from the Cognito UserPool which is the actual "owner" in the system.
**Corresponding docs …
=> Enable user pool group access to storage and modify owner access syntax

.github/actions/install_with_cache/action.yml, .github/actions/restore_build_cache/action.yml, .github/workflows/health_checks.yml
Continuation of https://github.com/aws-amplify/amplify-backend/pull/1103 to change windows runners
=> chore: use 4 core windows runner for github actions

.changeset/famous-glasses-know.md, packages/backend-data/API.md, packages/backend-data/src/convert_authorization_modes.test.ts, packages/backend-data/src/convert_authorization_modes.ts, packages/backend-data/src/types.ts, packages/backend-data/src/validate_authorization_modes.test.ts, packages/backend-data/src/validate_authorization_modes.ts
This change removes `allowListedRoleNames` from `defineData`.
This field is getting deprecated at data construct and will be replaced with alternative IAM access mechanism.
1. Remove `allowListedRoleNames`
2. Amend rest of the codebase.
Tests
=> remove allowListedRoleNames from defineData

.changeset/modern-moons-fail.md, packages/cli/src/commands/sandbox/sandbox_command.ts
The description for `amplify sandbox --dir-to-watch` was not updated to match the new behavior of watching the amplify directory.
Change description from
`Directory to watch for file changes. All subdirectories and files will be included. defaults to the current directory.`
to
`Directory to watch for file changes. All subdirectories and files will be included. Defaults to the amplify directory.`
https://github.com/aws-amplify/docs/pull/7031
=> Update text to match sandbox default behavior

.changeset/afraid-flies-repair.md, packages/backend/API.md, packages/backend/api-extractor.json, packages/backend/package.json, packages/backend/src/index.internal.ts, packages/backend/src/types/platform.ts, packages/integration-tests/src/test-in-memory/backend_submodule_type_exports.test.ts
When building additional abstractions around `defineBackend` or other `define*` functions, you often need access to the input our output types from these functions and the objects they return. These types come from `@aws-amplify/plugin-types`, but declaring a direct dependency on that package can lead to version conflicts and incompatible types.
fixes https://github.com/aws-amplify/amplify-backend/issues/340
Re-export a subset of the types in `@aws-amplify/plugin-types` from `@aws-amplify/backend`. The submodule import is `@aws-amplify/backend/types/platform`
Added a build-time check in the integration-tests package to make sure that the expected submodule exports are available from the backend package
_By …
=> expose subset of plugin-types from backend submodule export

.changeset/four-peaches-pull.md, package-lock.json, packages/backend-data/package.json, packages/backend-data/src/factory.ts, packages/backend/package.json, packages/integration-tests/package.json, packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/data/echo/handler2.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/data/resource.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/hotswap-update-files/data/resource.ts
Allows inline `defineFunction` in the schema builder without additional configuration in `defineData`
Complement to this data-schema PR: https://github.com/aws-amplify/amplify-api-next/pull/124
Docs PR: https://github.com/aws-amplify/docs/pull/6836/files#diff-dfe0a992e880882948237e578edffdfb4a4548f19487a58118ff900d2c7c233aR146-R161
fixes: https://github.com/aws-amplify/amplify-backend/issues/573
Enables the following DX:
```ts
import {
type ClientSchema,
a,
defineData,
defineFunction,
} from '@aws-amplify/backend';
const fn1 = defineFunction({entry: './echo/handler.ts',});
const fn2 = defineFunction({entry: './echo/handler2.ts',});
const s = a.schema({
getPostDetails: a
.query()
.arguments({ postId: a.string() })
.handler([
a.handler.function(fn1), …
```
=> backend-data: add support for first-class defineFunction

.changeset/serious-maps-wait.md, packages/backend-auth/src/userpool_access_policy_factory.ts, packages/backend-data/src/factory.ts, packages/backend-deployer/src/cdk_deployer.ts, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/cli-core/src/package-manager-controller/package_manager_controller_factory.ts, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.test.ts, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts, packages/platform-core/src/errors/amplify_user_error.ts, packages/platform-core/src/usage-data/usage_data_emitter.test.ts, packages/sandbox/src/file_watching_sandbox.test.ts
Setting a resolution for customer errors is not enforced by the type system and relies on engineer best-effort.
Fixes: https://github.com/aws-amplify/amplify-backend/issues/873
Make the resolution field required in the ctor for `AmplifyUserError` and add a resolution in places where it is now required.
Build passes, updated existing unit tests.
=> enforce "resolution" in `AmplifyUserError` ctor

.eslint_dictionary.json, scripts/components/api-changes-validator/api_usage_generator.test.ts, scripts/components/api-changes-validator/api_usage_generator.ts, scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/package.json, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/index.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/tsconfig.json, scripts/components/api-changes-validator/types.ts
API check generates incorrect usage statements for types declared in API extract like this:
```ts
export type SomeTypeUnderNamespace = {
someProperty: string;
}
declare namespace someNamespace {
export {
SomeTypeUnderNamespace
}
}
```
I.e.
```
Validation of backend completed successfully
/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:[87](https://github.com/aws-amplify/amplify-backend/actions/runs/8349176781/job/22852847929#step:7:88)
throw new AggregateError(
^
at <anonymous> (/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:87:9)
at …
```
=> build: handle namespaced types in api check

.changeset/soft-radios-hug.md, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.test.ts, packages/client-config/src/client-config-writer/client_config_formatter_legacy.test.ts, packages/client-config/src/client-config-writer/client_config_to_legacy_converter.test.ts, packages/client-config/src/client-config-writer/client_config_to_legacy_converter.ts
aws_project_region was not being populated in the client config.
**Issue number, if available:** https://github.com/aws-amplify/amplify-backend/issues/1170
Populate if from one of the constructs.
Unit tested and manually tested.
=> fix: populate top level region in the client config

.changeset/poor-items-swim.md, packages/cli/src/info/cdk_info_provider.ts
notices may not be ideal when using info command
example of notices when using cdk version 2.132.0
```
NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)
29420(cli): List stack output change issue.
Overview: v2.132.0 introduced functionality to the cdk list command to
display stack dependencies. This feature introduced a change
that displays stack ids over displayName altering the
existing list functionality
Affected versions: cli: 2.132.0
More information at: https://github.com/aws/aws-cdk/issues/29420
29483(cli): Upgrading to v2.132.0 or v2.132.1 breaks cdk diff functionality
Overview: cdk diff functionality used to rely on assuming lookup-role.
With a recent change present in v2.132.0 and v2.132.1, it is
now trying to assume deploy-role with the lookup-role. …
```
=> adds no-notice to info command

.changeset/smart-gifts-teach.md, package-lock.json, packages/backend-function/src/factory.ts, packages/integration-tests/package.json, packages/integration-tests/src/test-project-setup/data_storage_auth_with_triggers.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/func-src/response_generator.ts
If a function handler code uses a 3p dependency that requires `.node` files it fails to bundle because there is no loader configured for `.node` files.
fixes #1153 
- Add `loader` option to load `.node` files as `file`
- Add 3p dependency that requires `.node` files for E2E tests
E2E tests and verified locally.
=> add support for function dependencies that require .node files

.changeset/dry-yaks-kiss.md, packages/cli/src/commands/sandbox/option_types.ts, packages/cli/src/commands/sandbox/sandbox-delete/sandbox_delete_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_list_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_list_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts, packages/cli/src/commands/sandbox/sandbox_command.ts, packages/cli/src/commands/sandbox/sandbox_command_factory.ts, packages/cli/src/commands/sandbox/sandbox_id_resolver.test.ts, packages/cli/src/commands/sandbox/sandbox_id_resolver.ts
Sandbox secret commands do not recognize the `--name` argument. This means that there is no way to manage secrets for named sandboxes from the CLI
fixes: https://github.com/aws-amplify/amplify-backend/issues/1125
Modified the `--name` arg to be global to all sandbox commands and make necessary plumbing refactors to use the name arg in the `sandbox secret` commands. I also included some type refactoring that wasn't strictly required, but makes the types across the arg objects more consistent
https://github.com/aws-amplify/docs/pull/7108
=> Named sandbox secrets

.changeset/small-donkeys-yawn.md, .eslint_dictionary.json, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
`Error` object in javascript cannot be serialized using `JSON.serialize()`. Often times a `Error` from a downstream library is wrapped inside the `AmplifyError` while keeping the `Error` in the `cause` of `AmplifyError`. However due to serialization issues, the `Error` object was not being reconstructed from the `stderr`.
This change manually serializes and deserialize the `Error` object.
Another unrelated change here is to ensure single quotes are handled correctly in the error serialization.
=> chore: handle generic error serialization correctly

.changeset/silly-pots-know.md, package-lock.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/sandbox/package.json, packages/sandbox/src/sandbox_executor.test.ts, packages/sandbox/src/sandbox_executor.ts
Extract more types of user errors from CDK log and map/classify them as `AmplifyErrors` to give less clutter in the sandbox log.
unit tests
=> chore: add more cdk errors in the error mapper

.changeset/kind-lemons-compare.md, packages/cli/src/commands/configure/configure_profile_command.ts, packages/cli/src/commands/generate/config/generate_config_command.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts
There are inconsistencies on how we handle yargs arg object in handler methods, some args are kebab-case and others are camelCase.
Fixes #1203 
Update all handler methods to handle args in handler methods as camelCase to keep things consistent.
=> cleanup instances where we use kebab case in yargs handler methods

.changeset/modern-balloons-wave.md, package-lock.json, packages/cli-core/src/package-manager-controller/package_manager_controller_factory.ts
Directs users to use `npx amplify` if the CLI errors when not being run with a package manager.
=> Improved error message for package manager

.changeset/nasty-snails-speak.md, package-lock.json, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.test.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts, packages/schema-generator/API.md, packages/schema-generator/package.json, packages/schema-generator/src/generate_schema.test.ts, packages/schema-generator/src/generate_schema.ts
Adds the amplify secret name to the generated typescript data schema file.
- The core functionality exists in the API repo `@aws-amplify/graphql-schema-generator` package. Gen2 CLI is responsible for passing the amplify secret name option from the below command to the library.
```sh
npx amplify generate schema-from-database --connection-uri-secret CONN_STRING_SECRET --out schema.rds.ts
```
The underlying library uses the secret name in the generated file as shown in the below link. This file is later used to deploy the backend.
https://github.com/aws-amplify/amplify-category-api/blob/2c8ee6b16c1bb2b5dececa70354d7f4fff616497/packages/amplify-graphql-schema-generator/src/__tests__/__snapshots__/generate-ts-data-schema.test.ts.snap#L115
The PR also upgrades the …
=> add amplify secret name to the generated typescript data schema file

.github/workflows/canary_checks.yml
After adding retry canaries may cross 15 minutes threshold.
The usual run time for canaries is around 7-8 minutes. If there's retry it may cross 15 minutes.
Therefore bumping threshold to 20 minutes.
=> Increase canary timeout

.changeset/popular-stingrays-talk.md, packages/backend-auth/API.md, packages/backend-auth/src/types.ts, packages/backend-auth/src/userpool_access_policy_factory.ts
Currently we are unable to define group-related access beyond managing user membership. 
Creating policy documents and managing (or avoiding) circular dependencies is painful.
This change adds manageGroups as a meta action.
=> feat: add manageGroups as an IAM action

.changeset/beige-dragons-boil.md, package-lock.json, packages/cli/src/commands/generate/config/generate_config_command.ts, packages/client-config/API.md, packages/client-config/src/client-config-types/client_config.ts, packages/create-amplify/src/gitignore_initializer.test.ts, packages/create-amplify/src/gitignore_initializer.ts, packages/integration-tests/src/test-e2e/create_amplify.test.ts
Current `amplify-outputs.json` doesn't work with android as the character `-` is not allowed in the resource names
1. This PR changes the name of the file to `amplify_outputs` for all platforms.
2. Add this file to the gitignore as well.
=> chore: rename the new client config file name

.changeset/silent-rules-obey.md, packages/create-amplify/src/gitignore_initializer.test.ts, packages/create-amplify/src/gitignore_initializer.ts, packages/integration-tests/src/test-e2e/create_amplify.test.ts
fix: order of array in test assert in gitignored tests
=> fix: order of array in test assert in gitignored tests

.changeset/three-kings-sin.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
chore: Translate secrets not set error to a more user friendly error message
The existing error message is too verbose and could be confusing. Since it's quite a common pitfall to use the secrets before setting them, this error perhaps help customers know exactly how to fix.
As part of this PR, I also made contextual data extracted from the `stderr` to be also used in the human readable error messages if they have a placeholder.
Unit tests
=> chore: Translate secrets not set error to a more user friendly error message

.changeset/warm-spoons-approve.md, packages/backend-data/src/factory.test.ts, packages/backend-data/src/factory.ts
The `apiName` isn't handled correctly in some cases and can lead to `undefined` being used as the value.
fixes https://github.com/aws-amplify/amplify-backend/issues/1272
Resolves the `apiName` consistently and updates all instances of `this.props.name`
Updated unit tests
=> Bug: API name is undefined in some cases

.changeset/light-papayas-count.md, packages/cli/src/main_parser_factory.test.ts, packages/cli/src/main_parser_factory.ts
Currently amplify backend cli will accept any arbitrary arguments whether they are supported or not.
Made the main parser factor only accept strict command inputs.
Uni tests
=> chore: make all cli commands strict

.changeset/tiny-experts-hammer.md, packages/backend-auth/src/factory.test.ts, packages/backend-data/src/convert_authorization_modes.test.ts, packages/backend-data/src/convert_functions.test.ts, packages/backend-data/src/factory.test.ts, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts, packages/backend-storage/src/storage_container_entry_generator.test.ts, packages/plugin-types/API.md, packages/plugin-types/src/function_resources.ts
Functions are missing `cfnResources` for L1 constructs.
Fixes #1248 
Add `resources.cfnResources` for functions.
Docs PR will be created soon
Unit tests and manually (also tested overriding memory):
`backend.ts`:
CloudFormation template for function stack:
=> add cfnResources to function resource

.changeset/angry-bugs-buy.md, packages/backend-auth/src/factory.ts, packages/backend-data/src/factory.ts, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/backend-function/src/factory.ts, packages/platform-core/src/backend_entry_point_locator.ts, packages/platform-core/src/package_json_reader.ts, packages/platform-core/src/parameter_path_conversions.ts
1. More instances updated where `AmplifyUserError` should be thrown.
2. Based on the telemetry, all errors thrown by CDK constructs (L2 or L3) were customer errors. Starting with categorizing all as customer errors until we have a better way to distinguishing between customer and library faults.
unit tests
=> chore: convert errors to AmplifyUserError

.changeset/proud-balloons-grab.md, package-lock.json, packages/backend-data/package.json, packages/backend/package.json, packages/integration-tests/package.json
N/A
- Bumps data-construct to current version: 1.8.0-0411-gen2.0
- Bumps data-schema to current version: 0.15.0
- Bumps data-schema-types to current version: 0.8.0
These new versions contain breaking changes for relationship definitions.
=> chore!: bump data-construct, data-schema, and data-schema-types dependency

.github/workflows/deprecate_release.yml, .github/workflows/restore_release.yml, scripts/restore_release.ts
When testing these workflows before merging, there was no way to kick off the workflow using the GH UI so I was manually setting these env vars in the branch push workflow. I thought they would be set automatically by the workflow inputs, but they are not.
Wire the workflow inputs to corresponding environment variables so they are picked up by the @actions/core toolkit `getInput()` function.
Now that the workflow exists on `main`, the workflow dispatch UI can be used to trigger the workflow: 
Successful dryrun `restore_release` workflow: https://github.com/aws-amplify/amplify-backend/actions/runs/8710549954/job/23892707554
Successful dryrun `deprecate_release` workflow: …
=> Fix workflow input wiring for `deprecate_release` and `restore_release` workflows

.changeset/weak-bottles-camp.md, package-lock.json, packages/form-generator/package.json, packages/model-generator/package.json
`@aws-amplify/backend@0.13.0-beta.17` depends on updated `data-schema` and `data-schema-types` packages that change how relationships are defined and their implementation details.
The model introspection schema is currently generated for the new outdated relationship paradigm, resulting in client side errors when querying related models in relationships.
Bumps the following packages involved in model introspection schema generation:
- @aws-amplify/appsync-modelgen-plugin: 2.11.0-gen2-release-0411.0
- @aws-amplify/graphql-generator: 0.4.0-gen2-release-0411.0
- @aws-amplify/graphql-types-generator: 3.6.0-gen2-release-0411.0
Manually tested relational queries with updated packages.
_By submitting this pull request, I …
=> fix: bump model introspection schema generation packages for references relationships

.changeset/yellow-peas-wonder.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
If the downstream exception/cause was not a generic Error (such as ones thrown by data construct), we were correctly handling their serialization and deserialization.
Preserve the `name` of the underlying error and relax the restriction that it has to have the name `Error`
Unit tests
=> fix: serialize downstream errors when they are not generic Errors

.changeset/strong-cooks-call.md, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.test.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.ts
When running `npx amplify generate *` commands while the stack is in a `*_IN_PROGRESS` status, there may not be metadata/outputs available yet so users get an error like `Error: Output userPoolId not found in stack`.
Update when to check if the stack is in a status that ends with `_IN_PROGRESS` and throw a helpful error message.
Unit tests and manually while sandbox is updating the stack:
-----------
-----------
=> throw for generate commands while deployment is still in progress

.changeset/three-lamps-impress.md, package-lock.json, packages/backend-data/package.json, packages/schema-generator/package.json
https://github.com/aws-amplify/amplify-backend/security/dependabot/31
Bumped data construct and schema generator to the tag version released on 4/16 to resolve dependent bot alert issue
=> chore: bump data construct and schema generator

.changeset/hot-tigers-impress.md, .changeset/thin-timers-double.md, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.ts, packages/integration-tests/src/process-controller/predicated_action_macros.ts, packages/integration-tests/src/test-e2e/deployment.test.ts, packages/sandbox/API.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts, packages/sandbox/src/sandbox.ts
Support sandbox deployment without running watcher using `--once` flag
```npx amplify sandbox --once```
https://github.com/aws-amplify/amplify-backend/issues/1062
=> feat: support sandbox deployment without watcher with --once flag

.changeset/nice-cooks-laugh.md, .changeset/tough-shirts-repeat.md, packages/backend-storage/src/factory.test.ts, packages/backend-storage/src/factory.ts, packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts
Removing the name restriction on `defineStorage` for consistency with other resources like function, auth, data.
Removing name check on getInstance for storage.
=> fix: remove name validation on defineStorage

.changeset/spotty-llamas-jump.md
removes changeset introduced with https://github.com/aws-amplify/amplify-backend/pull/1327
Since this revert was never part of a release it shouldn't appear in the changelog
=> remove changeset

.changeset/strange-trainers-invite.md, packages/backend-storage/API.md, packages/backend-storage/src/access_builder.test.ts, packages/backend-storage/src/access_builder.ts, packages/backend-storage/src/private_types.ts, packages/backend-storage/src/storage_access_orchestrator.test.ts, packages/backend-storage/src/storage_access_orchestrator.ts, packages/backend-storage/src/types.ts
When defining storage access for user pool groups, many times multiple groups should have the same access permissions. Our current interface requires specifying separate but duplicate actions for each of these groups.
Additionally, our current access allows the same group (or other entity) to be specified multiple times within the access definition for a single path. This makes it ambiguous how those rules will be combined together.
To solve the first problem, we are changing `allow.group(name).to([action])` to `allow.groups([name]).to([action])` so that multiple groups can be specified together.
Instead of
```ts
defineStorage({
access: allow => ({
'foo/*': [
allow.group('managers').to(['read']),
allow.group('auditors').to(['read']),
]
})
})
```
This can …
=> Allow specifying multiple groups in one group access rule

.changeset/tiny-drinks-melt.md, packages/backend/API.md, packages/backend/src/backend.ts
The `getResourceAccessAcceptor` method that is used internally for wiring resource access is exposed on the `defineBackend` type. While this method is part of our package interface, we don't intend for customers to use it directly in normal circumstances.
Hides the `getResourceAccessAcceptor` method on backend resources.
Before:
After:
Note that it is still possible to find this method if you inspect the return value of `defineFunction` or `defineAuth` directly. We can't hide this type as it is required for proper type inferences when passing references of these objects in the backend definition.
Manually validated that editor tooltips are working as expected and all existing test cases build
_By submitting this …
=> Sanitize backend type inference

.changeset/nine-oranges-eat.md
https://github.com/aws-amplify/amplify-backend/pull/1288 should have updated plugin-types changeset but overlooked it. This PR creates the missing changeset.
=> chore: update plugin-types changeset

.changeset/neat-hotels-thank.md, packages/backend-storage/API.md, packages/backend-storage/src/construct.test.ts, packages/backend-storage/src/construct.ts
In order to provide a better DX and maintain consistency with other categories, we want to provide access to the L1 bucket to the customer. This way they have access to the S3 resource and can further customize the bucket using CDK.
Fixes #1249 
Add `cfnResources` to storage resource to provide access to L1 `cfnBucket`.
TODO
Unit tests and locally:
=> add cfnBucket to storage resource

.changeset/lovely-pugs-know.md, package-lock.json, packages/client-config/API.md, packages/client-config/src/client-config-contributor/client_config_contributor_v1.test.ts, packages/client-config/src/client-config-contributor/client_config_contributor_v1.ts, packages/client-config/src/client-config-schema/client_config_v1.ts, packages/client-config/src/client-config-schema/schema_v1.json, packages/client-config/src/client-config-types/notifications_client_config.ts, packages/client-config/src/client-config-writer/client_config_to_legacy_converter.test.ts, packages/client-config/src/client-config-writer/client_config_to_legacy_converter.ts, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.test.ts, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.ts
1. Revert splitting `oauth.domain` to `oauth.cognito_domain` and `oauth.custom_domain`. Custom domain config will be configured in the customs section until we have first class support.
2. Remove `authentication_flow_type`
3. Fix the notifications config. APNS and FCM maps to `Push` config key in all libraries, including [javascript](https://github.com/aws-amplify/amplify-cli/blob/1da5de70c57b15a76f02c92364af4889d1585229/packages/amplify-frontend-javascript/lib/frontend-config-creator.js#L587-L588)
=> chore: minor client config updates

.changeset/yellow-toes-smile.md, package-lock.json, packages/cli/package.json
Adds `backend` as a valid command name for executing the Gen 2 CLI.
Intentionally not updating any of the other references to the `amplify` command in the codebase at this time.
=> add `backend` command name

.changeset/clean-kiwis-cross.md, package-lock.json, packages/backend-data/package.json, packages/backend-data/src/convert_schema.test.ts, packages/backend-data/src/convert_schema.ts
The customers of Amplify console can have their database connection string stored as a shared secret rather than as a branch specific one. We do not support this today which limits the console customers from using shared database connect secret.
With this PR, we utilize the updated API that we recently released in the data construct and pass both SSM paths to it. The data construct handles resolution of the secret path by searching in the order of the SSM paths in the list. In this PR, we set the branch specific path followed by shared path in the list that we pass to the data construct, since that is the recommended order.
_By submitting this pull request, I confirm that my contribution is made under the terms of …
=> fix: support connection URI as a shared secret in Amplify console

.changeset/angry-wasps-marry.md, package-lock.json, packages/cli/src/commands/generate/generate_command.ts, packages/cli/src/commands/generate/generate_command_factory.test.ts, packages/cli/src/commands/generate/generate_command_factory.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.test.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.ts, packages/integration-tests/src/test-e2e/deployment.test.ts
Now that we have new configuration file name `amplify_outputs.json`, rename the command name to reflect that as well.
`npx amplify generate config` --> `npx amplify generate outputs`
=> chore: change generate config command to generate outputs

.changeset/ninety-beds-tan.md, package-lock.json, packages/backend-data/package.json, packages/backend/package.json, packages/integration-tests/package.json, packages/integration-tests/src/test-projects/access-testing-project/amplify/data/resource.ts
* bumps `data-schema` and `data-schema-types` deps to latest
* build/tests
=> chore: bump data-schema deps to latest

.changeset/four-oranges-brake.md, package-lock.json, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.test.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.ts
Rename all the config generation options to have `outputs` instead of `config` in it.
=> chore: rename config generation options as outputs generation options

.changeset/six-deers-sin.md, packages/cli/src/error_handler.ts, packages/platform-core/src/usage-data/usage_data_emitter.ts
UsageDataEmitter needs credential to emit metrics and will throw. This is resulting in an infinite loop
Gracefully handle the emit failure.
=> fix: gracefully fail on usage data emit failure

.changeset/rotten-ducks-invent.md, .github/workflows/health_checks.yml, scripts/check_package_versions.ts
Major version bump for all public packages in the repo. Except for the `ampx` package which I am leaving at 0.x because it is not intended to be used and we aren't sure how it might evolve at this point.
=> major version bump to 1.x

.changeset/fuzzy-buses-marry.md, packages/cli/package.json
When executing commands using the package name, ie `npx @aws-amplify/backend-cli`, npx looks for the first bin entry in the package.json of the file. This means that it would execute the amplify bin and then fail
Reorder the bin entries in the package.json file so that `ampx` is the one that gets executed.
Manually verified
=> update bin order in cli package

.changeset/bright-clouds-drive.md, .github/actions/build_with_cache/action.yml, .github/actions/install_with_cache/action.yml, .github/actions/restore_build_cache/action.yml, .github/actions/restore_install_cache/action.yml, .github/actions/setup_node/action.yml, .github/workflows/health_checks.yml, packages/integration-tests/src/test-project-setup/access_testing_project.ts
We should be ensuring that our repo is able to install, build, and test using the specified node versions.
- Update `setup_node` action to take in `node-version` input
- Add node versions to test matrix in following jobs: `install`, `build`, `test_with_coverage`
- Add node versions to test matrix for `e2e_deployment`, `e2e_create_amplify`
- Skip `global.crypto` workaround for node > 20 as it is [no longer needed](https://github.com/nodejs/node/pull/42083).
=> feat: node compatibility test

.eslintignore
Running linter scripts fail for local test projects created by `npm run setup:test-project`
The local projects are not tracked or part of this repo. No need to run linter for external code.
Confirmed that linter ignored files under test-projects.
=> chore: lint ignore test-projects directory

.eslint_dictionary.json, .github/workflows/health_checks.yml, scripts/components/github_client.ts, scripts/components/is_version_packages_commit.ts, scripts/do_include_e2e.ts, scripts/is_version_packages_commit.ts
When releasing from the hotfix branch, we want to be able to get releases out as fast as possible without compromising safety checks. We are currently running e2e tests on all merges to the hotfix branch. This means that for a patch, e2e tests run at least twice: once when the patch is merged and a second time when the version packages PR is merged.
To shorten this time, we can update the workflow to only run e2e tests on hotfix version packages merges. This ensures that e2e is still run on any hotfix release payload but doesn't run automatically on the patch merge itself. E2E can still be triggered on the patch PR by applying the `run-e2e` label.
While making this change, I also refactored the run e2e check from bash to TS so that the bash conditional …
=> refactor run e2e check; when running on hotfix, only run on version package commits

.changeset/mighty-owls-impress.md, packages/backend-function/src/function_env_translator.test.ts, packages/backend-function/src/function_env_translator.ts
If an undefined value is passed as a function env var to `defineFunction`, the existing logic would try to treat it like a BackendSecret and error out.
fixes: https://github.com/aws-amplify/amplify-backend/issues/1460
Add defensive logic to check for undefined environment variable values and throw a clear error message.
Added a unit test
=> defensive logic for undefined function env vars

.changeset/twenty-poems-perform.md, packages/auth-construct/src/construct.ts
fixes https://github.com/aws-amplify/amplify-backend/issues/1506
Updating amplify_output.json to emit correct values for identity_providers.
```
AMAZON -> LOGIN_WITH_AMAZON
APPLE -> SIGN_IN_WITH_APPLE
```
=> fix: amplify_outputs for apple & amazon login method

.changeset/ninety-spiders-end.md, .eslint_dictionary.json, package-lock.json, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/string_maps.ts
**Issue number, if available:** fixes: #1472
two standard attributes were missing from the mapping.
Add the mapping and change the mapping from array to a map/record.
Updated unit tests and validated the `amplify_outputs.json`
=> fix: update user attributes mapping to have all the attributes

scripts/components/dependencies_validator.test.ts, scripts/components/dependencies_validator.ts, scripts/components/test-resources/inter-repo-dependency-version-consistency-test-packages/package1/package.json, scripts/components/test-resources/inter-repo-dependency-version-consistency-test-packages/package2/package.json, scripts/components/test-resources/inter-repo-dependency-version-consistency-test-packages/package3/package.json
With [this change](https://github.com/aws-amplify/amplify-backend/pull/1487), inter-repo dependencies are no longer all on the exact same semver range. This is okay, but caused our dependency_validator check to fail because it detected inconsistent version ranges. eg https://github.com/aws-amplify/amplify-backend/actions/runs/9083855361/job/24963522397?pr=1508#step:5:40
Relax the dependency_validator to only check that inter-repo dependencies are on a consistent major version rather than exact semver range. External dependencies are still validated to all be on the exact same semver range.
Added a unit test and manually verified.
_By submitting this pull request, I confirm that my contribution is made under the …
=> relax dependency semver range check for inter-repo dependencies

.changeset/afraid-cameras-walk.md, packages/backend-function/src/lambda-shims/resolve_ssm_params.ts, packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts, packages/integration-tests/src/test-project-setup/data_storage_auth_with_triggers.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/func-src/handler_with_ssm.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/function.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/test_factories.ts, packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/hotswap-update-files/function.ts
There are two problems:
1. Customers can't use SSM in lambdas, as described here https://github.com/aws-amplify/amplify-backend/issues/1520 .
2. AWS SSM client is loaded eagerly even if unused impacting cold start performance.
This PR attempts to solve these two problems by removing eager import from header.
I was looking at possibility of not rendering a banner conditionally at synthesis time but I hit a problem that SSM entries are processed lazily as well which demanded lazy rendering of banner.
Then it appeared that lazy rendering banner makes esbuild fail, as apparently esbuild runs before CDK tokens are resolved, see screenshot:
_By submitting this pull request, I confirm that my contribution is made under the …
=> lazy load ssm

.changeset/wise-dragons-marry.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts
**Issue number, if available:** fixes #1481 
Currently if `loginWith` has `phone` enabled, cdk [auto enables](https://github.com/aws/aws-cdk/blob/4b6dc8c650822bcd0231c8890bd94a934a0cd34d/packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts#L1160) `smsConfiguration` without which cognito would throw error `SMS configuration is required when phone_number is selected for auto verification`
but enabling `smsConfiguration` then requires MFA sms to be turned on, otherwise it fails with error `Can't turn off SMS_MFA when SMS configuration is set for the user pool`
This PR adds a fast fail with clear resolution step on how to recover from this error.
unit tests
_By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> chore: fast fail if loginWith phone is enabled but sms mfa is not

.changeset/olive-boxes-stare.md, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.test.ts, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.ts
We were using the wrong auth mode in the additional auth mode configuration. Reference [Gen1 implementation](https://github.com/aws-amplify/amplify-cli/blob/80a596498584d3f9bfeb0ffbde4a0d4256f971eb/packages/amplify-frontend-android/lib/frontend-config-creator.js#L373)
**Issue number, if available:** fixes: https://github.com/aws-amplify/amplify-backend/issues/1547
use correct auth mode in data config for legacy mobile client config
=> fix: use correct auth mode in data config for legacy mobile client config

.changeset/light-pets-behave.md, packages/backend-data/src/convert_js_resolvers.ts, packages/backend-function/src/factory.ts, packages/backend-storage/src/construct.ts, packages/backend/src/backend_factory.ts, packages/backend/src/engine/backend-secret/backend_secret_fetcher_provider_factory.ts, packages/backend/src/engine/branch-linker/branch_linker_construct.ts, packages/backend/src/engine/nested_stack_resolver.ts, packages/cli/src/commands/sandbox/sandbox_command_factory.ts, packages/client-config/src/write_client_config_to_file.ts, packages/integration-tests/src/cdk_version_finder.ts, packages/integration-tests/src/setup_test_directory.ts, packages/integration-tests/src/test-project-setup/cdk/test_cdk_project_creator.ts, packages/integration-tests/src/test-project-setup/data_storage_auth_with_triggers.ts, packages/platform-core/src/extract_file_path_from_stack_trace_line.ts, packages/platform-core/src/usage-data/get_usage_data_url.ts
disambiguate `url` imports and change to `import from 'node:url'` explicitly
=> chore: disambiguate url imports and import from node:url explicitly

.changeset/proud-clouds-cross.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts, packages/sandbox/src/sandbox_singleton_factory.ts
CDK can be bootstrapped in a region using custom stack name. I.e. other than `CDKToolkit`
https://github.com/aws-amplify/amplify-backend/issues/1510
This PR changes detection logic to use SSM parameter that contains version.
SSM access is already required for other functionalities to work.
=> use ssm parameter to detect CDK boostrap

scripts/publish_runner.ts
Fixes https://github.com/aws-amplify/amplify-backend/actions/runs/9354792810/job/25748559094
```
> amplify-backend@0.0.1 publish:snapshot
> tsx scripts/publish_snapshot.ts
🦋  error `changeset pre exit` can only be run when in pre mode
🦋  info If you're trying to enter pre mode, run `changeset pre enter`
file:///home/runner/work/amplify-backend/amplify-backend/node_modules/execa/lib/error.js:[6](https://github.com/aws-amplify/amplify-backend/actions/runs/9354792810/job/25748559094#step:6:7)0
error = new Error(message);
^
Error: Command failed with exit code 1: changeset pre exit
at makeError (file:///home/runner/work/amplify-backend/amplify-backend/node_modules/execa/lib/error.js:60:11)
at handlePromise (file:///home/runner/work/amplify-backend/amplify-backend/node_modules/execa/index.js:12 …
```
=> fix snapshot release

.changeset/tasty-cougars-visit.md, package-lock.json, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts
NA
Add support to pass secret value using redirections like `|` or `<`.
**Usage:**
```sh
$ pbpaste | npx ampx sandbox secret set SECRET_NAME
(or)
$ npx ampx sandbox secret set SECRET_NAME < SECRET.TXT
```
Docs will be updated as part of SQL custom SSL certificate support documentation.
- New unit tests
- Manual testing
=> add support to input secret value using redirection

.changeset/tiny-worms-confess.md, package-lock.json, packages/client-config/src/client-config-types/mobile/client_config_mobile_types.ts, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.test.ts, packages/client-config/src/client-config-writer/client_config_to_mobile_legacy_converter.ts
`socialProvider` and `AppClientId` are missing in the lagecy config when running `npx ampx generate outputs --format dart --out-dir lib --outputs-version 0` or `npx ampx sandbox --outputs-format dart --outputs-out-dir lib --outputs-version 0 `. 
This PR is to add `socialProvider` and `AppClientId` and modify the unit tests.
https://github.com/aws-amplify/amplify-backend/issues/1551
Added unit tests and tested on local app.
=> fix: add `socialProvider` and `AppClientId` to lagecy config

.changeset/cyan-dots-film.md, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.test.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts
Some args of `generate graphql-client-code` were hidden which made discovering these arguments difficult
fixes: https://github.com/aws-amplify/amplify-backend/issues/1546
Unhide all args on the `generate graphql-client-code` command
Updated unit tests
=> Show all args in output of `generate graphql-client-code --help`

.changeset/strange-moose-hide.md, package-lock.json, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.test.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts, packages/schema-generator/API.md, packages/schema-generator/package.json, packages/schema-generator/src/generate_schema.test.ts, packages/schema-generator/src/generate_schema.ts
Add support to pass a custom SSL certificate to connect to the SQL database for `generate schema-from-database` command.
NA
Adds new option `ssl-cert-secret` to the `generate schema-from-database` to specify the secret which contains the SSL certificate to be used to connect to the SQL database.
The new option is optional. If not provided, the command will use the default bundled certificate.
Docs update will be released later.
- New unit tests
- Manual testing
=> allow custom ssl certificate to generate schema-from-database command

.changeset/flat-toys-love.md, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.test.ts, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.ts
Fixes https://github.com/aws-amplify/amplify-backend/issues/964 .
1. Improves spacing
2. It changes wording from `configuration` to `outputs` to align with rest of the code.
The GH issue asked to include region in error message. However, that error message is coming from CFN service via SDK call and we don't have control over it. Region messaging should be handled differently.
=> fix error message formatting when amplify outputs cannot be generated

.changeset/chilly-onions-look.md, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts
**Issue number, if available:** fixes https://github.com/aws-amplify/amplify-backend/issues/1480
Better messaging to let users know that the secret command was successful.
=> chore: add success messaging when setting and removing sandbox secrets

.changeset/curvy-lamps-swim.md, packages/create-amplify/src/amplify_project_creator.test.ts, packages/create-amplify/src/amplify_project_creator.ts
There's "Gen 2" in telemetry message.
"Gen 2" is removed now.
1. Unit test amended.
2. Manually verified that changed http link works as expected.
=> Remove "Gen 2" wording from telemetry message

.changeset/selfish-pumpkins-sparkle.md, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
`pipeline-deploy` command can't render same outputs as `sandbox` command. This impacts DX of non-JS projects.
https://github.com/aws-amplify/amplify-backend/issues/1612
Introduce `--outputs-format` parameter for pipeline deploy command by pattern matching sandbox.
Unit test added.
=> add possibility to specify output format in pipeline-deploy command

.changeset/lazy-teachers-fold.md, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
Yargs validation errors are currently reported as unknown faults
wrap yargs validation errors in AmplifyUserError.
No UX change, the error is wrapped before sending to telemetry
Unit tests
=> wrap yargs validation errors in AmplifyUserError

.changeset/good-ghosts-reply.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts
Domain is not included in outputs when name is specified.
https://github.com/aws-amplify/amplify-backend/issues/1724
Include name in domain output generation logic.
Unit test added.
=> Fix a case where domain is not included in outputs if name property is specified

.changeset/healthy-crabs-breathe.md, packages/client-config/API.md, packages/client-config/src/client-config-contributor/client_config_contributor_v1.test.ts, packages/client-config/src/client-config-contributor/client_config_contributor_v1.ts, packages/client-config/src/client-config-schema/client_config_v1.ts, packages/client-config/src/client-config-schema/schema_v1.json, packages/client-config/src/client-config-writer/client_config_to_legacy_converter.test.ts, packages/client-config/src/unified_client_config_generator.test.ts
Upstream components expect defaults in password policies shape even if they have not been specified.
https://github.com/aws-amplify/amplify-backend/issues/1749
1. Make properties of password policy shape mandatory in schema.
2. Adjust code to render defaults if needed.
Unit tests added.
=> Fix a case where default password policy are not populated

.changeset/few-beans-tan.md, packages/sandbox/src/sandbox_executor.test.ts, packages/sandbox/src/sandbox_executor.ts
Currently token refresh errors are currently wrapped by SecretsErrors which then gets wrapped under `ListSecretsFault`
correctly classify credentials related errors while making sdk calls to SSM
=> correctly classify credentials related errors while making sdk calls to SSM

.changeset/ninety-dodos-try.md, package-lock.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
When customers have either deleted their tsconfig or rendered it useless for TSC to perform type-checks, the syntax and build errors are then caught at the CDK's ESBuild step which is then caught at `stderr`
catch and wrap the esbuild errors from cdk into AmplifyUserErrors
=> Catch and wrap esbuild error from cdk

.changeset/real-dragons-trade.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
Yargs error when a dependent argument is not provided by the customer was still missing from the error map.
add missing dependent arguments error in the yargs validations
=> chore: add missing dependent arguments error in the yargs validations

.changeset/mighty-donuts-check.md, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Current error mapping regexes were using hard coded line feeds `\n` which doesn't work on some OS.
Parameterize those regex to include os specific line feed.
1. Change explicit `\n` to `os.EOL`
2. Change implicit new line to `os.EOL`  and simple line concatenation in tests.
=> fix: error mapping regex for host specific newline characters

.changeset/cyan-crews-watch.md, packages/backend-deployer/src/cdk_deployer.ts
Seeing instances in the telemetry with empty error messages thrown from `CDKDeployer.executeCommand` which provides no information to debug
If there is no output generated by the child process, throw the process execution error instead.
=> throw child process error if no stderr generated during CDK cli execution

.changeset/long-chairs-march.md, package-lock.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
When cfn deployments are failed because of custom resource failures, cdk was printing a slightly different message. 
The error mapper has been updated to catch this type of deployment failure as well.
=> update cdk error mapper to catch all deployment errors

.changeset/poor-dodos-compare.md, packages/cli-core/src/package-manager-controller/pnpm_package_manager_controller.ts
Pnpm doesn't handle the node process gracefully with the SIGINT life cycle.
Avoid the prompt on SIGINT for pnpm.
Before:
After:
=> prevent ctrl+c handling for pnpm

scripts/components/api-changes-validator/api_changes_validator.test.ts, scripts/components/api-changes-validator/api_usage_generator.test.ts, scripts/components/api-changes-validator/api_usage_generator.ts, scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_sub_namespace.ts, scripts/components/api-changes-validator/types.ts
While working on feature branch I noticed that api check is not handling nested properties correctly.
See https://github.com/aws-amplify/amplify-backend/actions/runs/10325487544/job/28587278238?pr=1830 
```
at <anonymous> (/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:87:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[errors]: [
Error: Validation of @aws-amplify/ai-constructs failed, compiler output:
index.ts(4,10): error TS2305: Module '"@aws-amplify/ai-constructs"' has no exported member 'ConversationHandlerFunction'.
index.ts(5,10): error …
```
=> Handle nested namespaces in api check

.changeset/pink-bees-provide.md, packages/cli/src/commands/generate/forms/generate_forms_command.test.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/client-config/src/unified_client_config_generator.test.ts, packages/client-config/src/unified_client_config_generator.ts, packages/deployed-backend-client/API.md, packages/deployed-backend-client/src/backend_output_client_factory.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.test.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.ts, packages/model-generator/src/create_graphql_document_generator.test.ts, packages/model-generator/src/create_graphql_models_generator.test.ts, packages/model-generator/src/create_graphql_types_generator.test.ts, packages/model-generator/src/get_backend_output_with_error_handling.ts
Credential errors when running `ampx generate` commands should be wrapped in `AmplifyUserError`.
Wrap these errors in `AmplifyUserError` with more information on how to fix credentials.
Unit tests.
=> wrap credential related errors for generate in AmplifyUserError

.changeset/lucky-rabbits-decide.md, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_executor.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts, packages/ai-constructs/src/conversation/runtime/event-tools-provider/event_tools_provider.test.ts, packages/ai-constructs/src/conversation/runtime/types.ts, packages/integration-tests/src/test-project-setup/conversation_handler_project.ts
When lambda sends final response to AppSync it needs to specify a selection set.
That selection set is important to trigger propagation through subscriptions down the line, but for the lambda it's an opaque value that serves no other purpose than triggering desired behavior upstream.
In other words, lambda doesn't care what selection set is, upstream component does.
This PR changes event shape to require response selection set to be sent by upstream as opaque string.
Lambda doesn't use it, just makes sure it's in right place.
It is a single opaque string because lambda doesn't really care about the same being requested. This allows flexibility.
_By submitting this pull request, I confirm that my contribution is made …
=> Make conversation response selection set dynamic

.changeset/spicy-swans-enjoy.md, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts
Input for client tool is defined as AWSJSON in appsync. We have to serialize it before sending.
The reason for this strategy is that tool input can be arbitrary shape and can't be otherwise modeled in upstream appsync schema.
Serialize content if tool block is detected.
Added unit test.
=> Serialize tool us blocks

scripts/components/api-changes-validator/api_usage_generator.ts, scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/import_statements_renderer.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/package.json, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_other_entry_point.ts, scripts/components/api-changes-validator/types.ts, scripts/components/api-changes-validator/usage_statemets_renderer.ts
This PR solves two problems:
1. The existing solution to add namespace to symbols doesn't scale well. I.e. there's a need to cover every place a symbol is used in usage snippets.
2. API extractor does not support multiple entry point in package.json (exports section). We workaround this with `index.internal.ts` but this workaround needs more refinement to handle more advanced usage on `feature/conversation-handler` branch.
I.e.
1. Refactor namespacing solution to use match-replace after snippet generation. This is cheap and covers everything we need without complicating generators to process every possible type usage (which would otherwise require unpacking generics in every place, which is a lot of work).
2. Add special convention with `__export__` prefix in `index.internal.ts`. So that …
=> Handle namespaces better in api check

.changeset/modern-vans-fetch.md, packages/backend-ai/API.md, packages/backend-ai/src/index.internal.ts
Adjust `index.internal.ts` (workaround for API extractor) to leverage mechanism created in https://github.com/aws-amplify/amplify-backend/pull/1864 . I.e. to recognize extra exports defined in package.json while validating APIs exported from there.
This was validated manually, locally. Check will get green when main is merged to feature branch later after this PR goes in (so that baseline API.md) looks good.
=> Adjust API.md generation in backend-ai for api check to work.

.changeset/friendly-melons-hear.md, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
`SyntaxError`s that we throw during `ampx sandbox` [here](https://github.com/aws-amplify/amplify-backend/blob/main/packages/backend-deployer/src/cdk_deployer.ts#L210) and [here](https://github.com/aws-amplify/amplify-backend/blob/main/packages/backend-deployer/src/cdk_deployer.ts#L239) are being sent to our telemetry as `UnknownFaults`.
Make sure we wrap `SyntaxError`s in `AmplifyUserError`.
Unit tests.
=> wrap SyntaxErrors in AmplifyUserError

.changeset/kind-drinks-beg.md, packages/backend-function/src/function_env_translator.test.ts, packages/backend-function/src/function_env_translator.ts, packages/backend-storage/src/private_types.ts, packages/backend-storage/src/storage_access_orchestrator.ts
Two error names are missing `Error` suffix and are classified as unknown faults.
Add `Error` suffix.
=> Fix error names in storage and functions.

.changeset/plenty-years-clap.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
CDK can emit more variants of error for non bootstrapped accounts.
Expand error capturing pattern.
Added test.
=> Detect more non bootstrapped account variants

.changeset/shiny-beans-happen.md, package-lock.json, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
A generic error is thrown for running pipeline-deploy in local
Mark it as a user error
=> fix: classify error for running pipeline-deploy in local as user error

.changeset/lovely-eels-tap.md, packages/backend-deployer/API.md, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_deployer.ts, packages/backend-deployer/src/cdk_deployer_singleton_factory.ts, packages/cli/src/commands/sandbox/sandbox-delete/sandbox_delete_command.test.ts, packages/cli/src/commands/sandbox/sandbox-delete/sandbox_delete_command.ts, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.ts, packages/sandbox/API.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts, packages/sandbox/src/sandbox.ts, packages/sandbox/src/sandbox_executor.test.ts, packages/sandbox/src/sandbox_executor.ts
Passing profile via environment variables (see [here](https://github.com/aws-amplify/amplify-backend/blob/b2464ab051a1e4b8380fda8ebd911a610d64ac6e/packages/cli/src/command_middleware.ts#L35-L37)) is not enough to assure consistency.
Customer using `npx ampx sandbox --profile <profile_name>` might run into edge case scenarios where local or user home scoped cdk configuration might override environemnt.
See [code in CDK](https://github.com/aws/aws-cdk/blob/c7980a2e068b5336914364050f72e41259aebc90/packages/aws-cdk/lib/settings.ts#L134-L139). I.e. config is resolved in such a way that env variables have the least priority (implicitly).
Pass profile explicitly when calling CDK commands. So that it has the same priority as in ampx cli.
**Corresponding docs PR, if …
=> Pass profile explicitly to CDK CLI when using `npx ampx sandbox --profile <profile_name>`

.github/actions/select_e2e_account/action.yml, .github/workflows/canary_checks.yml, .github/workflows/health_checks.yml
Canary workflow doesn't use multiple e2e accounts yet.
Previous PR that introduced multiple accounts to health checks https://github.com/aws-amplify/amplify-backend/pull/1879 .
1. Create action to encapsulate account selection logic.
2. Use it canaries in addition to health checks.
1. This PR checks
2. Canary run https://github.com/aws-amplify/amplify-backend/actions/runs/10497624775
=> Use multiple accounts in canary workflow

.changeset/lazy-radios-do.md, packages/backend-secret/API.md, packages/backend-secret/src/secret.ts, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.test.ts, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts, packages/cli/src/commands/generate/generate_command_factory.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_command_factory.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_list_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_remove_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.test.ts, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/sandbox_executor.test.ts, packages/sandbox/src/sandbox_executor.ts, packages/sandbox/src/sandbox_singleton_factory.ts
Secrets client is used between a lambda to fetch secrets at runtime as well as by the cli commands for CRUD operations. The error handling for cli commands was either happening at the call site or none at all.
This PR introduces another wrapper over `SSMSecretClient` to perform error handling for amplify cli commands use case.
=> chore: refactor error handling for secrets client

.github/actions/run_with_e2e_account/action.yml, .github/workflows/canary_checks.yml, .github/workflows/health_checks.yml
We could spread health_checks traffic across regions we also use for canaries (since they're bootstrapped anyway).
This is a follow up on this https://github.com/aws-amplify/amplify-backend/pull/1902#issuecomment-2305168439 .
1. Refactor out a new action that can run a script with "e2e context". I.e. reduce duplication of constantly growing jobs that share same steps.
2. Add mechanism that can select region randomly if not provided.
1. In canaries region is provided explicitly, so we use that
2. In health checks a jobs pick region randomly.
1. Canary checks: https://github.com/aws-amplify/amplify-backend/actions/runs/10531663942
2. This PR checks.
I looked at jobs to see if canaries keep their stickyness and if health checks select random regions.
_By submitting this pull request, I …
=> Select random region in health check

scripts/components/api-changes-validator/api_usage_generator.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/index.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace_with_same_type.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/types.ts, scripts/components/api-changes-validator/types.ts, scripts/components/api-changes-validator/usage_statemets_renderer.ts
Sometimes the same symbol name appears under different namespaces.
When this happen API Extractor aliases the type with `_<number>` suffix to de-duplicate it and presents the type as exported with alias.
This became visible after https://github.com/aws-amplify/amplify-backend/pull/1917 got merged.
For example (see https://github.com/aws-amplify/amplify-backend/blob/main/packages/client-config/API.md).
```
// @public
type AmazonCognitoStandardAttributes = 'address' | 'birthdate' | 'email' | 'family_name' | 'gender' | 'given_name' | 'locale' | 'middle_name' | 'name' | 'nickname' | 'phone_number' | 'picture' | 'preferred_username' | 'profile' | 'sub' | 'updated_at' | 'website' | 'zoneinfo';
// @public
type AmazonCognitoStandardAttributes_2 = 'address' | 'birthdate' | 'email' | 'family_name' …
```
=> Handle aliased symbols in namespaces in api check

.changeset/tender-fishes-drive.md, package-lock.json, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/runtime/index.ts, packages/ai-constructs/src/conversation/runtime/types.ts, packages/backend-ai/API.md, packages/backend-ai/package.json, packages/backend-ai/src/conversation/factory.test.ts, packages/backend-ai/src/conversation/factory.ts, packages/backend-ai/src/conversation/runtime/index.ts, packages/backend-ai/src/index.internal.ts, packages/integration-tests/src/test-projects/conversation-handler/amplify/custom-conversation-handler/custom_handler.ts
Feedback from API review:
1. We should accept `a.ai.model.anthropic.claude3Haiku()` as input for model Id
2. We should re-export types from `backend-ai` that take part in custom conversation handler implementation.
1. Re-export types from `backend-ai`
2. Use these types in integration tests
3. Change inputs to `defineConversationHandlerFunction`.
This PR's checks
=> Api adjustments for conversation handler

scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_sub_namespace.ts, scripts/components/api-changes-validator/usage_statemets_renderer.ts
Usage of namespaced type in other type was not handled properly.
Add `;` as one of possible characters surrounding a symbol.
I.e. have `inputSchema: ToolInputSchema;` to be replaced by `inputSchema: conversation.runtime.ToolInputSchema;`
Finally green check in the PR.
=> Handle usage of namespaced types in api check

.changeset/sixty-pears-relate.md, package-lock.json, packages/ai-constructs/API.md, packages/ai-constructs/api-extractor.json, packages/ai-constructs/src/conversation/index.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts, packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_tool.ts, packages/ai-constructs/src/index.internal.ts
Exporting `runtime` via `<root_entry_point>` -> `conversation` -> `runtime` 
is causing module loader eagerly load bedrock sdk in IaC (CDK) context.
I.e. attempt to use just construct triggers it.
The runtime sub namespace is only needed for esbuild bundling of function and building custom handlers.
I.e.
```
"Error: Cannot find module '@aws-sdk/middleware-host-header'\r
Require stack:\r
- /private/var/folders/rd/hr92pbz54kx78lddndlp9jg40000gr/T/amplify-e2e-tests/generation-model_7149fdda9_20dc2c2f/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js\r
- /private/var/folders/rd/hr92pbz54kx78lddndlp9jg40000gr/T/amplify-e2e-tests/generation-model_7149fdda9_20dc2c2f/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-ampli …
```
=> Remove runtime from main exports in ai-constructs

.changeset/red-lamps-press.md, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts, packages/sandbox/src/file_watching_sandbox.ts
When part of the AWS credentials are incorrect we do not throw `InvalidSignatureException` as a user error.
An example of running into this scenario is partially copying the access key by double clicking to select (which selects the key up to a non alphanumeric character) which selects only part of the key when modifying the credential file directly.
Wrap `InvalidSignatureException` in AmplifyUserError.
I'll follow up in another PR for `SignatureDoesNotMatch` errors, which throws with the same message but is in different parts of the codebase.
Existing unit tests for `SSMCredentialsError`
=> wrap InvalidSignatureException in AmplifyUserError

.changeset/flat-hounds-speak.md, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_deployer.ts
fixes #1722
When customers are deploying their apps for the first time, i.e. `.amplify/generated/env` doesn’t yet exist, if an issue happens during the ESBuild step as part of cdk synth, the env files fail to get auto-generated. TypeScript check that run after then complain
```console
amplify/func-src/handler.ts(1,21): error TS2307: Cannot find module '$amplify/env/defaultNodeFunction' or its corresponding type declarations.
TypeScript validation check failed.
```
The root cause is a cyclic dependency issue between Synth process and TS checks.
Synth generates the .env files which are required to make TS happy. Without that TS will complain about the above error.
The coding errors that are caught by TS and ESBuild overlap by a lot. However, ESBuild is run by cdk in a child process and TS …
=> fix: surface synth errors if the function declaration files have not been written yet

.changeset/small-gorillas-remain.md, package-lock.json, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_command.ts, scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/expected-error-message.txt
Currently throwing generic Error which is translated to AmplifyFault
throw user error when sandbox identifier validation fails
=> throw user error when sandbox identifier input validation fails

.changeset/happy-starfishes-trade.md, packages/ai-constructs/src/conversation/conversation_handler_construct.ts
Bundling Bedrock SDK is problematic in default implementation case. I.e. when data construct uses conversation handler construct under the hood. 
That behavior demands that data construct bundles Bedrock SDK with it's dependencies as well. Which is not optimal.
We started conversation handler with bundling of Bedrock SDK because it was not available in Lambda runtime yet.
Since then however. Lambda has updated SDKs and they now include Bedrock. Which is also compatible with our default implementation.
Therefore, we disable bundling if default handler is used to simplify situation on data construct side.
This is another solution like [this one](https://github.com/aws-amplify/amplify-backend/pull/1962) that aims to simplify caller (upstream) situation and smoothen DX for preview purposes. …
=> Do not bundle AWS SDK if default implementation is used.

.changeset/fuzzy-poems-walk.md, packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_query_factory.test.ts, packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_query_factory.ts
This is a test we have today, which works as expected.
```ts
{
toolDefinition: {
name: 'toolName2',
description: 'toolDescription2',
inputSchema: {
json: {},
},
graphqlRequestInputDescriptor: {
queryName: 'testQueryName2',
selectionSet: 'testSelection3 testSelection4',
propertyTypes: {},
},
},
expectedQuery: `
query ToolQuery {
testQueryName2 {
testSelection3 testSelection4
}
}
`,
},
```
The `inputSchema: { json: {} }` is what the resolver should be passing the lambda if there aren’t any arguments. But apparently in some cases. we’re sending this (which is also a valid tool definition):
```ts
toolDefinition: {
name: 'toolName3',
description: 'toolDescription3',
inputSchema: {
json: {
type: 'object',
properties: {},
required: [],
},
},
},
```
I'll make the fix in the transformer to ensure …
=> fix(ai-constructs): invalid graphql generation for query tools

.changeset/famous-dryers-lie.md, packages/create-amplify/src/project_root_validator.ts
e2e tests for `create-amplify` were not happy about the change from an `Error `to an `AmplifyUserError`
- Reverted `AmplifyUserError` to `Error` in `create-amplify` that had been changed with the Activate prefer-amplify-errors PR
- added inline ignore to the `Error` so the linter stays happy
- marked with e2e to make sure all the `create-amplify` health checks are successful
=> Fix for create-amplify

.changeset/fresh-dancers-peel.md, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts, packages/sandbox/src/file_watching_sandbox.ts
Seeing the following errors in telemetry
`Failed to list secrets. ExpiredToken: The security token included in the request is expired`
add ExpiredToken in the list of credentials error
=> add ExpiredToken in the list of credentials error

.changeset/strange-jobs-refuse.md, packages/backend-output-storage/package.json, packages/backend-output-storage/tsconfig.json, packages/backend-platform-test-stubs/package.json, packages/backend-platform-test-stubs/tsconfig.json, packages/cli-core/package.json, packages/cli-core/src/package-manager-controller/execute_with_debugger_logger.ts, packages/cli-core/src/package-manager-controller/yarn_modern_package_manager_controller.test.ts, packages/cli-core/src/package-manager-controller/yarn_modern_package_manager_controller.ts, packages/cli/package.json, packages/cli/tsconfig.json, packages/client-config/package.json, packages/client-config/tsconfig.json, packages/deployed-backend-client/package.json, packages/deployed-backend-client/tsconfig.json, packages/integration-tests/package.json, packages/integration-tests/tsconfig.json, packages/model-generator/package.json, packages/model-generator/tsconfig.json, packages/plugin-types/package.json, packages/sandbox/package.json, packages/sandbox/tsconfig.json, scripts/check_package_json.ts
`cli-core` was previously unresolvable and would not trigger errors for `no-extraneous-dependencies`
**Issue number, if available:** https://github.com/aws-amplify/amplify-backend/issues/2001
- added main field to `cli-core`
- fixed violations adding a main field to `cli-core` and `plugin-types` caused
- `plugin-types` cannot keep its main field because of this test -- expected behavior for `plugin-types` is that it cannot export functional code can only be used for types, main field breaks this behavior
- updated comment in `check_package_json.ts` to explain why `plugin-types` must be ignored
linter is happy, violations of `no-extraneous-dependencies` relating to `cli-core` now appear
_By submitting this pull request, I confirm that my …
=> Fix for cli-core so it is no longer unresolvable

.changeset/spicy-monkeys-guess.md, .eslint_dictionary.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
When installed `aws-cdk` and `aws-cdk-lib` are not compatible a fault is raised.
**Repro.**
Create project like and use mismatched CDK versions.
```
{
"name": "testapp048",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"keywords": [],
"author": "",
"license": "ISC",
"devDependencies": {
"@aws-amplify/backend": "^1.2.1",
"@aws-amplify/backend-cli": "^1.2.6",
"aws-cdk": "2.130.0",
"aws-cdk-lib": "2.158.0",
"constructs": "^10.3.0",
"esbuild": "^0.23.1",
"tsx": "^4.19.1",
"typescript": "^5.6.2"
},
"dependencies": {
"aws-amplify": "^6.6.1"
}
}
```
Observe
Add mapping and classify as user error.
1. Added test.
2. Manual verification
_By submitting this pull request, I confirm that my contribution is made under …
=> Handle CDK version mismatch

.changeset/fuzzy-drinks-attend.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/backend-function/src/factory.ts
Currently if ESBuild running as a child process by CDK cli fails, CDK throws an error `Failed to bundle asset.....` without the actual error message. The actual error message is printed by the esbuild cli on the stderr which we skip scraping because of wrapping and throwing CDK error in an `AmplifyError`
This PR prevents wrapping if the error for instantiating the NodeJSFunction construct is from esbuild and let the cdk_deployer scrape the stderr and throw meaningful message.
=> throw ESBuild error with correct messages

.changeset/rich-jokes-divide.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Errors in a form of
```
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module ..../function/foo/resource.ts is not a valid package name imported from 
/Users/foo/Desktop/amplify-app/amplify/storage/foo/resource.ts
at new NodeError (node:internal/errors:405:5)
```
I.e. with extra `[ERR_INVALID_MODULE_SPECIFIER]`
were not captured.
Adjust regex.
Test added.
=> Improve type error regex

.changeset/fluffy-months-prove.md, packages/cli/src/backend-identifier/backend_identifier_resolver.test.ts, packages/cli/src/backend-identifier/backend_identifier_resolver.ts, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.test.ts, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.ts, packages/cli/src/commands/generate/forms/generate_forms_command.test.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.test.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts
When passing stack option for `generate schema-from-database` command, secret client `getSecret` is expecting backend identifier to be like https://github.com/aws-amplify/amplify-backend/blob/main/packages/plugin-types/src/backend_identifier.ts#L17 but it is resolved to `{ stackName: '<stack>' }`. So we fail to convert the backend identifier to parameter path strings for connection URI and SSL Cert secrets.
If stack is passed, we correctly convert to `BackendIdentifier` before getting secrets.
Updated test.
=> correctly handle stack argument for generate schema command

.changeset/itchy-vans-behave.md, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.test.ts, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts
Came from https://github.com/aws-amplify/amplify-backend/pull/2028#discussion_r1768862801.
If stack, app id, or branch are passed in as an argument for generate commands, there is no intention to run these commands against a sandbox.
Only fallback to resolving sandbox backend identifier if stack, app id, and branch are not passed in as arguments to generate commands.
Updated unit test.
=> update fallback for backend id resolvers if stack, app id, or branch are in args

.changeset/forty-squids-help.md, packages/eslint-rules/src/index.ts, packages/form-generator/src/local_codegen_graphql_form_generator.ts, packages/form-generator/src/s3_string_object_fetcher.ts, packages/model-generator/src/create_graphql_document_generator.ts, packages/model-generator/src/create_graphql_models_generator.ts, packages/model-generator/src/create_graphql_types_generator.ts, packages/model-generator/src/generate_api_code.ts, packages/model-generator/src/get_backend_output_with_error_handling.ts, packages/model-generator/src/graphql_document_generator.ts, packages/model-generator/src/graphql_models_generator.ts, packages/model-generator/src/graphql_types_generator.ts, packages/model-generator/src/s3_string_object_fetcher.ts, packages/schema-generator/src/generate_schema.test.ts, packages/schema-generator/src/generate_schema.ts
This PR revises expectations about errors for `X-generator` packages to prefer Amplify Errors.
Reasons:
1. We already use Amplify Errors in them. Changing that would be a break.
2. Translating errors in CLI would leak implementation details. This is unwanted.
3. In order to surface necessary information each of them would need to use error system similar to Amplify Errors.
4. Amplify Errors are part if `platform-types`. I.e. usable not only in "cli-ish" packages.
I fixed only one violation which was simple and left rest for the future. The priority is to establish these rules.
PR checks.
=> Prefer amplify errors in generators

.changeset/spicy-toys-scream.md, packages/schema-generator/src/generate_schema.test.ts, packages/schema-generator/src/generate_schema.ts
Invalid and empty schema errors indicate invalid inputs. I.e. user error.
Map these errors.
Added test.
=> Handle schema errors

.changeset/eleven-snails-move.md, .prettierignore, package-lock.json, packages/ai-constructs/API.md, packages/ai-constructs/package.json, packages/ai-constructs/src/conversation/conversation_handler_construct.test.ts, packages/ai-constructs/src/conversation/conversation_handler_construct.ts, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_executor.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_executor.ts, packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts, packages/ai-constructs/tsconfig.json, packages/backend-ai/src/conversation/factory.test.ts, packages/backend-ai/src/conversation/factory.ts, packages/backend-output-schemas/API.md, packages/backend-output-schemas/src/ai/conversation/index.ts, packages/backend-output-schemas/src/ai/conversation/v1.ts, packages/backend-output-schemas/src/index.ts, packages/backend/src/backend_factory.ts, packages/sandbox/package.json, packages/sandbox/src/lambda_function_log_streamer.test.ts, packages/sandbox/src/lambda_function_log_streamer.ts, packages/sandbox/src/sandbox_singleton_factory.ts
Conversation handler logs should show up when executing `npx ampx sandbox --stream-function-logs`.
This PR makes the following changes to stream and improve logs in conversation handler.
1. Adds logs with log level in conversation handler runtime componenets.
1. Conversation handler lambda is configured to emit structured logs. So that it supports log levels, see https://docs.aws.amazon.com/lambda/latest/dg/nodejs-logging.html for reference. I.e. we set log format to `json` as opposed to `text` (which doesn't support application log levels).
2. We add more `info` and `debug` logs around incoming event, bedrock invocations, tools invocation, emitting response. Debug logs dump request/response payloads.
2. We change Sandbox component to support arbitrary log group attached to lambda …
=> Stream conversation logs in sandbox

scripts/check_api_changes.ts, scripts/components/api-changes-validator/api_changes_validator.test.ts, scripts/components/api-changes-validator/api_changes_validator.ts, scripts/components/api-changes-validator/api_usage_generator.test.ts, scripts/components/api-changes-validator/api_usage_generator.ts, scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/src/index.ts
The way we test types assignment (attempt to assign to older copy of type) makes compiler fail for `FromJSONSchema`. This can be attributed to the way we test it rather than actual usage of the type. The attempt to compare current type to older copy of `FromJSONSchema` triggers it's deep computation mentioned in https://github.com/ThomasAribart/json-schema-to-ts/blob/main/documentation/FAQs/i-get-a-type-instantiation-is-excessively-deep-and-potentially-infinite-error-what-should-i-do.md .
Fixes:
```
at <anonymous> (/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:87:9)
at …
```
=> Exclude FromJSONSchema from api checks due to its complexity

.changeset/tender-camels-agree.md, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts, packages/integration-tests/src/test-project-setup/conversation_handler_project.ts, packages/integration-tests/src/test-projects/conversation-handler/amplify/constants.ts, packages/integration-tests/src/test-projects/conversation-handler/amplify/custom-conversation-handler/custom_handler.ts
Currently. We append a new message if bedrock emits multiple tool use blocks in single bedrock response.
However, bedrock then validates that we return it a single array with tool responses. NOT multiple messages with tool responses.
I.e. we want to fix this error.
Accumulate tool responses into single "user message" instead of multiple messages.
Enhanced both unit and e2e test to be sensitive to this scenario.
=> Fix case when multiple tools are requested by Bedrock.

.changeset/sixty-cycles-happen.md, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/conversation_handler_construct.ts, packages/ai-constructs/src/conversation/index.ts, packages/backend-ai/API.md, packages/backend-ai/src/conversation/factory.test.ts, packages/backend-ai/src/conversation/factory.ts, packages/backend-ai/src/conversation/index.ts
This PR solves two problems:
1. Defines type for conversation handler factory. This is to narrow down what `a.conversation({ ..., handler: })` can take. I.e. prevent using raw defineFunction.
2. Define and expose information about event version.
1. Adds return type for `defineConversationHandlerFunction`.
2. Adds information about conversation turn even version to both `ai-constructs` and `backend-ai`.
1. Event is a protocol/schema. Therefore `major.minor` is sufficient.
2. Typing is defined as `1.x` for the version.
1. This will trigger compiler when we introduce `2.x` and attempt to use incompatible version is made.
2. This surfaces a version value at runtime. So that upstream component is aware of which feature set of event is supported.
Added test.
_By submitting this pull request, I …
=> Add information about event version to conversation components

.changeset/modern-toys-jump.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Catch when CFN deployment fails to deploy stack because of errors with specific resources.
Update error mapper to catch these types of errors.
=> detect more generic CFN deployment failure errors

scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_namespace.ts, scripts/components/api-changes-validator/usage_statemets_renderer.ts
The usage snippets that are testing static symbols from namespaced class are not applying namespace correctly.
```
/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:100
throw new AggregateError(
^
at <anonymous> (/home/runner/work/amplify-backend/amplify-backend/scripts/check_api_changes.ts:100:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[errors]: [
Error: Validation of @aws-amplify/ai-constructs failed, compiler output:
index.ts(16,78): error TS2304: Cannot find name 'ConversationHandlerFunction'.
at ApiChangesValidator.validate …
```
=> allow trailing dot when applying namespace.

.changeset/early-starfishes-impress.md, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.ts, packages/ai-constructs/src/conversation/runtime/types.ts
1. GraphQL query returns `null` for fields that are not populated in a sparse block models.
2. Bedrock doesn't like `nulls` it likes `undefined`. I.e. fails with `"errorMessage": "ContentBlock object at messages.5.content.0 must set one of the following keys: text, image, toolUse, toolResult, document.",` when seeing `{text: null, image: null, toolUse: {...}}`
Source: https://www.reddit.com/r/ProgrammerHumor/comments/mqt9br/null_vs_undefined/
Add logic in message history retrieval to replace `null` with `undefined`
Added unit test.
=> Fix case where bedrock content blocks would be populated with 'null' instead of 'undefined.

.changeset/old-suns-float.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Add ability for error mapper to detect `TransformError` with multiple errors.
=> detect transform errors with multiple errors

.changeset/twenty-boxes-pretend.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Builds on top of https://github.com/aws-amplify/amplify-backend/pull/2097 to catch when CFN deployment fails because a stack failed creation.
=> detect generic CFN stack creation errors

.changeset/chilly-snakes-accept.md, packages/backend-secret/src/ssm_secret.test.ts, packages/backend-secret/src/ssm_secret.ts
GetParametersByPath API only supports returning at [max 10 results](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#systemsmanager-GetParametersByPath-request-MaxResults) at a time and requires pagination for further results.
Internally paginate the calls to return all secrets at once.
Out of scope: Updating the public API to paginate calls to `listSecrets`. This can be added in future if the need arises.
Unit tests and manually testing `ampx sandbox secrets list` command with more than 10 secrets in the sandbox.
=> fix: internally paginate list secret calls

.changeset/purple-dodos-kneel.md, packages/deployed-backend-client/src/deployed_backend_client.ts, packages/deployed-backend-client/src/deployed_backend_client_list_delete_failed_stacks.test.ts, packages/deployed-backend-client/src/deployed_backend_client_list_sandboxes.test.ts
`listBackends` [calls](https://github.com/aws-amplify/amplify-backend/blob/fb3538c58cfb25b6ae8aa5d4036be05bf1ee2181/packages/deployed-backend-client/src/deployed_backend_client.ts#L166-L167) `tryGetDeploymentType` to load the entire stack metadata and then infer deployment type from it.
This creates issue if the stack is being created or deleted and the metadata is not available causing the `fetchBackendOutput` to throw causing the `listBackends` call to fail.
Infer `deploymentType` from stack tags instead. If we can't we don't include that stack/backend in the result.
=> fix: detect deploymentType from Stack Tags

.changeset/happy-jokes-double.md, .changeset/tough-taxis-tan.md, package-lock.json, packages/backend-ai/API.md, packages/backend-ai/package.json, packages/backend-ai/src/conversation/factory.ts, packages/backend-data/package.json
The `AiModel` was moved to `data-schema-types`. Now we can use it instead of defining mirror type.
There are already existing tests that cover previously mirrored type. The shape of data doesn't change, only type name.
=> Use AiModel from data-schema-types as possible input

package-lock.json, package.json, scripts/cleanup_e2e_resources.ts
When troubleshooting e2e test failures, sometimes it's good to look at lambda logs. However, old, not cleaned up log groups makes this impossible as AWS Console loads 10k log groups before allowing searching for relevant one and due to overflow sometimes the interesting log groups are not even loaded.
Include log groups in e2e resource cleanup
https://github.com/aws-amplify/amplify-backend/actions/runs/11481721215
=> Add log groups to e2e resource cleanup script

.changeset/red-candles-fly.md, .changeset/tiny-ears-fly.md, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/conversation_handler_construct.test.ts, packages/ai-constructs/src/conversation/conversation_handler_construct.ts, packages/backend-ai/API.md, packages/backend-ai/src/conversation/factory.test.ts, packages/backend-ai/src/conversation/factory.ts, packages/backend-function/src/factory.ts
1. Default memory setting is too low.
2. Custom handler can run any arbitrary customer defined tool, ability to tweak memory is needed.
3. Function's default is documented incorrectly.
1. Add knob in conversation handler for memory settings
2. Bump conversation handler's default to 512MB
3. Fix `defineFunction` jsdocs.
Added tests
=> Add memory setting to conversation handler

package-lock.json
Introduced in https://github.com/aws-amplify/amplify-backend/pull/2164
`npm upgrade aws-cdk`
this Pr checks.
=> Upgrade CDK CLI to match CDK lib

.changeset/long-toys-suffer.md, packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.test.ts, packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.ts
Tool use and result blocks become irrelevant after turn is completed.
We persist "client side tools" blocks in history (as they require UI -> Appsync -> Lambda -> Bedrock roundtrip to work).
Including non-current turn's tools blocks in message history isn't incorrect but it costs tokens to process by Bedrock. Therefore, we remove them.
Add logic to message history retrieval that:
1. Finds where current turn begins
2. Removes any tool use/result blocks from non-current turns.
3. Squashes messages that belong to the same "role" (in case tool removal leaves continuous sequences of them).
1. Added unit test with most extreme case.
2. Existing unit tests cover the rest.
=> Remove tool usage for non current turns when looking up message history

.changeset/funny-papayas-invent.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Add `Stack:<stack-arn> is in <state> state and can not be updated` to our error mapping.
Unit test.
=> add stack is in a state and can not be updated to error mapper

.changeset/tidy-chicken-notice.md, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.test.ts, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts
Two errors are misclassified as faults while removing secrets:
1. When ssm parameter does not exist.
2. Another variant of invalid credentials.
Added handling logic.
Existing tests + new test.
=> Handle parameter not found error while deleting secret

.changeset/cool-pumpkins-dream.md, package-lock.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
The CdkErrorMapper was not properly handling the "Error: The security token included in the request is expired" error message, leading to potentially confusing error output for users with expired AWS credentials.
- Updated the CdkErrorMapper to catch both "ExpiredToken" and "Error: The security token included in the request is expired" errors
- Modified the error message to be more descriptive and user-friendly
- Added a new test case to cover the expanded error handling
- Updated the existing test to align with the current implementation
- Updated and added unit tests in `cdk_error_mapper.test.ts` to cover the new error handling
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> fix(backend-deployer): improve handling of expired AWS credentials

.changeset/new-buckets-mix.md, packages/client-config/src/client-config-writer/client_config_formatter_default.test.ts, packages/client-config/src/client-config-writer/client_config_formatter_default.ts, packages/client-config/src/client-config-writer/client_config_formatter_legacy.test.ts, packages/client-config/src/client-config-writer/client_config_formatter_legacy.ts
Fixes https://github.com/aws-amplify/amplify-backend/issues/2173 .
`$` is special characters in Dart. We're emitting outputs that contain `$` signs. That fails compilation.
Use raw Dart strings to disable interpolation.
1. Added tests.
2. Manual validation.
**Before**
**After**
=> Fix a bug where $ sign in dart outputs would fail compilation

.changeset/green-cups-jam.md, .eslint_dictionary.json, packages/backend-data/src/factory.ts, packages/backend-deployer/src/cdk_deployer.ts, packages/cli/src/commands/sandbox/sandbox_command.test.ts, packages/cli/src/commands/sandbox/sandbox_event_handler_factory.ts, packages/cli/src/error_handler.ts, packages/eslint-rules/src/index.ts, packages/eslint-rules/src/rules/amplify_error_no_instance_of.test.ts, packages/eslint-rules/src/rules/amplify_error_no_instance_of.ts, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts, packages/sandbox/src/file_watching_sandbox.ts
`AmplifyError`s are used across multiple packages. When package manager does not de-deuplicate dependencies. I.e. there are multiple copies of `amplify_error.js` in `node_modules` then each class (and it's hierarchy) is a separate island in runtime memory. This causes `instanceof` check to be unreliable when testing if error is an amplify error.
1. Add type predicate (see https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)
2. Replace `instaceof` with type predicate.
3. Add lint rule to prevent `instanceof AmplifyError`
PR checks.
=> Fix detection of AmplifyErrors

scripts/components/api-changes-validator/api_usage_statements_generators.ts, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/src/index.ts
Fixes type predicate handling in api check.
New syntax was introduced in https://github.com/aws-amplify/amplify-backend/pull/2200 .
1. Treat type predicate return type as boolean.
Added tests.
=> Handle type predicates in api check.

.changeset/eleven-numbers-hide.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
There are 2 new edge cases around CDK boostrap.
1. The stack might be outdated.
2. AWS creds might lack permissions to check parameter.
Map errors and provide resolution steps.
Added tests.
=> Handle errors when checking CDK bootstrap

.changeset/short-dryers-tell.md, packages/cli/src/command_middleware.test.ts, packages/cli/src/command_middleware.ts
When
```
export AWS_REGION=""
```
And running
```
npx ampx sandbox --debug
```
CLI throws:
```
Error: expected `region` to be configured for `aws.auth#sigv4`
[DEBUG] 2024-11-06T22:20:26.927Z: Error: expected `region` to be configured for `aws.auth#sigv4`
at /Users/sobkamil/playground/testapp059/node_modules/@aws-sdk/client-ssm/dist-cjs/auth/httpAuthSchemeProvider.js:11:23
at Object.defaultSSMHttpAuthSchemeParametersProvider [as httpAuthSchemeParametersProvider] (/Users/sobkamil/playground/testapp059/node_modules/@aws-sdk/client-ssm/dist-cjs/auth/httpAuthSchemeProvider.js:12:15)
at async /Users/sobkamil/playground/testapp059/node_modules/@smithy/core/dist-cjs/index.js:61:5
at async /Users/sobkamil/playground/testapp059/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
at …
```
=> Handle case when AWS region is configured as blank string

.changeset/violet-tools-clap.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts, packages/backend-function/src/layer_parser.test.ts
Work done in https://github.com/aws-amplify/amplify-backend/pull/2188 was too eager (no solid way to validate layer arn region with function region during synthesis). Reverting this change leaves us with the original error when layer arn region is not the same as function region which is not great:
```
The CloudFormation deployment has failed.
Caused By: The stack named <stack> failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "User: <user-arn> is not authorized to perform: lambda:GetLayerVersion on resource: <layer-arn> because no resource-based policy allows the lambda:GetLayerVersion action...
Resolution: Find more information in the CloudFormation AWS Console for this stack.
```
Update error mapping with instructions to …
=> update error mapping to catch when Lambda layer ARN regions do not match function region

.github/actions/setup_profile/action.yml
We're getting intermittent `InvalidSignatureException` exception in our e2e tests.
This seems to happen:
1. On Windows only.
2. With `e2e-tooling` profile only.
3. First SDK call with `e2e-tooling` profile seems to be failing, regardless of scenario.
This has been triaged to match:
https://github.com/aws-actions/configure-aws-credentials/issues/599
and 
https://github.com/aws-actions/configure-aws-credentials/issues/528
Example
Use `special-characters-workaround` which was added to handle this particular case.
Docs: https://github.com/aws-actions/configure-aws-credentials/blob/97834a484a5ab3c40fa9e2eb40fcf8041105a573/action.yml#L73-L75
This PR run.
=> Fix intermittent credential problem on Windows

.changeset/clean-hounds-exercise.md, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts
Bedrock Tools might be parameterless.
In that case bedrock either returns undefined input or blank.
Conditionally parse tool input.
added tests 
=> Fix case where tool use does not have input while streaming

.changeset/clever-emus-hope.md, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts, packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts, packages/integration-tests/src/test-project-setup/conversation_handler_project.ts, packages/integration-tests/src/test-projects/conversation-handler/amplify/constants.ts, packages/integration-tests/src/test-projects/conversation-handler/amplify/custom-conversation-handler/custom_handler.ts
This was missed in https://github.com/aws-amplify/amplify-backend/pull/2226
Fall back to empty object when bedrock is sending empty input.
Added e2e test for this particular case since problem was with bedrock runtime validation
=> Fix a case when Bedrock throws validation error if tool input is not persisted in history

.changeset/seven-chefs-trade.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts
There are legit cases when bootstrap url cannot be opened.
E.g.
- in headless environments
- if user does not have any app to open URL or lacks permissions to open it
- if browser crashes
Catch open errors, eat and log them (as debug logs), print url to the console.
added test
=> Print bootstrap url when browser cannot be opened

.changeset/hip-yaks-remain.md, packages/backend/src/engine/amplify_stack.test.ts, packages/backend/src/engine/amplify_stack.ts, packages/backend/src/project_environment_main_stack_creator.ts
For sandbox, some resources are still retained even after running `ampx sandbox delete`.
Set `RemovalPolicy` on all sandbox resources to `DESTROY` to guarantee all resources are destroyed when deleting a sandbox.
Unit tests. Local project with a stateful resource (OpenSearch) and ensure all resources are deleted after running `ampx sandbox delete`.
=> set removal policy for resources to destroy in sandbox deployments

.changeset/slimy-sheep-wonder.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
If the AWS account used does not have all permissions to perform deployment (not using the `AmplifyBackendDeployFullAccess` permission policy), deployment fails with an error like:
```
Error: Stack <stack> failed: ValidationError: User: <user-arn> is not authorized to perform: ssm:GetParameters on resource: <resource-arn> because no identity-based policy allows the ssm:GetParameters action
```
- Handle not authorized to perform on resource error
- Update so placeholders can be applied to resolution messages too (in this case to show the action in resolution)
Added test.
=> handle not authorized to perform on resource error

.changeset/nasty-jars-peel.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
`ENOENT` coming from npm indicate broken installation or workspace.
1. Introduce `CommonNpmError`.
2. Map just `ENOENT` errors for now.
3. Direct customer to https://docs.npmjs.com/common-errors in resolution.
Added tests.
=> Handle ENOENT error from npm

.changeset/chatty-goats-smell.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Mapping destroy failed errors from CDK that have to do with a stack being a failed state and some resources needing manual attention before deletion can occur.
N/A
Update to CDK error mapping
Updated CDK error mapping test
=> Catch "stack is in failed state, you may need to delete it from AWS Console" (DELETE_FAILED)

.changeset/poor-phones-attend.md, package-lock.json, packages/backend-deployer/package.json, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
generic cdk asset publish failures are categorized as unknown faults
extract the actual error and display more meaningful error message to customer.
=> fix: extract generic cdk asset publish failures

.changeset/forty-bulldogs-end.md, .changeset/new-rings-suffer.md, package-lock.json, packages/ai-constructs/package.json, packages/auth-construct/package.json, packages/backend-ai/package.json, packages/backend-auth/package.json, packages/backend-data/package.json, packages/backend-deployer/package.json, packages/backend-function/API.md, packages/backend-function/package.json, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts, packages/backend-output-storage/package.json, packages/backend-platform-test-stubs/package.json, packages/backend-storage/package.json, packages/backend/package.json, packages/client-config/API.md, packages/integration-tests/package.json, packages/platform-core/API.md, packages/plugin-types/package.json, packages/sandbox/package.json
Closes #2268
Add support to `@aws-amplify/backend-function` for Node 22, which is a [supported Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-deprecation-levels) that was added in [`aws-cdk-lib/aws-lambda` version `2.168.0`](https://github.com/aws/aws-cdk/releases/tag/v2.168.0) on November 20th, 2024
=> Allow Node 22 functions

.changeset/fair-ghosts-wave.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Error like `InvalidClientTokenId: The security token included in the request is invalid` was not mapped properly.
handle cdk error mapping for more generic invalid credentials
=> fix: handle cdk error mapping for more generic invalid credentials

.changeset/five-comics-beg.md, packages/platform-core/API.md, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
`AmplifyUserError`s were getting wrapped as UnknownFaults in `AmplifyError.fromError`
return amplify user error as it is from `AmplifyError.fromError`
=> fix: return amplify user error as it is from `AmplifyError.fromError`

.changeset/shy-lions-smash.md, .changeset/weak-nails-change.md, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts
Deployment can fail with the following error message when function environment keys are invalid:
```
1 validation error detected: Value at <environment-key> failed to satisfy constraint: Map keys must satisfy constraint: [Member must satisfy regular expression pattern: [a-zA-Z]([a-zA-Z0-9_])+]
```
Add validation for `defineFunction` environment prop.
Unit tests.
=> add validation for environment prop

.changeset/purple-news-do.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Error like `EPERM: operation not permitted, rename 'C:\Users\[...]\.amplify\artifacts\cdk.out\synth.lock.45040_1' → 'C:\Users\[...]\.amplify\artifacts\cdk.out\synth.lock'` not mapped properly. 
Updated `The stack named _stackName_ is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED` resolution message to suggest looking at original error message, has additional info about cause of error.
Handles errors like `EPERM: operation not permitted, rename 'C:\Users\[...]\.amplify\artifacts\cdk.out\synth.lock.45040_1' → 'C:\Users\[...]\.amplify\artifacts\cdk.out\synth.lock'`.
=> cdk error mapping EPERM errors relating to synth.lock

.changeset/rude-moles-attack.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Sometimes yarn customers are running into this issue during sandbox run. I'm able to reproduce this by having sandbox running with yarn and deleting node_modules (or perhaps a custom clean script) and making a file change in the backend.
Add error mapping to let customers know to install their dependencies again.
=> fix: add cdk error mapping for error 'command cdk not found'

.changeset/new-mails-speak.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
When trying to deploy a Lambda that exceeds the 250 MB size quota, deployment will fail with one of the following errors:
```
Error: <stack> failed: InvalidParameterValueException: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is <size-above-max> bytes.
```
```
Error: <stack> failed: InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes
```
Capture both of these errors in the CDK error mapper.
Unit tests.
=> add error mapping for lambda exceeding max size

.changeset/brave-walls-thank.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
For several reasons Lambda bundling results in an empty zip file and we see
```
Error: some-stack failed: InvalidParameterValueException: Uploaded file must be a non-empty zip
```
Add to the CDK error mapper to capture this with a generic resolution message of removing artifacts and trying again. Also includes a link to a GitHub issue with other scenarios and resolutions.
Unit tests.
=> add error mapping for lambda bundling into an empty zip

.changeset/shy-ladybugs-buy.md, packages/cli/src/commands/generate/generate_command.ts, packages/cli/src/commands/generate/generate_command_factory.test.ts
Currently there is no validation for stack name input in the generate commands. This fails later in CFN call with `ValidationError: 1 validation error detected: Value '@#$WDF@#R%' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*\|arn:[-a-zA-Z0-9:/._+]*`
Also from this [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stack.html) we can deduce that the stack name (the one not starting from `arn`) has a limit of 128 characters.
validate input stack name for generate commands
=> fix: validate input stack name for generate commands

.changeset/flat-donkeys-wonder.md, .changeset/olive-singers-tease.md, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.test.ts, packages/cli/src/backend-identifier/backend_identifier_with_sandbox_fallback.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts, packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
This PR addresses 2 problems:
1. There is no validation to confirm `--branch` and `--app-id` have inputs for the `pipeline-deploy` command. So something like this can be passed `npx ampx pipeline-deploy --branch --app-id` which results in the following error when we start tagging the root stack:
```
ValidationError: 2 validation errors detected: Value '' at 'tags.1.member.value' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'tags.2.member.value' failed to satisfy constraint: Member must have length greater than or equal to 1
```
2. For `generate` commands, if `--branch`, `--app-id`, or `--stack` have no inputs (eg. `generate outputs --stack`) we incorrectly fallback to sandbox resolver.
- Validate that …
=> validate branch and app id inputs for pipeline-deploy command

.changeset/real-yaks-bow.md, .changeset/silent-files-appear.md, packages/backend-function/src/factory.ts, packages/backend-function/src/layer_parser.test.ts, packages/backend-function/src/layer_parser.ts
We can currently use an ARN to add a layer. This PR would add support for just providing the `layerName:version` where the account-id and region are auto inferred using cdk improving DX. 
example:
```
layers: {
"sharp": "SharpLayerGen2:1", 
"@aws-lambda-powertools/logger":
"arn:aws:lambda:us-east-1:094274105915:layer:AWSLambdaPowertoolsTypeScriptV2:12",
},
```
=> updates layer to also use layername:version

.changeset/brown-mayflies-turn.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
If the role does not exist or permissions don't allow `sts:AssumeRole` for the role in question, sandbox throws with:
```
Error: ❌  <stack> failed: ValidationError: Role <role-arn> is invalid or cannot be assumed
```
This can be due to many reasons, one is if the CDK bootstrap exec role is deleted.
Add this error message to the CDK error mapper with resolution.
=> add error mapping for role is invalid or cannot be assumed error

.changeset/hip-buses-clap.md, packages/platform-core/src/errors/amplify_error.ts
There are `getaddrinfo ENOTFOUND` errors that do not match our current error handling (error messages may not start with `getaddrinfo ENOTFOUND`)
Update error handling logic.
Unit tests.
=> expand handling of getaddrinfo ENOTFOUND errors

.changeset/early-dodos-pull.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
A workaround for customers running into circular dependency was implemented here https://github.com/aws-amplify/amplify-backend/pull/2233 but the discoverability is still an issue for customers running into it.
Start with giving a detailed resolution step and for next steps, create a dedicated documentation page to handle circular dependencies. 
Unit tests and manual testing
=> chore: add error mappings and resolutions for circular dependency failures

.changeset/itchy-flowers-reply.md, packages/backend-data/src/convert_authorization_modes.test.ts, packages/backend-data/src/convert_authorization_modes.ts
If `defaultAuthorizationMode` is set to `"apiKey"` and `apiKeyAuthorizationMode` is not defined the deploy will fail with an error. On the data construct side `apiKeyConfig` is required if `defaultAuthorizationMode` is `API_KEY`. The `convertAuthorizationModesToCDK` should provide `apiKeyConfig` in this case.
```
Failed to instantiate data construct
Caused By: Cannot read properties of undefined (reading 'authenticationType')
Resolution: See the underlying error message for more details.
```
```typescript
import { type ClientSchema, a, defineData } from "@aws-amplify/backend";
const schema = a.schema({
Supermarket: a
.model({
name: a.string().required(),
address: a.string(),
})
.authorization((allow) => [allow.publicApiKey()]),
});
export type Schema = ClientSchema<typeof schema>;
export …
```
=> fix: allow apiKeyAuthorizationMode to be undefined if defaultAuthorizationMode is apiKey

.changeset/old-hornets-type.md, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.test.ts, packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_set_command.ts
When attempting to set a secret with an invalid character in the secret name, the following error appears:
```
SetSecretsFailedFault: Failed to set secrets. ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
Cause: {"name":"ValidationException","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"f5206be8-b8a6-411e-a959-979676f439af","attempts":1,"totalRetryDelay":0},"__type":"ValidationException","message":"Parameter name: can't be prefixed with \"ssm\" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix …
```
=> add validation for sandbox set command secret-name

.changeset/few-oranges-tell.md, packages/ai-constructs/API.md, packages/ai-constructs/src/conversation/conversation_handler_construct.test.ts, packages/ai-constructs/src/conversation/conversation_handler_construct.ts, packages/backend-ai/API.md, packages/backend-ai/src/conversation/factory.test.ts, packages/backend-ai/src/conversation/factory.ts
Addresses https://github.com/aws-amplify/amplify-backend/issues/2356 .
1. Add timeout property.
2. Map construct validation errors to amplify user errors.
Added tests.
=> Expose timeout property.

scripts/copy_template.ts
When Windows users attempt to use the command: `npm run new -- --template=<template> --name=<new name>`, it fails with `ENOENT: no such file or directory, lstat 'C:\C:\Users\[..]\amplify-backend\templates\empty-package'` -- specifically, the double C drive is a problem. 
Changed URL to use `host` instead of `pathname` when pulling the source and destination paths of the file -- see https://nodejs.org/api/url.html#urlobjecthost
Which also means that the line to jump one level out (`'..'`) is no longer needed. 
Tested on Windows and Linux dev desktop, was able to successfully make a new package using `npm run new -- --template=<template> --name=<new name>` on both. 
Results of running on Linux: 
_By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Adjustment for `copy_template.ts`

.changeset/new-maps-lay.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
When customers try to delete a sandbox, but a previous deployment is still in progress, CFN throws an error destroy failed Error: Stack [id] cannot be deleted while in status UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
catch and wrap deployment in progress when deleting the backend
=> chore: catch and wrap deployment in progress when deleting the backend

.changeset/chilly-pillows-live.md, packages/cli/src/commands/generate/forms/generate_forms_command.test.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/client-config/src/unified_client_config_generator.test.ts, packages/client-config/src/unified_client_config_generator.ts, packages/model-generator/src/create_graphql_document_generator.test.ts, packages/model-generator/src/create_graphql_models_generator.test.ts, packages/model-generator/src/create_graphql_types_generator.test.ts, packages/model-generator/src/get_backend_output_with_error_handling.ts, packages/sandbox/src/lambda_function_log_streamer.test.ts, packages/sandbox/src/lambda_function_log_streamer.ts
If the first deployment (sandbox/branch) is unsuccessful, the stack ends up getting created but stays in `CREATE_FAILED` state and doesn't have any outputs or metadata associated with it. This passes the check/error `NO_STACK_FOUND` since there is indeed a stack, but no outputs.
Add the new case of `NO_OUTPUTS_FOUND` and refactor bunch of `if` to a `switch`.
=> chore: wraps no outputs found error from backend output client

package-lock.json
Running `npm audit` we have a vulnerability from downstream dependency of `verdaccio`:
```
path-to-regexp  <0.1.12
Severity: moderate
Unpatched `path-to-regexp` ReDoS in 0.1.x - https://github.com/advisories/GHSA-rhx6-c78j-4q9w
fix available via `npm audit fix`
node_modules/path-to-regexp
express  4.0.0-rc1 - 4.21.1 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of path-to-regexp
node_modules/express
@verdaccio/middleware  <=8.0.0-next-8.6
Depends on vulnerable versions of express
node_modules/@verdaccio/middleware
verdaccio  2.2.7-r - 2.7.2 || 3.0.0-alpha.1 - 6.0.4 || 7.0.0-next.0 - 8.0.0-next-8.6
Depends on vulnerable versions of @verdaccio/middleware
Depends on vulnerable versions of express
Depends on vulnerable versions of verdaccio-audit
node_modules/verdaccio …
```
=> bump verdaccio

.changeset/tall-parrots-sort.md, packages/backend-function/API.md, packages/backend-function/src/factory.test.ts, packages/backend-function/src/factory.ts
Allows the users to choose between the available Lambda runtime architectures (`x86_64` and `arm64`).
**Issue number, if available:** 1820
This is a relatively simple change, which only adds the architecture field to the `defineFunction` function, with `x86_64` as its default value to keep backwards compatibility, and converts it to the corresponding CDK API `Architecture` value.
This change also introduced a new Architecture validation to guarantee that only valid values are used. Tests and documentation changes are also included.
=> Adds Architecture Property on defineFunction

.github/workflows/health_checks.yml, scripts/components/dependabot_version_update_handler.test.ts, scripts/components/dependabot_version_update_handler.ts, scripts/dependabot_handle_version_update.ts
There were some issues and the `handle_dependabot_version_update` workflow was not able to add a changeset file to Dependabot PRs.
- Update getting the branch name and sha from GitHub context (this removed the need for HEAD_SHA input for the script)
- Added fetch depth to `checkout` step so we can properly get the updated files
This PR https://github.com/aws-amplify/amplify-backend/pull/2393 that has these changes and is based off of this Dependabot version update PR https://github.com/aws-amplify/amplify-backend/pull/2387.
https://github.com/aws-amplify/amplify-backend/actions/runs/12588139778/job/35085511871
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> fix dependabot version update workflow

.github/workflows/health_checks.yml
`handle_dependabot_version_update` being skipped does not allow `do_include_e2e` step to run.
Remove `handle_dependabot_version_update` from `needs`.
=> remove handle_dependabot_version_update step from needs

.github/workflows/health_checks.yml
`handle_dependabot_version_update` job does not have the permission to write to Dependabot PRs, see https://github.com/aws-amplify/amplify-backend/actions/runs/12590013366/job/35090960677?pr=2387
Add permission mentioned in https://github.com/aws-amplify/amplify-backend/actions/runs/12590013366/job/35090960677?pr=2387#step:5:41 for the `handle_dependabot_version_update` job.
=> add permission to write to pull request for handle version update job

.changeset/curly-bags-cheer.md, package-lock.json, packages/auth-construct/API.md, packages/auth-construct/src/construct.test.ts, packages/auth-construct/src/construct.ts, packages/auth-construct/src/index.ts, packages/auth-construct/src/test-assets/lambda/handler.js, packages/auth-construct/src/types.ts, packages/backend-auth/API.md, packages/backend-auth/src/factory.test.ts, packages/backend-auth/src/factory.ts, packages/backend-auth/src/translate_auth_props.ts, packages/backend-auth/src/types.ts, packages/integration-tests/src/test-project-setup/advanced_auth_and_functions.ts, packages/integration-tests/src/test-projects/advanced-auth-and-functions/amplify/auth/resource.ts, packages/integration-tests/src/test-projects/advanced-auth-and-functions/amplify/backend.ts, packages/integration-tests/src/test-projects/advanced-auth-and-functions/amplify/func-src/handler_custom_sender.ts, packages/integration-tests/src/test-projects/advanced-auth-and-functions/amplify/function.ts, packages/integration-tests/src/test-projects/advanced-auth-and-functions/amplify/test_factories.ts
Adds sms configuration and custom sms sender to auth. Some implementation decisions:
* `KMSKeyArn` is duplicated in both `sms` and `email` custom senders since extracting it out will involve a breaking change and cognito only accepts one key for both senders. This change will throw an exception if different keys are used in both sms and email senders.
* We rely on CDK to create the IAM role if customer wants to enable SMS but doesn't explicitly provide one.
=> add sms configuration and custom sms sender to auth

.changeset/popular-insects-listen.md, packages/backend-function/src/lambda-shims/invoke_ssm_shim.ts
After the recent change of https://github.com/aws-amplify/amplify-backend/pull/2438, health checks are failing as lambda execution is failing with error
```console
"TypeError [ERR_INVALID_ARG_TYPE]: The \"callback\" argument must be of type function. Received undefined",
"    at setInterval (node:timers:212:3)",
"    at file:///var/task/index.mjs:1:1769",
"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```
I tried changing it to use IIFE as well and then instead I got the following error from lambda
```console
"TypeError [ERR_INVALID_ARG_TYPE]: The \"callback\" argument must be of type function. Received an instance of Promise",
"    at setInterval (node:timers:212:3)",
"    at file:///var/task/index.mjs:1:1769",
"    at …
```
=> remove the workaround for no-misused-promises as it broke lambdas execution

.changeset/slimy-fireants-cheer.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.test.ts, packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
Handle connect ENOMEM error
Upon investigation it turns out that this error happens randomly in our codebase whenever Node can't establish connection due to lack of available OS memory.
Added error handling in 3 places.
These places are:
1. Deployment - when CDK CLI makes remote calls to deploy or monitor deployments.
2. Secret commands - this got special handling to prevent conversion to fault.
3. I added generic logic in AmplifyError as well to handle errors coming from other commands that could make remote calls.
Added tests.
=> Handle connect ENOMEM error

.changeset/afraid-crabs-care.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/client-config/src/paths/get_client_config_path.test.ts, packages/client-config/src/paths/get_client_config_path.ts
Continuation of https://github.com/aws-amplify/amplify-backend/pull/2192 and https://github.com/aws-amplify/amplify-backend/pull/2267 we still see some instances of this error in telemetry. I've found three different causes
1. Customers using file paths in their backend definition that genuinely don't exist.
2. Customer providing a path for client config that cannot be created such as `/lib`
3. for `manifest.json` file in cdk.out directory. I believe this is similar issue as https://github.com/aws-amplify/amplify-backend/pull/2192 though I am not able to reproduce it by any means.
Unit tests
=> wrap more instances of ENOENT type errors

.changeset/happy-pianos-destroy.md, packages/cli/src/commands/generate/forms/generate_forms_command.test.ts, packages/cli/src/commands/generate/forms/generate_forms_command.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.test.ts, packages/cli/src/commands/generate/graphql-client-code/generate_graphql_client_code_command.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.test.ts, packages/cli/src/commands/generate/outputs/generate_outputs_command.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.test.ts, packages/cli/src/commands/generate/schema-from-database/generate_schema_command.ts
I've found that we don't enforce passing both `--app-id` and `--branch` for all generate commands.
It is possible to run `npx ampx generate outputs --branch <branch>`, when this happens we look at `name` in `package.json` but if this name does not match an existing Amplify app then we will get `Error: No apps found with name <app-name> in region <region>`.
Enforce passing both `--app-id` and `--branch` options for `generate outputs` and `generate graphql-client-code`, this aligns with `generate forms` and `generate schema-from-database` and our [docs](https://docs.amplify.aws/react/reference/cli-commands/#npx-ampx-generate).
Unit tests. Locally and in Amplify console.
_By submitting this pull request, I confirm that …
=> enforce branch option implying app id for generate commands

.changeset/sweet-sheep-march.md, packages/cli/src/commands/configure/profile_controller.test.ts, packages/cli/src/commands/configure/profile_controller.ts
Permissions tests with `chmod` were failing on CodeBuild
Updated the `chmod` tests to use mock instead
tests work locally
=> Update permissions tests in `ProfileController` to use mock

.changeset/good-falcons-attend.md, .eslint_dictionary.json, packages/platform-core/src/usage-data/account_id_fetcher.test.ts, packages/platform-core/src/usage-data/account_id_fetcher.ts, packages/platform-core/src/usage-data/serializable_error.test.ts, packages/platform-core/src/usage-data/serializable_error.ts
We include account id and error details can contain stack name and file paths with user info when being sent to our telemetry.
- "Bucketize" account ids and hash them
- Remove stacks from errors like we do with ARNs
- Make file paths in errors relative to remove user info
Unit tests.
=> anonymize account id and error details for telemetry

.changeset/hip-pens-walk.md, packages/cli-core/API.md, packages/cli-core/src/printer/printer.test.ts, packages/cli-core/src/printer/printer.ts
update start spinner api to accept the id instead of generating a new one. Allow clients to generate the ids themselves for associating the spinners. This helps clients to easily access spinners across the threads.
=> update start spinner api to accept the id instead of generating a new

.changeset/rich-sheep-double.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Recently our data schema errors have been prefixed by `_Toolkit`, we do not have a mapping to capture those
Added mapping to capture data schema errors prefixed with `_Toolkit`
=> Mapping for data schema errors

.changeset/real-pants-smash.md, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.test.ts, packages/deployed-backend-client/src/stack_metadata_output_retrieval_strategy.ts
Using CDK nag or doing `backend.stack.addMetadata()` causes Zod error when generating the `amplify_outputs.json` file. The Zod error is occurring when we are parsing the stack metadata in order to fetch backend outputs and the parsing is not expecting non backend output entries.
https://github.com/aws-amplify/amplify-backend/issues/2428
Filter out non backend output entries in stack metadata before parsing.
Unit tests
=> correctly handle non backend outputs from stack metadata

.changeset/itchy-geckos-end.md, packages/create-amplify/src/default_packages.json, packages/create-amplify/tsconfig.json
From https://github.com/aws-amplify/amplify-backend/pull/2544, introduce `default_packages.json` for create amplify
None for this PR, this only adds the json file which is currently not being used.
=> add default_packages.json

.changeset/eight-steaks-greet.md, packages/backend-storage/src/storage_access_policy_factory.ts, packages/integration-tests/src/find_deployed_resource.ts, packages/integration-tests/src/test-project-setup/cdk/auth_cdk_project.ts, packages/integration-tests/src/test-project-setup/reference_auth_project.ts
When we create policies for storage access, the id for each new policy is `storageAccess<stack node children length>`. This works to keep policies unique within a stack, but there is overlap when it comes to reference auth since each role will have a newly created policy overwriting the existing policy.
Prepend storage access policy id with stack to stop ids from clashing when using reference auth. This way auth and unauth roles get a new storage access policy when being referenced in another app.
Updated E2E test to ensure storage access policies start with storage stack.
=> update naming of storage access policies to also use stack

.changeset/great-swans-collect.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
- we were previously not mapping validation errors like `failed: ValidationError: Stack <some stack> cannot be deleted while TerminationProtection is enabled`
- the current mapping for `failed: ValidationError: Stack:<stack arn> is in STATE state and can not be updated` did not capture stacks that do not have hyphens (EX: some stacks come in looking like this - `amplifysomestack`)
- created a mapping for errors like `failed: ValidationError: Stack <some stack> cannot be deleted while TerminationProtection is enabled`
- updated the mapping for `failed: ValidationError: Stack:<stack arn> is in STATE state and can not be updated` to capture stacks without hyphens in their names
_By submitting this pull request, I …
=> Adds and updates mapping for some validation errors

.changeset/mighty-kids-thank.md, .eslint_dictionary.json, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
When watching for file changes for the sandbox command, the system may run out of watchers and throw the following error as a fault:
```
Error: inotify_add_watch on '/some/path' failed: No space left on device
```
Add logic to classify as user error with directions to increase the amount of watchers (system config file varies based on Linux distro so being vague here instead of pointing to the exact config file path).
Unit test
=> wrap inotify errors in AmplifyUserError

.changeset/smart-beds-exercise.md, packages/cli-core/src/printer/printer.test.ts
For some slower machines, the spinner (with 50ms refresh) only spins 3 times instead of 4 in 190 ms. 
See failing run https://github.com/aws-amplify/amplify-backend/actions/runs/13794734502/job/38583723506
This PR updates the refresh rate to 100ms to bridge the gap between slower and powerful machines.
=> increase spinner time to more accurately capture spinner refreshes in unit tests

.changeset/thirty-weeks-whisper.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts
When working with multiple profile or a region env variable set on a terminal session the sandbox can get deployed to a different region that what a user may be expecting. Showing the region at the start would help see what region is currently being used. 
example:
=> Shows region being used when starting sandbox

.changeset/shaggy-students-knock.md, package-lock.json, packages/ai-constructs/package.json, packages/auth-construct/package.json, packages/backend-ai/package.json, packages/backend-auth/package.json, packages/backend-data/package.json, packages/backend-deployer/package.json, packages/backend-function/package.json, packages/backend-output-storage/package.json, packages/backend-platform-test-stubs/package.json, packages/backend-storage/package.json, packages/backend/package.json, packages/create-amplify/src/default_packages.json, packages/integration-tests/package.json, packages/platform-core/package.json, packages/plugin-types/package.json, packages/sandbox/package.json
When attempting to upgrade the data construct for the migrations work (https://github.com/aws-amplify/amplify-backend/pull/1678) the [test_with_baseline_dependencies job failed](https://github.com/aws-amplify/amplify-backend/actions/runs/13724700722/job/38388428773). The [data construct was upgraded](https://github.com/aws-amplify/amplify-category-api/pull/3193) to CDK `aws-cdk-lib@2.180.0` and `aws-cdk@2.1001.0` and is no longer compatible with the lower versions of CDK. 
* Upgrade the data construct to 1.15.1 (needed for migrations)
* Upgrade to `aws-cdk-lib@2.180.0`
* Upgrade to `aws-cdk@2.1001.0`
I've separated this PR from the data migrations PR to simplify the reviews.
Automated tests
_By submitting …
=> Upgrade data construct and CDK

.changeset/easy-points-shop.md, packages/backend-function/src/factory.ts, packages/cli-core/src/loggers/amplify_event_logger_for_sandbox.test.ts, packages/cli-core/src/loggers/amplify_event_loggers.ts, packages/cli-core/src/loggers/cfn-deployment-progress/cfn_deployment_progress_logger.ts, packages/sandbox/src/file_watching_sandbox.ts
Few display related bugs in pretty sandbox
1. Suppress ESBuild bundling output.
2. Suppress some specific `stderr` messages that come from `aws-cdk-lib` that currently does not use IoHost to delivery logs
3. Dim the timestamp for CFN progress
4. Print `"Built and published assets"` only once.
=> fix small 'pretty sandbox' qa bugs

.changeset/shiny-forks-smell.md, packages/cli-core/API.md, packages/cli-core/src/loggers/amplify_io_events_bridge_singleton_factory.ts, packages/plugin-types/API.md, packages/plugin-types/src/amplify_io_host.ts
1. change `AmplifyEventMessage` interface to type
2. add printer type explicitly
API check for this PR will fail as well due to issues in baseline branch. Hopefully next PR would be successful. 
=> Fix API checks following the pretty sandbox change

.changeset/eighty-items-repeat.md, packages/sandbox/src/cloudwatch_logs_monitor.test.ts, packages/sandbox/src/cloudwatch_logs_monitor.ts
Fixes https://github.com/aws-amplify/amplify-backend/issues/2502
There is a hard limit on TPS for `FilterLogEvents` API that is Account wide. We don't want to get throttled if customers are streaming logs for a lot of functions.
**Issue number, if available:** #2502
Instead of calling `FilterLogEvents` API for all the functions concurrently, stagger them with a 0.5s wait in between.
=> stagger FilterLogEvents API calls to prevent throttling exceptions

.changeset/five-dancers-search.md, packages/create-amplify/templates/basic-auth-data/amplify/data/resource.ts
The default create-amplify template contains a deprecated authz mode set as the default for the data resource. It produces the following message when you deploy
```
Schema is using an @auth directive with deprecated provider 'iam'. Replace 'iam' provider with 'identityPool' provider.
```
This PR adjusts `iam` to `identityPool` as the default authz mode
=> create-amplify's data resource to use identityPool default authz

.changeset/ten-ravens-rest.md, .changeset/vast-dragons-yawn.md, packages/cli-core/src/format/format.test.ts, packages/cli-core/src/format/format.ts, packages/cli-core/src/loggers/amplify_event_logger_for_sandbox.test.ts, packages/cli-core/src/loggers/cfn-deployment-progress/rewritable_block.ts, packages/cli-core/src/printer/printer.ts, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts
Some updates to pretty sandbox display based on QA
1. Move the spinner between the timestamp and info message
2. Make the hierarchical error cause more obvious
3. Make the CFN progress display block collapsible instead of just expandable.
4. Keep the sandbox splash screen consistent
5. Start the sandbox with a clear screen
=> Updates to pretty sandbox display

.changeset/ripe-lemons-turn.md, packages/cli-core/src/loggers/amplify_event_loggers.ts, packages/cli-core/src/loggers/amplify_io_events_bridge_singleton_factory.ts
There can be a slight delay between messages "Built and published assets" and `Deployment in progress..." causing customers to believe that the process has hanged.
Change the CDK event marker to use `Deployment started` as a way to mark assets were published.
=> Use deployment started as a marker for assets published

.github/workflows/canary_checks.yml
This reverts commit 15d186b836262539809f412e1b70ae9d5fe958e1.
Turns out that canary build can overwrite current `HEAD` cache with artifacts produced from previous commit hash (pinned). This is unwanted side-effect. 
Undo the pinning.
I inspected couple of failing canary runs to figure out why they're faling.
it turns out they're restoring build cache from `HEAD` and therefore ignoring the pin effectively.
The other way problem is possible. I.e. canary run MAY create build cache for `HEAD` commit with stale code.
The reason is that scheduled run run with `HEAD` sha, if cache doesn't exist it will try to populate it, but we check out repo with old commit to build artifacts.
=> Revert "pin live canaries (#2626)"

.github/workflows/deprecate_release.yml, .github/workflows/restore_release.yml, scripts/components/git_client.ts, scripts/components/release_deprecator.ts, scripts/components/release_lifecycle.test.ts, scripts/components/release_restorer.ts, scripts/deprecate_release.ts, scripts/publish_runner.ts, scripts/restore_release.ts, scripts/version_runner.ts
While trying to deprecate recent release we encountered a problem:
One of packages was brand new. First time released. Therefore the algorithm was unable to find previous release to roll back to.
1. Add option to skip packages to rollback and restore workflow.
2. Print packages that failed to resolve previous release.
Tested with `@aws-amplify/seed` included here https://github.com/aws-amplify/amplify-backend/actions/runs/14094450735/job/39478789483 .
It failed but printed
```
Set npm registry to http://localhost:4873
Unable to resolve previous release tags for @aws-amplify/seed
Error: 
Expected release commit commit to be authored by github-actions[bot].
Instead found "Edward Foyle".
Make sure commit 42302df04380d044e8b7391c872628592ce9f9cf points to a release commit.
```
Tested with …
=> Add option to skip package

.changeset/slimy-mangos-draw.md, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_deployer.ts, packages/backend-deployer/src/cdk_error_mapper.ts
Minimum node version requirement for using amplify has been increased due to using tsx's dynamic import APIs.
throw more actionable error message for unsupported versions of node
=> throw more actionable error message for unsupported versions of node

.changeset/rare-buckets-show.md, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_command.ts, packages/seed/src/auth-seed/auth_client.test.ts, packages/seed/src/auth-seed/auth_client.ts
Found 2 issues with seed:
1. spinners provide spinner text to the MFA command line prompts (so you do not get the opportunity to provide your own input) and if you stop the spinners before entering the MFA flow, they will eat the output of the command line prompt
2. when using the email MFA flow, you may not have an `mfaConfig` because we do not support email in our MFA config, so you would get thrown an error even if you have email MFA set up in cognito
1. replaced spinners with a line of text when seed starts running that informs the customer seed is running (this line of text is not removed upon completion of seed since customers might be logging output to the console so we do not want to clear it)
2. re-configured the way `mfaConfig` detection works so if a customer is using email MFA …
=> Minor fixes for seed

.changeset/moody-friends-invent.md, .github/workflows/health_checks.yml, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
with the new cdk toolkit integration, the errors fed to the cdk_error_mapper have changed from being scraped from `stdout` to now fully structured errors. This causes the error mapper to not match some of the known common errors.
This is beginning of updating the error mapper to now start consuming structured errors to minimize falling back to unknown faults category
=> Update error matching and parsing based on toolkit integration

.changeset/ten-rings-crash.md, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_command.test.ts, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_command.ts
When seed used `execa`, we would not see the actual error message that were thrown to the customer while seed was running. instead all we would see is something like: `"message": "ExecaError: Command failed with exit code 1: tsx amplify/seed/seed.ts"`.
This appears as an unknown fault in our telemetry and is unhelpful for debugging the actual issue the customer may have run into.
Switches seed from using `execa` to run the seed script to using `tsImport`. `tsImport` allows us to run the seed script in the same process as the seed command so any error messages that appear will go through `stderr`.
Tested manually to ensure error messages still appear when running seed. Ensured seed command tests still operate correctly.
_By submitting this pull request, I confirm that my contribution is …
=> Seed uses tsImport instead of execa

.github/actions/build_with_cache/action.yml, .github/workflows/canary_checks.yml
Follow up on https://github.com/aws-amplify/amplify-backend/pull/2626 and https://github.com/aws-amplify/amplify-backend/pull/2630
1. Changes in main are not compatible with latest version that's live.
2. Using previous commit sha to build repo may corrupt HEAD's cache.
1. Pin live checks to use commit from before toolkit integration.
2. Change build action to get SHA for caching from local repo instead of github context.
Checks passing and caching as expected:
1. This PR checks.
1. Sample hash key `6f78b4675e7cff4bb5d99d3e24c1520c5d95dd96-node18-cdklibFROM_PACKAGE_LOCK`
2. `6f78b4675e7cff4bb5d99d3e24c1520c5d95dd96` is PR's merge commit (see https://github.com/aws-amplify/amplify-backend/commit/6f78b4675e7cff4bb5d99d3e24c1520c5d95dd96)
2. Manual health check run from head of branch …
=> Pin live canaries v2

.changeset/fair-crabs-laugh.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts
CDK's ESBuild execution happens in a [child process](https://github.com/aws/aws-cdk/blob/994e95289b589596179553a5b9d7201155bd9ed1/packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts#L332-L350).
This means that the errors are printed to stderr and not included in the error thrown.
wrap cdk's esbuild bundle error to remove clutter
=> wrap cdk's esbuild bundle error to remove clutter

.changeset/quick-pillows-type.md, packages/cli-core/src/printer/printer.test.ts
After this last change https://github.com/aws-amplify/amplify-backend/pull/2577 sometimes on a fast machine, the spinner ends up running one extra time just before the waiting period was over. See https://github.com/aws-amplify/amplify-backend/actions/runs/14346193591/job/40216502741
=> adjust spinner time to ensure it renders deterministic amount of time

.changeset/cool-olives-exist.md, packages/backend-data/src/convert_js_resolvers.test.ts, packages/backend-data/src/convert_js_resolvers.ts
JS resolvers are supposed to have `amplifyApiEnvironmentName` in the `ctx.stash`. See expectations here https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/batch-ddb-operations/ .
`amplifyApiEnvironmentName` was never sourced correctly outside of Sandbox.
I.e. nothing ever wrote the `amplifyEnvironmentName` CDK context entry in entire Gen2 backend ecosystem (backend and data repos).
The `amplifyEnvironmentName` is used by old Gen1 code and shouldn't have been used to source `amplifyApiEnvironmentName` in a first place.
PR changes the JS resolver logic to source `amplifyApiEnvironmentName` from gen2 cdk context keys.
Modified/added unit tests.
=> Fix amplifyApiEnvironmentName in non sandbox environments

scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/API.md, scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-with-namespace/src/some_sub_namespace.ts, scripts/components/api-changes-validator/usage_statemets_renderer.ts
Fixes
```
/Users/sobkamil/git/amplify-backend/scripts/check_api_changes.ts:100
throw new AggregateError(
^
at <anonymous> (/Users/sobkamil/git/amplify-backend/scripts/check_api_changes.ts:100:9) {
[errors]: [
Error: Validation of @aws-amplify/client-config failed, compiler output:
index.ts(100,13): error TS2552: Cannot find name 'AmplifyStorageAccessActions'. Did you mean 'AmplifyStorageAccessActionsBaseline'?
index.ts(101,21): error TS2552: Cannot find name 'AmplifyStorageAccessActions'. Did you mean 'AmplifyStorageAccessActionsBaseline'?
index.ts(102,33): error TS2552: Cannot find name …
```
=> Fix api check - array properties under namespaces

.github/dependabot.yml
Dependabot is opening plenty of eslint PRs separately.
These packages are connected by peer-deps.
This changes dependabot config to bundle all eslint packages together into single pr.
Note. This doesn't solve the peer dependencies problems in all cases.
However, there are the following benefits:
1. These dependencies usually have to be solved in single PR anyway, often manually. We can take over dependabot initial draft and iterate on that.
2. It should prevent dependabot of claiming most of the weekly PR quota for eslint packages.
Validation needs a merge to main.
=> group eslint upgrades together into single PR.

.github/dependabot.yml
We have some package jsons in test resources that are NOT used for dependency resolution at all.
It results in dependabot opening PRs like this https://github.com/aws-amplify/amplify-backend/pull/2769 .
Restrict directories to root and packages.
PR checks
=> Update directories scanned by dependabot

.github/workflows/canary_checks.yml
Canaries are timing out after release.
Undo workaround.
https://github.com/aws-amplify/amplify-backend/actions/runs/14736385952
=> Undo canary workaround

.changeset/blue-dots-count.md, packages/backend-deployer/src/cdk_deployer.test.ts, packages/backend-deployer/src/cdk_deployer.ts
We are missing mapping CDK errors thrown on `cdk.destory`
Add the same error mapper that is used for `deploy`
=> map errors from CDK destroy

.changeset/flat-spoons-enjoy.md, packages/backend-deployer/src/cdk_error_mapper.test.ts, packages/backend-deployer/src/cdk_error_mapper.ts, packages/platform-core/src/errors/amplify_error.test.ts, packages/platform-core/src/errors/amplify_error.ts
Some permissions related mappings are still missing, specially outside of cdk calls (e.g. generate commands)
add permissions related error mapping
=> add permissions related error mapping

.changeset/metal-foxes-argue.md, packages/sandbox/src/file_watching_sandbox.test.ts, packages/sandbox/src/file_watching_sandbox.ts
We don't display/print stack traces when sandbox deployments fail and customers are running in debug mode.
Display all stack traces in debug mode.
=> print stack traces in debug mode for sandbox deploy failures

.changeset/silver-lies-jam.md, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_command.test.ts, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_command.ts, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_policy_command.test.ts, packages/cli/src/commands/sandbox/sandbox-seed/sandbox_seed_policy_command.ts
Seed commands previously did properly resolve backends that were created using the `--identifier` flag and would throw errors instead of running the commands.
**Issue number, if available:** #2802 
Updates the way seed resolves sandbox backend Ids so it can properly resolve backendIds for sandboxes that were created with `--identifier`. 
Added new unit tests for this behavior and manually ensured that the seed commands work with and without the use of `--identifier`. 
=> Seed Command using Identifier

.github/dependabot.yml
Dependabot version upgrades are random right now. Which tends to open PRs for deps we care less about.
And the `production` strategy seems to be not great either. For example here https://github.com/aws-amplify/amplify-backend/pull/2777 - it bumps some packages in prod closure but not dev. And we do use some packages or parts of package groups as both prod and dev dependencies.
Change approach from "upgrade anything except some exceptions" to "here is list of dependencies we care most about, upgrade them". Or in other words - create allow list of depdendecies we care about most.
=> Use opt in list for dependabot upgrades

.github/workflows/health_checks.yml
Currently health checks are using `windows-latest` which maps to `windows-2022`. This runner is currently exhibiting degrading performance. 
`e2e_notices` test for windows and `check_api_changes` are often unable to complete within their current timeout windows, extended timeout windows for these tests.
A newer runner for windows, `windows-2025`, is available has better performance than previous runner when running health checks.
e2es are mostly successful. 
Health checks were eventually successful against this branch: https://github.com/aws-amplify/amplify-backend/actions/runs/15541874326
=> Switched Windows runner to 2025

package-lock.json
This is to resolve 
It seems that github started using different drive letter (C instead of D) overnight. We need to invalidate caches.
=> Poke package lock

.github/workflows/health_checks.yml
Undoes the hack where we removed package manager tests as release gate.
=> Re-gate release with package manager tests

.github/workflows/health_checks.yml
The current CI workflow has separate ulimit increase steps, but ulimit changes don't persist across GitHub Actions steps. Each step runs in its own shell session, so the ulimit increase has no effect on subsequent test execution steps.
- Remove ineffective dedicated "Increase ulimit" steps from GitHub Actions workflows
- Move ulimit increase inline with test execution commands so it applies to the same shell session
- Apply ulimit only when running on macOS runners where it's needed
This change fixes the ulimit configuration that was previously ineffective. The ulimit increase now actually applies to the test execution since it runs in the same shell session.
=> chore: move ulimit increase to per-step execution in CI workflows

.github/workflows/health_checks.yml
E2E tests can fail for a variety of reasons, and matrices are especially vulnerable to intermittent failure, due to the aggregation of several parameterized runs.
Implement retries for steps for which we anticipate or commonly see failures.
Run checks that include E2E tests.
=> test: retries on e2e matrix strategy and matrix generator jobs

.github/workflows/health_checks.yml
Added a 3x retry to `check_api_changes` on a commonly failing step.
Running the workflow in this PR.
=> fix: check_api_changes often fails on network error

.github/actions/run_with_e2e_account/action.yml, .github/workflows/health_checks.yml
E2E tests are flaky due to unreliable network. Some retries that are implemented are not effective.
Recent intermittent E2E test failures:
- [e2e_notices](https://github.com/aws-amplify/amplify-backend/actions/runs/18161676781/job/51693945882)
- [e2e_deployment](https://github.com/aws-amplify/amplify-backend/actions/runs/18147249166/job/51651447129)
- [e2e_sandbox](https://github.com/aws-amplify/amplify-backend/actions/runs/18024220824/job/51288284226)
Removed ineffective retries. Added retry for E2E Notices tests that have recently failed on ephemeral reasons.
Implemented retries for deployment and sandbox tests at the action level.
Workflows running on this PR, with label `run-e2e`.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> feat: retry e2e tests at the action level

.github/actions/setup_baseline_version/action.yml, .github/workflows/health_checks.yml
The `health_checks` workflow fails on the `Setup baseline version` due to network connectivity issues:
https://github.com/aws-amplify/amplify-backend/actions/runs/18266505828/job/52001722478#logs
There are no retries on this intermittently failing task.
Implemented retries in the `setup_baseline_version` action.
The workflow run on this PR will validate the change. `run-e2e` is applied.
=> fix: setup_baseline_version only runs once, and fails often on network instability

.github/workflows/health_checks.yml
The **check_api_changes** job is sometimes cancelled when the job exceeds the timeout of 20 minutes. This can happen when steps are retried (introduced in https://github.com/aws-amplify/amplify-backend/pull/3010).
Increased the timeout from 20 minutes to 60 minutes. Being generous here, as a successful run of step `Check API changes with retry` should take around *14 minutes*. If we try that step three times, a 60 min timeout should be able to cover the time needed for 3 tries and other steps in the run.
Run workflows on this PR.
=> fix: check_api_changes times out when steps are retried
