aws-amplify/amplify-backend

- .changeset/polite-poets-decide.md
- packages/auth-construct/src/construct.test.ts
- packages/auth-construct/src/construct.ts
- packages/backend-data/src/convert_authorization_modes.test.ts
- packages/backend-data/src/convert_authorization_modes.ts
- packages/backend-data/src/factory.test.ts
- packages/plugin-types/API.md
- packages/plugin-types/src/auth_resources.ts
> fix: Add Cfn Prefix to Auth cfnResources

- .changeset/perfect-terms-smile.md
- packages/create-amplify/README.md
Remove incorrect information from create-amplify readme
> Readme update

- .changeset/polite-goats-unite.md
- .eslint_dictionary.json
- package-lock.json
- packages/backend-data/package.json
- packages/backend/package.json
- packages/create-amplify/templates/basic-auth-data/amplify/data/resource.ts
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataamplifyDataTodo80505FFF.nested.template.json
- packages/integration-tests/package.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854astorage16B83955.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854astorage16B83955.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854astorage16B83955.nested.template.json
- packages/integration-tests/test-projects/minimalist-project-with-typescript-idioms/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/minimalist-project-with-typescript-idioms/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854astorage16B83955.nested.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
* Update template data/resource.ts to PM-approved (@renebrandel) content
* Bump `data-schema` versions to latest
* Update snapshots
> update data/resource template; bump data-schema versions

- .changeset/silent-crews-end.md
- package-lock.json
- packages/auth-construct/src/construct.ts
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-cjs/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-js/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-storage-auth-with-triggers-ts/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854aauth473E022C.nested.template.json
- packages/integration-tests/test-projects/minimalist-project-with-typescript-idioms/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
See: https://github.com/aws-amplify/amplify-backend/issues/678
Initial we thought the issue was due to missing conditions, but the conditions were there (they were recently added by this https://github.com/aws-amplify/amplify-backend/pull/625).
The real problem was the 'action' for the assume role policy.
> fix: Auth assume role action

- .github/actions/install_with_cache/action.yml
- package-lock.json
> test: change cache key back to original and update package lock

- .changeset/rich-pumas-know.md
- package-lock.json
- packages/backend-data/package.json
- packages/backend-data/src/convert_schema.test.ts
- packages/backend/package.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/create-amplify/templates/basic-auth-data/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/package.json
- packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/data-iterative-deploy/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-auth-modes/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplify-testAppId-testBranchName-branch-7d6f6c854a.template.json
- packages/integration-tests/test-projects/standalone-data-sandbox-mode/expected-cdk-out/amplifytestAppIdtestBranchNamebranch7d6f6c854adataE67321C2.nested.template.json
> fix: update tests for new validation

- .github/CODEOWNERS
> Update CODEOWNERS, include srquinn21

- .changeset/plenty-rules-sparkle.md
- packages/model-generator/src/appsync_graphql_generation_result.test.ts
- packages/model-generator/src/appsync_graphql_generation_result.ts
*Description of changes:* Fix creating android model files that have path embedded in it
> Fix creating android model files that have path embedded in it

- .changeset/empty-houses-thank.md
*Description of changes:* Bump to minor version for usage data consent
> Bump to minor version for usage data consent

- .changeset/fresh-lobsters-cheer.md
- packages/platform-core/src/config/local_configuration_controller.test.ts
- packages/platform-core/src/config/local_configuration_controller.ts
Closing file handle after reading config file.
> fix: close file handle warning

- .changeset/old-scissors-doubt.md
- packages/form-generator/src/local_codegen_graphql_form_generator.test.ts
- packages/form-generator/src/local_codegen_graphql_form_generator.ts
> Fix(formgen): exclude timestamps

- .changeset/few-eels-beam.md
- package.json
- packages/cli/package.json
*Description of changes:* fix: update package.json metadata
> fix: update package.json metadata

- CONTRIBUTING.md
- README.md
N/A
This PR addresses the README and CONTRIBUTING guide changes required for customers using the new Gen 2 experience.
> Changes to README and CONTRIBUTING guides for Amplify Backend

- .changeset/few-pillows-pay.md
- packages/backend/src/secret.ts
fixes #503 
adds link to secrets documentation in jsdoc for `secret()`
> add secrets docs link, fixes #503

- .eslint_dictionary.json
- package-lock.json
- packages/passwordless-auth-construct/API.md
- packages/passwordless-auth-construct/package.json
- packages/passwordless-auth-construct/src/common/passwordless_config.test.ts
- packages/passwordless-auth-construct/src/common/passwordless_config.ts
- packages/passwordless-auth-construct/src/custom-auth/index.ts
- packages/passwordless-auth-construct/src/otp/construct.test.ts
- packages/passwordless-auth-construct/src/otp/construct.ts
- packages/passwordless-auth-construct/src/services/ses_service.test.ts
- packages/passwordless-auth-construct/src/services/ses_service.ts
- packages/passwordless-auth-construct/src/types.ts
> feat(auth): OTP via Email

- packages/passwordless-auth-construct/src/services/sns_service.test.ts
- packages/passwordless-auth-construct/src/services/sns_service.ts
Fixed origination number attribute key per docs: https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html#sms_publish_sdk
> fix(passwordless): Fixed origination number attribute key

- packages/passwordless-auth-construct/src/constants.ts
- packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.test.ts
- packages/passwordless-auth-construct/src/custom-auth/custom_auth_service.ts
- packages/passwordless-auth-construct/src/magic-link/magic_link_challenge_service.test.ts
- packages/passwordless-auth-construct/src/magic-link/magic_link_challenge_service.ts
- packages/passwordless-auth-construct/src/mocks/challenge_events.mock.ts
- packages/passwordless-auth-construct/src/types.ts
- prefix metadata keys to prevent collisions with customer provided metadata
> chore: add prefix to metadata keys

- .github/workflows/canary_checks.yml
Updates the canary credential setup to match recent changes to e2e setup
> fix canary e2e creds

- .changeset/stale-ghosts-provide.md
- package-lock.json
- packages/backend-function/API.md
- packages/backend-function/src/factory.test.ts
- packages/backend-function/src/factory.ts
Adds config options for timeout, memory size and environment variables to `defineFunction`
> Add timeout, memory size and env vars to `defineFunction`

- .github/workflows/issue-pending-response.yml
adds GitHub Action to automatically remove the `pending-response` label when the author responds. Copied from https://github.com/aws-amplify/amplify-cli/blob/dev/.github/workflows/issue-pending-response.yml
> add issue pending response action

- packages/passwordless-auth-construct/src/construct.test.ts
- packages/passwordless-auth-construct/src/construct.ts
- packages/passwordless-auth-construct/src/mocks/construct.ts
- scope down SES policy to only allow sending from the specified email address.
> chore: scope down ses policy

- .gitignore
> gitignore .vscode dir

- .changeset/tender-ligers-cross.md
the storage-construct-alpha package has been removed from the repo and needs to be removed from pending changesets
> sanitize removed package from changeset

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Adds a PR template and updates the contributing readme to link to the proj arch readme
> add PR description template

- scripts/components/api-changes-validator/api_usage_generator.test.ts
- scripts/components/api-changes-validator/api_usage_statements_generators.ts
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/API.md
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/expected-error-message.txt
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/package.json
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/src/index.ts
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-constructor/tsconfig.json
- scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/API.md
- scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/src/index.ts
This is continuation of https://github.com/aws-amplify/amplify-backend/pull/800 .
Class constructor was not covered in api backwards compatibility check.
https://github.com/aws-amplify/amplify-backend/issues/655
This PR:
1. Adds coverage for concrete class constructor by generating snippets that call ctor.
2. Abstract class constructor by generating derived classes that call super()
3. Test.
1. Added tests to api check suite
2. This PR checks run on our packages without failure.
> add class constructor coverage to api check

- scripts/components/api-changes-validator/api_usage_generator.test.ts
- scripts/components/api-changes-validator/api_usage_statements_generators.ts
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-inheritance/API.md
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-inheritance/expected-error-message.txt
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-inheritance/package.json
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-inheritance/src/index.ts
- scripts/components/api-changes-validator/test-resources/test-projects/with-breaks/class-break-inheritance/tsconfig.json
- scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/API.md
- scripts/components/api-changes-validator/test-resources/test-projects/without-breaks/project-without-breaks/src/index.ts
Class inheritance was not covered in api check.
https://github.com/aws-amplify/amplify-backend/issues/871
This PR:
1. Adds snippet generators for class inheritance use cases.
2. Adds relevant tests.
1. Added tests
2. This PR checks use new rules
> cover class inheritance in api check

- .changeset/smooth-lies-complain.md
- packages/cli/src/command_middleware.ts
Customers following the instructions as is wouldn't be able to get to the right command. The `npx` part is required. Otherwise, it results in a "command not found: amplify" error.
N/A
Added the correct string
Tested it by running it manually with npx and it works.
> added npx prefix to command instructions

- .changeset/clever-eels-confess.md
- package-lock.json
- packages/backend/package.json
- packages/create-amplify/src/amplify_project_creator.ts
- packages/integration-tests/src/test-e2e/create_amplify.test.ts
`@aws-amplify/backend` was pinning version of CDK preventing customers from experimenting with higher versions of CDK.
However, we should still be pinning CDK somewhere until we figure out how to test "latest CDK".
Related issues:
This fixes https://github.com/aws-amplify/amplify-backend/issues/517#issuecomment-1876949678 .
This is part of https://github.com/aws-amplify/amplify-backend/issues/392 .
This PR changes a place where CDK library is pinned from `@aws-amplify/backend` to customer's project.
Therefore achieving two goals:
1. Setup customer with CDK that we tested our libraries with.
2. Let customers experiment with higher CDK versions.
E2E run is included in this PR checks.
_By submitting this pull request, …
> Move pinning of CDK version to customer's project

- .changeset/eight-suits-nail.md
- .github/workflows/health_checks.yml
Follow up on https://github.com/aws-amplify/amplify-backend/pull/892 to get changeset into consistent state.
See https://github.com/aws-amplify/amplify-backend/actions/runs/7466700483/job/20318680018?pr=890 (run from "Version Packages" PR).
This PR:
1. Adds missing changeset entries.
2. Adds a check that verifies that dependencies are consistent after executing `changeset version` (i.e. make sure that "Version Packages" PR is going to pass checks.
> Fix change sets

- .changeset/fair-shoes-yell.md
- package-lock.json
- packages/cli/package.json
- packages/cli/tsconfig.json
- packages/sandbox/package.json
We need to add @aws-amplify/backend-deployer to @aws-amplify/cli because it's used in https://github.com/aws-amplify/amplify-backend/blob/cefddd1b4f2113a6fa99dd00a811c3a7d9393e39/packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command_factory.ts#L2 
without it, yarn complains:
> Error: @aws-amplify/backend-cli tried to access @aws-amplify/backend-deployer, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> Add @aws-amplify/backend-deployer to @aws-amplify/cli as a dependency

- .changeset/honest-pumas-fold.md
- packages/cli/src/error_handler.test.ts
- packages/cli/src/error_handler.ts
In some cases the `error.message` printed by the top-level error handler only contains a generic error message when the real root-cause is in `error.cause.message`. This makes it difficult or impossible to debug some errors such as https://github.com/aws-amplify/amplify-backend/issues/914
Fixes https://github.com/aws-amplify/amplify-backend/issues/922 
Updates the top-level error handler to print error.cause.message in addition to error.message.
There are also some cases where error is undefined when calling handleError (specifically yargs arg validation errors) but the function was not typed to account for this. I have updated the TS types in the function to account for a possibly-undefined Error.
Tested locally, …
> If present, print error.cause.message in top-level error handler

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Updates issues template to use `npx amplify info` to collect information.
https://github.com/aws-amplify/amplify-backend/pull/952
> update issue templates to use info command

- .changeset/lemon-peas-sin.md
- .changeset/pre.json
- packages/create-amplify/src/amplify_project_creator.ts
> Enter prerelease mode with beta tag

- scripts/check_api_changes.ts
> update api check error message

- .changeset/giant-feet-sing.md
- packages/cli-core/src/package-manager-controller/yarn_classic_package_manager_controller.test.ts
- packages/cli-core/src/package-manager-controller/yarn_classic_package_manager_controller.ts
- packages/integration-tests/src/package_manager_sanity_checks.test.ts
We removed installing `tsc` for yarn-classic in https://github.com/aws-amplify/amplify-backend/pull/1016 and the [test didn't fail](https://github.com/aws-amplify/amplify-backend/actions/runs/7906775269/job/21583388198), because the `yarn create amplify` was not using the correct beta version.
This PR is to fix yarn-classic and the test.
Note: we have to install `create-amplify` saperately because [yarn create fails when specifying a package version ](https://github.com/yarnpkg/yarn/issues/6587)
- install `tsc` for yarn-classic
- install `create-amplify` in local folder and use the binary directly
> fix: yarn classic  Command "tsc" not found

- CONTRIBUTING.md
Trivial Change:
Just updated a really small typo in the CONTRIBUTION.md file
> Fix grammer typo in CONTRIBUTING.md

- package-lock.json
- package.json
- scripts/cleanup_e2e_resources.ts
Partially solves https://github.com/aws-amplify/amplify-backend/issues/918 .
I.e. adds orphan role removal to cleanup script.
Add role removal to cleanup script.
https://github.com/aws-amplify/amplify-backend/actions/workflows/e2e_resource_cleanup.yml?query=branch%3Aadd-role-cleanup
> Add role cleanup

- package-lock.json
- package.json
- scripts/cleanup_e2e_resources.ts
E2E tests leave orphaned SSM params
Add removal of stale SSM params to e2e script
https://github.com/aws-amplify/amplify-backend/actions/workflows/e2e_resource_cleanup.yml?query=branch%3Aadd-parameter-cleanup
> Add parameter cleanup

- package-lock.json
- package.json
- scripts/cleanup_e2e_resources.ts
E2E tests may leave orphan ddb tables.
Include DDB tables in resource cleanup.
https://github.com/aws-amplify/amplify-backend/actions/workflows/e2e_resource_cleanup.yml?query=branch%3Amore-cleanup
> test: ddb cleanup

- .changeset/new-kings-beg.md
- .changeset/rude-toys-visit.md
- .github/workflows/health_checks.yml
- package-lock.json
- packages/cli-core/API.md
- packages/cli-core/package.json
- packages/cli-core/src/package-manager-controller/package_manager_controller_factory.test.ts
- packages/cli-core/src/package-manager-controller/package_manager_controller_factory.ts
- packages/cli-core/tsconfig.json
- packages/create-amplify/README.md
- packages/integration-tests/src/package_manager_sanity_checks.test.ts
`create-amplify` doesn't work with pnpm on Windows because pnpm doesn't support nexted node_modules on Windoes. [See details](https://pnpm.io/faq#but-the-nested-node_modules-approach-is-incompatible-with-windows). This PR is to throw an error if it detects pnpm used on Windows.
- Throw error if detect pnpm used on Windows
- Add e2e test
- Add unit test
- Fix unit test for "unsupported" package manager
- Tested unit test on local with good and bad cases
- Tested e2e test https://github.com/aws-amplify/amplify-backend/actions/runs/8043894200
> feat(cli-core): throw error if detect using pnpm on Windows

- .changeset/chatty-icons-mix.md
- packages/backend-storage/src/access_builder.test.ts
- packages/backend-storage/src/access_builder.ts
The cognito identity id placeholder is `${cognito-identity.amazonaws.com:sub}` not `${cognito-identity.amazon.com:sub}`. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_cognito-bucket.html
Fixes the placeholder token
Updated unit tests
Created an issue to track additional work to make it possible to add e2e coverage for behavior like this: https://github.com/aws-amplify/amplify-backend/issues/1085
> Fix typo in cognito placeholder token in S3 access policy

- .changeset/two-shirts-type.md
Update changeset to minor version
> fix: update changeset to minor version

- .github/workflows/snapshot_release.yml
- package-lock.json
- package.json
- scripts/publish_runner.ts
- scripts/publish_snapshot.ts
We don't have a way to publish dev artifacts to NPM
Introduces snapshot release workflow which:
1. installs
2. builds
3. tests
4. checks version
5. publishes snapshot
Sample run with hardcoded tag:
https://github.com/aws-amplify/amplify-backend/actions/runs/8301839174/job/22722942275
Result:
https://www.npmjs.com/package/@aws-amplify/backend-cli/v/0.0.0-test-20240315202106
Usage in test app:
> Snapshot release workflow

- .changeset/eleven-crabs-arrive.md
- packages/create-amplify/templates/basic-auth-data/amplify/auth/resource.ts
the comments in this auth/resource template are distracting
removes the comments from the template
> remove comments from defineAuth template

- .changeset/fuzzy-eyes-protect.md
- .changeset/spotty-socks-share.md
- package-lock.json
- packages/cli-core/API.md
- packages/cli-core/src/format/format.ts
- packages/cli-core/src/printer/printer.ts
- packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.test.ts
- packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_get_command.ts
- packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_list_command.test.ts
- packages/cli/src/commands/sandbox/sandbox-secret/sandbox_secret_list_command.ts
The current sandbox list format is a bit difficult to read.
Additionally, the sandbox secret printing was implemented before we had the `format` object.
Update the `sandbox secret list` format to be more readable. Also did some localized refactoring to move record formatting to the format object rather than additional methods on the printer.
```sh
$ npx amplify sandbox secret list
names: GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET
```
```sh
$ npx amplify sandbox secret list
- GOOGLE_CLIENT_ID
- GOOGLE_CLIENT_SECRET
```
Or when there are no secrets configured:
```sh
$ npx amplify sandbox secret list
No sandbox secrets found. To create a secret use amplify sandbox secret set <secret-name>.
```
Manually tested and updated / …
> Improve sandbox secret list formatting

- .changeset/cyan-frogs-sort.md
- packages/create-amplify/templates/basic-auth-data/amplify/data/resource.ts
> updated the client sample to have `await`

- .changeset/fluffy-actors-add.md
- package-lock.json
- packages/backend-data/package.json
Incorporates  https://github.com/aws-amplify/amplify-category-api/pull/2398
Upgrade data dependency.
PR checks.
> upgrade data construct version

- .changeset/twelve-dogs-fail.md
- package-lock.json
- packages/auth-construct/API.md
- packages/auth-construct/src/construct.test.ts
- packages/auth-construct/src/construct.ts
- packages/auth-construct/src/index.ts
- packages/auth-construct/src/types.ts
Please review this ticket for details https://github.com/aws-amplify/amplify-backend/issues/1035
Tests updated.
> fix: Simplify User Attribute Mappings to use strings instead of objects

- .changeset/strong-years-flash.md
- packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.test.ts
- packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
Customers are curious what this command does and how to deploy from self-hosted runners.
Expose the details of this command from CLI help output.
Unit tests
> chore: Surface pipeline-deploy command in CLI command help

- .changeset/metal-foxes-explode.md
- packages/backend-data/src/convert_schema.ts
- packages/backend-data/src/factory.ts
- packages/backend-data/src/resolve_entry_path.ts
- packages/backend-data/src/types.ts
Follow up to https://github.com/aws-amplify/amplify-backend/pull/1213 with some comment/naming/error improvements
> chore: backend-data sql PR follow up: clean up comments, minor naming improvements

- .changeset/witty-pillows-kiss.md
- packages/client-config/src/client-config-writer/client_config_to_legacy_converter.test.ts
- packages/client-config/src/client-config-writer/client_config_to_legacy_converter.ts
fix: populate analytics legacy v5 config
fixes #1264
Unit tests
> fix: populate analytics legacy v5 config

- .github/workflows/health_checks.yml
In the event that we need to publish a hotfix to the latest release, we need a quick way to kick off a release that includes only the patch and no other changes that may have been merged to main since the release went out.
Updates the publish job to point the hotfix branch to the new release commit. Also updates the health_check and release workflow to run on the hotfix branch so that PRs made to that branch can be released using the changeset release action.
There's not a great way to test this. I validated the git push command locally. The other GH workflow syntax only runs during publishes so we'll know if this works the next time we publish. If it doesn't we can adjust accordingly.
_By submitting this pull …
> Update publish workflow to keep `hotfix` branch up to date with latest release commit

- .changeset/tiny-pans-promise.md
- packages/backend-storage/src/construct.ts
- packages/backend-storage/src/factory.ts
- packages/backend-storage/src/types.ts
Add more JSDocs for input props to `defineStorage`
> Expand `defineStorage` JSDocs

- .github/workflows/health_checks.yml
turns out docs that say "boolean" mean "string that is true or false"
> fix publish condition check

- .changeset/pretty-grapes-thank.md
- packages/create-amplify/templates/.eslintrc.json
- packages/create-amplify/templates/basic-auth-data/amplify/backend.ts
Update getting started template to match latest product spec
> Add docs link to getting started template

- .changeset/spotty-llamas-jump.md
- .changeset/tough-shirts-repeat.md
- packages/backend-storage/src/factory.test.ts
- packages/backend-storage/src/factory.ts
- packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts
Reverts aws-amplify/amplify-backend#1299
> Revert "fix: remove name validation on defineStorage"

- .changeset/selfish-toys-pump.md
testing hotfix release process
> test hotfix release process

- .changeset/selfish-games-hunt.md
- package-lock.json
- packages/backend-data/package.json
- packages/schema-generator/package.json
Upgrade data packages to release bug fix https://github.com/aws-amplify/amplify-category-api/pull/2470
* https://github.com/aws-amplify/amplify-category-api/pull/2471
* https://github.com/aws-amplify/amplify-category-api/pull/2470
Unit tests
> chore: upgrade data packages

- .changeset/flat-rivers-marry.md
- package-lock.json
- packages/backend-storage/API.md
- packages/backend-storage/src/types.ts
The 'read' storage access action is a convenience for 'get' and 'list'. Previously we allowed setting both 'read' and 'get' or 'list'. However, this is potentially confusing: does 'get' override 'read' or are they combined together?
To avoid this confusion, the actions type is updated to enforce that 'read' is mutually exclusive with 'get' and 'list'.
TODO
Existing test cases build and verified that expected errors are shown in the editor
> Update storage access action type

- .changeset/cold-pants-matter.md
- packages/auth-construct/API.md
- packages/auth-construct/src/construct.test.ts
- packages/auth-construct/src/construct.ts
- packages/auth-construct/src/types.ts
Users could not customize the invitation emails/sms messages that are sent to users when an administrator signs them up.
This adds support for customizing the email invitation settings.
> Add support for customizing user invitation settings

- .changeset/proud-cameras-flash.md
- package-lock.json
- packages/backend-data/package.json
- packages/form-generator/package.json
- packages/model-generator/API.md
- packages/model-generator/package.json
- packages/model-generator/src/generate_api_code.ts
- packages/model-generator/src/model_generator.ts
- packages/schema-generator/package.json
Bumps the codegen and data construct, schema generator dependencies.
Note that we're also re-introducing the `^` dependency on our packages since that would allow customers to consume latest versions without using overrides or bumping version in CLI.
> chore: bump data dependencies

- .changeset/hip-taxis-design.md
- package-lock.json
> update package lock

- .changeset/funny-toes-heal.md
Just a changeset to release the new package. 
Related: https://github.com/aws-amplify/amplify-backend/pull/1388
> Adds the ampx binary package

- .changeset/chilly-ducks-play.md
chore: re-increment versions for PR #1397
> chore: re-increment versions for PR# 1397

- .changeset/silver-lamps-fetch.md
- packages/create-amplify/templates/basic-auth-data/amplify/backend.ts
chore: remove unused assignment in create_amplify template
> chore: remove unused assignment in create_amplify template

- .changeset/shaggy-ants-bow.md
- packages/client-config/src/client-config-schema/schema_v1.json
outputs schema has a required `cognito_domain` property for `auth.oauth`, this updates the requirement to `domain`
> cognito_domain -> domain in outputs schema auth requirements

- README.md
Updates the repo readme to remove preview wording
> gen 2 GA readme update

- .github/actions/build_with_cache/action.yml
- .github/actions/install_with_cache/action.yml
- .github/actions/restore_build_cache/action.yml
- .github/actions/restore_install_cache/action.yml
- .github/actions/setup_node/action.yml
- .github/actions/setup_profile/action.yml
- .github/workflows/canary_checks.yml
- .github/workflows/deprecate_release.yml
- .github/workflows/e2e_resource_cleanup.yml
- .github/workflows/health_checks.yml
- .github/workflows/restore_release.yml
- .github/workflows/snapshot_release.yml
Bump relevant actions to latest
> Upgrade actions that use NodeJS

- .github/workflows/health_checks.yml
Follow up on https://github.com/aws-amplify/amplify-backend/pull/1455 .
Upgrade two remaining actions to address.
> Upgrade actions that use NodeJS part 2

- .github/workflows/health_checks.yml
CLI call on workflow dispatch and schedule needs GH token.
This is follow up to https://github.com/aws-amplify/amplify-backend/pull/1468 .
added env variable per GH instructions.
Tested using workflow dispatch here https://github.com/aws-amplify/amplify-backend/actions/runs/9007171701 .
(this should have been done in previous PR).
> Fix access to Github API

- .changeset/swift-planets-itch.md
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- README.md
- packages/create-amplify/src/amplify_project_creator.test.ts
- packages/create-amplify/src/amplify_project_creator.ts
- packages/create-amplify/src/project_root_validator.ts
- packages/integration-tests/src/test-e2e/create_amplify.test.ts
#1475
format text Amplify (Gen 2) to Amplify Gen 2
🙅‍♀️ Amplify (Gen 2)
🙆 Amplify Gen 2
> fix: refactoring text Amplify (Gen 2) to Amplify Gen 2

- .changeset/config.json
While we were releasing 0.x versions, we needed to force dependent packages to bump minor version ranges. However, this is no longer a problem with 1.x versions and causes unnecessary package version bumps. eg https://github.com/aws-amplify/amplify-backend/pull/1441/files#diff-5054c6f5427250c92eb0ec706125e0b624a7aecdf1c111589c7d7aa92d8b0559R21-R22
Remove changeset config that causes versions to be bumped even when they are within the existing semver range
> update changeset config

- .changeset/quiet-phones-cross.md
- .changeset/selfish-roses-mix.md
> chore: bump consumers of auth-construct & client-config

- .changeset/fair-hotels-buy.md
- packages/backend-storage/src/construct.test.ts
- packages/backend-storage/src/construct.ts
We currently don't enforce SSL, which triggers the warning. It's better to enforce SSL for user's security. 
> chore: enforce ssl for Storage

- .changeset/lucky-mails-accept.md
- packages/sandbox/src/file_watching_sandbox.test.ts
- packages/sandbox/src/file_watching_sandbox.ts
Parameter not found handling logic was missed in initial implementation causing error instead of redirecting to boostraping page. (see https://github.com/aws-amplify/amplify-backend/pull/1576)
https://github.com/aws-amplify/amplify-backend/issues/1616
Adjusted exception handling to catch https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-ssm/Class/ParameterNotFound/ .
1. Adjusted unit tests
2. Manual verification in non-boostraped region.
> fix parameter not found error while checking bootstrap status

- .changeset/red-wasps-promise.md
- .changeset/ten-masks-change.md
- package-lock.json
- packages/auth-construct/package.json
- packages/backend-auth/package.json
- packages/backend-data/package.json
- packages/backend-deployer/package.json
- packages/backend-function/package.json
- packages/backend-function/src/factory.ts
- packages/backend-output-storage/package.json
- packages/backend-platform-test-stubs/package.json
- packages/backend-storage/package.json
- packages/backend/package.json
- packages/integration-tests/package.json
- packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts
- packages/integration-tests/src/test-project-setup/data_storage_auth_with_triggers.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/func-src/handler_with_aws_sdk.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/function.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/test_factories.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/hotswap-update-files/function.ts
- packages/plugin-types/package.json
- packages/sandbox/package.json
- templates/construct/package.json
1. SDK provided in Lambda runtime is missing latest features.
2. Bundling SDKs with esbuild give performance gain see https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/ .
This PR:
1. Makes `defineFunction` include AWS SDK in bundling process by default. (There doesn't seem to be a reason to make it a knob, function runtime keeps working).
1. Esbuild will fail if package is not available locally
2. Mismatch between locally available APIs and lambda provided APIs is unwanted surprise.
3. Bumps CDK baseline version. This is because API required for AWS SDK bundling is available since `2.132.0`
The SSM snippet/header keeps dependency on Lambda provided SSM. There doesn't seem to be an easy way to make esbuild bundle that. Therefore that optimization will be …
> Bundle locally available AWS SDK packages by default

- .changeset/curly-bags-talk.md
- package-lock.json
- packages/cli/src/info/env_info_provider.test.ts
- packages/cli/src/info/env_info_provider.ts
Currently `ampx info` only prints the installed versions of `@aws-amplify/backend` and `@aws-amplify/backend-cli`. However, sometimes we need to know the specific version of a transitive amplify package to fully diagnose an issue.
Include all Amplify packages in `ampx info` output to aid in issue investigation
Tested manually and updated existing unit tests.
> Print all amplify package versions as part of `ampx info`

- package-lock.json
- package.json
API extractor changed api report name generation , see https://github.com/microsoft/rushstack/issues/4842
This PR pins api extractor version to last known good for us. This is temporary solution until we find better.
PR checks.
> pin api extractor

- .changeset/little-cars-fix.md
- package-lock.json
- packages/schema-generator/package.json
@aws-amplify/graphql-schema-generator includes an old version of fast-xml-parser.
Upgrade @aws-amplify/graphql-schema-generator to upgrade fast-xml-parser.
* Unit tests
> chore: upgrade graphql schema generator

- .changeset/wicked-crabs-switch.md
- packages/backend-ai/package.json
Lack of `main` entry point upsets Jest in data repo.
```
FAIL  src/__e2e__/model-auth-transformer.e2e.test.ts
● Test suite failed to run
Cannot find module '@aws-amplify/ai-constructs' from '../amplify-graphql-conversation-transformer/lib/grapqhl-conversation-transformer.js'
Require stack:
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-conversation-transformer/lib/grapqhl-conversation-transformer.js
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-conversation-transformer/lib/index.js
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-transformer/lib/graphql-transformer.js
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-transformer/lib/index.js
src/__e2e__/utils/index.ts …
```
> Add main entry point in backend-ai package.

- package-lock.json
Include the fix https://github.com/aws/aws-cdk/pull/30689
> fix: upgrade aws-cdk-lib@2.152.0

- .changeset/shy-pillows-join.md
- package-lock.json
- packages/auth-construct/package.json
- packages/backend-auth/package.json
- packages/backend-data/package.json
- packages/backend-deployer/package.json
- packages/backend-function/package.json
- packages/backend-output-storage/package.json
- packages/backend-platform-test-stubs/package.json
- packages/backend-storage/package.json
- packages/backend/package.json
- packages/integration-tests/package.json
- packages/plugin-types/package.json
- packages/sandbox/package.json
- templates/construct/package.json
follow up https://github.com/aws-amplify/amplify-backend/pull/1875
> Upgrade aws cdk lib

- .changeset/wicked-baboons-beam.md
- packages/ai-constructs/API.md
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts
- packages/ai-constructs/src/conversation/runtime/types.ts
Upstream callers can't customize model inference configuration
Expose inference configuration
Modified tests.
> Add ability to pass inference configuration

- .changeset/fifty-carrots-study.md
- packages/backend-deployer/src/cdk_error_mapper.ts
> make line endings in error mapper regex os independent

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
> updates issue templates

- .changeset/hot-tigers-speak.md
- package-lock.json
- packages/client-config/src/unified_client_config_generator.test.ts
- packages/integration-tests/package.json
- packages/platform-core/package.json
- packages/platform-core/src/object_accumulator.test.ts
- packages/platform-core/src/object_accumulator.ts
> relax object accumulator to accumulate parts with different versions but with same major version

- .changeset/moody-kangaroos-nail.md
- packages/backend-function/src/factory.ts
closes: https://github.com/aws-amplify/amplify-backend/issues/1932
related amplify docs update: https://github.com/aws-amplify/docs/pull/7931
> update cron jsdoc example

- .changeset/smooth-seahorses-applaud.md
- packages/ai-constructs/package.json
**Originally fixed in https://github.com/aws-amplify/amplify-backend/pull/1870 but lost when renaming packages...**
Lack of `main` entry point upsets Jest in data repo.
```
FAIL  src/__e2e__/model-auth-transformer.e2e.test.ts
● Test suite failed to run
Cannot find module '@aws-amplify/ai-constructs' from '../amplify-graphql-conversation-transformer/lib/grapqhl-conversation-transformer.js'
Require stack:
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-conversation-transformer/lib/grapqhl-conversation-transformer.js
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-conversation-transformer/lib/index.js
/Users/sobkamil/git/amplify-category-api-nofork/packages/amplify-graphql-transformer/lib/graphql-transformer.js …
```
> Add main entry point in ai-constructs package

- .changeset/eight-cars-train.md
- package-lock.json
- packages/backend-data/package.json
- packages/backend-data/src/factory.test.ts
Canaries started to fail https://github.com/aws-amplify/amplify-backend/actions/runs/10893420780/job/30228299757 .
The change is not breaking, but we should catch up.
1. Update data-construct dependency
2. Adjust tests.
Canary run: https://github.com/aws-amplify/amplify-backend/actions/runs/10905264373
> update data construct

- .changeset/silver-bulldogs-play.md
- packages/backend-secret/src/ssm_secret_with_amplify_error_handling.test.ts
- packages/backend-secret/src/ssm_secret_with_amplify_error_handling.ts
Handle parameter not found error.
Classify this as use error and direct customers to docs page about setting secrets.
1. Added test.
> Handle parameter not found error

- .eslint_dictionary.json
- scripts/stop_npm_proxy.ts
`npm:stop-proxy` command was unable to be run without an error on Windows, so verdaccio process could not be killed. This stems from `lsof` command not existing on Windows.
- Added check to see if user is running `stop-npm-proxy.ts` on Windows machine
- if user is using Windows machine, uses alternative command (`netstat` was the best equivalent to `lsof` that I could find for windows) to find PID of verdaccio so the process can be killed
- added netstat to eslint dictionary to get spellcheck rule to stop complaining
Checked that process running on verdaccio port is killed after `stop:npm-proxy` command is run
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Update to `stop:npm-proxy` for Windows

- .changeset/soft-gifts-exist.md
- packages/ai-constructs/API.md
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.test.ts
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.ts
- packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.test.ts
- packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/event_tools_provider.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_tool.test.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_tool.ts
- packages/ai-constructs/src/conversation/runtime/graphql_request_executor.test.ts
- packages/ai-constructs/src/conversation/runtime/graphql_request_executor.ts
- packages/ai-constructs/src/conversation/runtime/types.ts
This PR makes `x-amz-user-agent` header flow via handle to Bedrock and gql queries.
Changes:
1. Type headers in event as `Record<string, string>`
2. Pass header in Bedrock calls, per instructions in https://github.com/aws/aws-sdk-js-v3/blob/main/README.md
3. Pass header in GQL requests.
Added unit tests.
Make sure e2e tests are still passing.
> Pass user agent in conversation handler lambda

- .changeset/pink-rockets-dance.md
- package-lock.json
- packages/backend-function/API.md
- packages/backend-function/src/factory.test.ts
- packages/backend-function/src/factory.ts
- packages/integration-tests/package.json
- packages/integration-tests/src/test-in-memory/data_storage_auth_with_triggers.test.ts
- packages/integration-tests/src/test-project-setup/data_storage_auth_with_triggers.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/func-src/handler_no_minify.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/function.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/amplify/test_factories.ts
- packages/integration-tests/src/test-projects/data-storage-auth-with-triggers-ts/hotswap-update-files/function.ts
#2027
1. Add `minify` option to `defineFunction`. Default value is `true`.
Added test.
> Add minify option to defineFunction

- package-lock.json
Upgrade constructs.
This isn't fixing the root cause, it's just mitigating the problem.
The proper fix would be to assure that we don't have mixed constructs versions when we spin up e2e projects in couple of tests. But this is more involved and this PR's goal is to unblock main branch.
e2e tests
> upgrade constructs

- .changeset/quiet-elephants-do.md
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.test.ts
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.ts
Client side tool json elements may come as serialized JSON.
This makes Bedrock angry.
Parse these fields.
This makes Bedrock happy.
added tests
> Parse client side tool json elements

- .changeset/honest-ducks-act.md
- packages/cli/src/main_parser_factory.test.ts
- packages/cli/src/main_parser_factory.ts
adds `-v` and `-h` alias for version and help commands
> adds version and help short hand arguments

- .changeset/thin-candles-perform.md
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.test.ts
- packages/ai-constructs/src/conversation/runtime/conversation_message_history_retriever.ts
- packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.test.ts
- packages/ai-constructs/src/conversation/runtime/conversation_turn_response_sender.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/event_tools_provider.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_tool.test.ts
- packages/ai-constructs/src/conversation/runtime/event-tools-provider/graphql_tool.ts
- packages/ai-constructs/src/conversation/runtime/graphql_request_executor.test.ts
- packages/ai-constructs/src/conversation/runtime/graphql_request_executor.ts
- packages/ai-constructs/src/conversation/runtime/user_agent_provider.test.ts
- packages/ai-constructs/src/conversation/runtime/user_agent_provider.ts
We're not emitting basic data from conversation handler.
Enrich user agent.
1. Add library name and version (ai-constructs)
2. Add turn response mutation type
Added tests
> Add metadata to user agent in conversation handler runtime

- .changeset/strange-fans-crash.md
- scripts/check_package_versions.ts
GA release of backend AI features
PR checks
> GA release of backend AI features

- package-lock.json
Bumped version of verdaccio
Was previously out of date -- waiting for this: https://github.com/verdaccio/verdaccio/pull/4906 
> Version bump for Verdaccio

- .changeset/dry-falcons-hammer.md
- packages/platform-core/src/usage-data/usage_data.ts
- packages/platform-core/src/usage-data/usage_data_emitter.test.ts
- packages/platform-core/src/usage-data/usage_data_emitter.ts
It's hard to repro customer issues without knowing package manager.
Report npm user agent string.
added test
> Report npm user agent

- .changeset/orange-garlics-reflect.md
- packages/platform-core/API.md
- packages/platform-core/src/errors/amplify_error.test.ts
- packages/platform-core/src/errors/amplify_error.ts
Sometimes we fail deployment, or output generation, or anything that needs disk space.
Classify this as user error and provide resolution steps.
added test
> Handle insufficient disk space errors

- .changeset/warm-garlics-raise.md
- packages/backend-deployer/src/cdk_error_mapper.test.ts
- packages/backend-deployer/src/cdk_error_mapper.ts
Handle invalid package json e
Handle invalid package json error
added test
> Handle invalid package.json error

- .changeset/great-otters-study.md
- packages/backend-deployer/src/cdk_error_mapper.test.ts
- packages/backend-deployer/src/cdk_error_mapper.ts
There are more forms of transform errors:
```
Error [TransformError]: 
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.
Specifically the @esbuild/linux-arm64 package is present but this platform
needs the @esbuild/darwin-arm64 package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying node_modules
into a Docker image that runs Linux, or by copying node_modules between
Windows and WSL environments.
If you are installing with npm, you can try not copying the node_modules
directory when you copy the files over, and running npm ci or npm install
on the destination platform after the copy. Or you …
```
> add more forms of transform errors to cdk error mapping

- .changeset/healthy-trains-doubt.md
- packages/backend-deployer/src/cdk_error_mapper.test.ts
- packages/backend-deployer/src/cdk_error_mapper.ts
fix: map another form of access denied validation error
CDK Error mapping updates. 
> fix: map another form of access denied validation error

- package-lock.json
Upgrade CDK to a version that passes e2e tests.
Related to https://github.com/aws-amplify/amplify-backend/issues/2277 
pr checks
> Upgrade CDK

- .changeset/perfect-grapes-lay.md
- packages/cli/src/commands/pipeline-deploy/pipeline_deploy_command.ts
Fix check introduced in https://github.com/aws-amplify/amplify-backend/pull/2301.
> fix pipeline-deploy check

- CONTRIBUTING.md
Add section about debugging into contributing guide.
> Add debug section to contributing guide.

- .github/CODEOWNERS
Add console team as codeowners for packages used by them.
PR checks
> Add console team as codeowners for packages used by them.

- .changeset/short-schools-act.md
- packages/platform-core/src/errors/amplify_error.test.ts
- packages/platform-core/src/errors/amplify_error.ts
> chore: wrap out of memory errors

- .github/workflows/health_checks.yml
Update the name of the workflow to match the new name of the script.
Set the GitHub token for the script to use.
> update github workflow for handling dependabot version update pull requests

- .github/workflows/health_checks.yml
`handle_dependabot_version_update` is not able to push to the Dependabot PR, see https://github.com/aws-amplify/amplify-backend/actions/runs/12602337092/job/35125382663?pr=2387.
Add `contents: write` to permissions for the job.
> add permission to write contents for handle version update job

- .changeset/three-adults-breathe.md
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.test.ts
- packages/ai-constructs/src/conversation/runtime/bedrock_converse_adapter.ts
Related to https://github.com/aws-amplify/amplify-backend/issues/2356 .
When reading the logs. It's hard to say whether lambda hangs on network (or whatever else) or whether the content is large enough to keep it busy until timeout hits.
Log processed chunk count. But do it sparsely, so that we don't log too much.
Added unit test.
> Log conversation handler streaming progress

- .changeset/seven-hounds-speak.md
- packages/sandbox/src/file_watching_sandbox.test.ts
- packages/sandbox/src/file_watching_sandbox.ts
Updates the message to be more informative as this enable users to see what region is being used. additionally, add info on `--profile` and env variables. 
closes: https://github.com/aws-amplify/amplify-backend/issues/2419
> Updates bootstrap message with more info

- .changeset/stupid-coats-smoke.md
- packages/platform-core/src/usage-data/account_id_fetcher.test.ts
- packages/platform-core/src/usage-data/account_id_fetcher.ts
Follow up for https://github.com/aws-amplify/amplify-backend/pull/2519.
Improve anonymization for accountId in response to https://github.com/aws-amplify/amplify-cli/pull/14113#discussion_r1962107883.
Added unit test to make sure accountIds fall into different buckets.
> improve anonymization for accountId

- .changeset/pink-grapes-flow.md
- package-lock.json
- packages/backend-deployer/src/cdk_error_mapper.test.ts
- packages/backend-deployer/src/cdk_error_mapper.ts
- packages/platform-core/src/errors/amplify_error.test.ts
- packages/platform-core/src/errors/amplify_error.ts
Signature mismatch errors are misclassified as fautls.
Add logic in:
- amplify error (handles generate outputs command for example)
- cdk error mapper (handles deployments)
added tests
> Handle signature mismatch error

- .changeset/pretty-bees-repair.md
- packages/platform-core/API.md
- packages/platform-core/src/index.ts
- packages/platform-core/src/telemetry-data/telemetry_data.ts
Add new telemetry schema, it should be the zod schema equivalent of https://github.com/aws-amplify/amplify-backend/pull/2485/files#diff-9a2ed6b46647cb347741b6e5bff379cf04c360f290cd286e87490819585f8e5f.
> add telemetry schema

- .github/workflows/health_checks.yml
Create amplify test on Node 18 is slow due to lot of warnings.
Node 18 is EOL in a month.
Run create amplify test on Windows on Node 20 instead.
e2e tests
> Run create amplify on node 20 on windows

- .changeset/whole-shrimps-send.md
- package-lock.json
- packages/create-amplify/src/default_packages.json
https://github.com/aws-amplify/amplify-backend/security/dependabot/68
`npm upgrade aws-cdk-lib`
pr checks.
> upgrade aws-cdk-lib

- scripts/components/git_client.ts
- scripts/components/release_deprecator.ts
- scripts/start_npm_proxy.ts
`@aws-amplify/seed` was never released. This is not accounted for in rollback workflow. 
Exclude seed in rollback workflow to unblock it.
Dry run https://github.com/aws-amplify/amplify-backend/actions/runs/14088239897
> Temporary fix for rollback workflow

- .changeset/nice-icons-press.md
- package-lock.json
- package.json
- packages/cli/package.json
- packages/create-amplify/package.json
update supported node versions in package.json
> update supported node versions in package.json

- .github/workflows/canary_checks.yml
Changes in main are not compatible with latest version that's live.
Pin live checks to use commit from before toolkit integration.
Dry run https://github.com/aws-amplify/amplify-backend/actions/runs/14090937859 
> pin live canaries

- scripts/components/git_client.ts
- scripts/components/release_deprecator.ts
Undo temporary fix from https://github.com/aws-amplify/amplify-backend/pull/2620 after we rolled back.
> undo temporary fix

- .github/dependabot.yml
- package-lock.json
- package.json
Version bump of `api-extractor` reintroduced breaking behavior referenced here: https://github.com/microsoft/rushstack/issues/4842
(discovered this behavior made a return while working on something that required an update to API.md)
Reverting `api-extractor` back to the version we were using previously which allows us to continue with how we were previously naming files.
Pinned `api-extractor` to the version this PR reverts us back to and has dependabot ignore any future updates to this package.
Made a change that would change the output of `api-extractor` and got a file with the expected name after running `api-extractor`
> Revert `api-extractor` version bump

- .changeset/funny-lizards-dress.md
- package-lock.json
- packages/backend-deployer/package.json
- packages/backend-deployer/src/cdk_deployer.test.ts
- packages/backend-deployer/src/cdk_deployer.ts
- packages/plugin-types/package.json
> upgrade cdk-toolkit to 0.2.0

- .github/workflows/health_checks.yml
- scripts/do_include_e2e.ts
https://github.com/aws-amplify/amplify-backend/issues/781
Fail fast if not from main repo.
This PR checks
> Fail fast if e2e tests if PR is from fork.

- .changeset/shaky-news-juggle.md
- packages/backend-data/src/factory.ts
- packages/backend-data/src/types.ts
Data migration features are marked as experimental before release.
Remove experimental tag from data migration features.
N/A
> chore: prep data migrations release

- .github/dependabot.yml
1. Add more dependabot groupings.
2. Ignore `@types/node` . This should stick to lowest node we support.
PR checks.
> Tweak dependabot configuration

- .github/workflows/canary_checks.yml
Data release caused some packages to have inconsistent versioning
Turning off dependencies check in canaries until the next data release goes out.
Canary run: https://github.com/aws-amplify/amplify-backend/actions/runs/15572490141/job/43851081639
> Temporarily disable dependencies check in canaries

- package-lock.json
Bump undici to address dependabot warning.
> Bump undici

- .github/workflows/health_checks.yml
Create amplify and package manager tests on Windows have a tendency to almost finish and time out on Windows workers.
Increase timeout there as there doesn't seem to be other solution for this.
Long but stable test is better than flaky.
> Increase timeout for e2e create and package manager windows tests

- package-lock.json
Fixes https://github.com/aws-amplify/amplify-backend/security/dependabot/74
> Bump brace-expansion

- .github/workflows/health_checks.yml
Health checks were failing due to a recent change in https://github.com/aws-amplify/amplify-backend/pull/3004/files. Code that runs cross-platform was failing on Windows, as it expected PowerShell code but got Bash. The failed health checks were skipped on the previous pull request, as it did not have the `run-e2e` label assigned.
```
ParserError: D:\a\_temp\1d9f3d7f-0fec-45c9-80d1-c0a2502d9153.ps1:2
Line |
2 |  [[ "$RUNNER_OS" == "macOS" ]] && ulimit -n 10000
|   ~
| Missing type name after '['.
Error: Process completed with exit code 1.
```
Removed the code that caused the workflow failure, and replaced it with a cross-platform solution.
Ran the previously failing workflows by adding `run-e2e` label to this PR.
_By submitting this pull request, I confirm that my contribution is made …
> fix: health checks fail on bash code where ps script is expected
